# -*- coding: utf-8 -*-
"""
curiana_escena_era2.py — la escena de la era 2: dónde está cada uno.

GENERADO por 6-fusion/scripts/generar_escena_era2.py desde
6-fusion/escena_era2.yaml, que a su vez deriva del elenco con
6-fusion/scripts/derivar_escena_por_lugar.py --canon. No se edita a mano:
se corrige la tabla del derivador, se regenera el YAML y se regenera este
módulo. test_escena_era2.py vigila que sea lo que el script emite.

Ninguna fila se escribió agente a agente: la clase de oficio sale de la
ficha por palabras clave declaradas y el lugar sale de una plantilla
resuelta con la ficha. Cambiar el elenco cambia esta tabla sin tocarla.

La puerta del motor NO es este módulo sino curiana_escena.py, que lo lee.
"""

ERA = 'era2'
MUNDO = 'PARAGUANÁ'

MOMENTOS = ('amanecer', 'mañana', 'mediodia', 'tarde', 'anochecer', 'noche')
PERIODOS = ('viento', 'seca_larga', 'siembra')

# Las decisiones de Miguel del 2026-09-17 que esta tabla aplica.
DECISIONES = {
    '1': 'A — tabla por momento, con las excepciones que el canon fecha',
    '2': 'B — compartidos: el Capubana y el camino Moruy–Caseto («la alianza»)',
    '3': 'A — las escenas que salgan, sin tope: un pescador solo en el agua es el dato',
    '4': 'A — la ventana de 12 no cambia; la escena sólo dice dónde está cada uno',
    '7': 'A — `--capubana-cada N` declarado y sellado en la config (N = 3 en la primera cadena)',
}

# ============================================================
# LOS LUGARES — 28, ninguno sin sitio ni coordenada
# ============================================================

LUGARES = {
    'Capubana': {
        'tipo': 'aldea',
        'sitio': 'Capubana',
        'nodo': 'COMPARTIDO',
        'lat': 11.8183,
        'lon': -69.9524,
        'glosa': 'el cerro Capubana',
        'locacion': None,
        'extremos': None,
        'puntos': None,
        'compartido': 'estructura_social_era2.yaml decision_creativa_2026-09-14.capubana',
    },
    'Capubana:fuente': {
        'tipo': 'locacion',
        'sitio': 'Capubana',
        'nodo': 'COMPARTIDO',
        'lat': 11.818,
        'lon': -69.952,
        'glosa': 'la fuente del cerro',
        'locacion': 'fuente',
        'extremos': None,
        'puntos': None,
        'compartido': 'clima_era2.yaml abre_y_cierra.Capubana (NO CIERRA NUNCA)',
    },
    'Carirubana': {
        'tipo': 'aldea',
        'sitio': 'Carirubana',
        'nodo': 'AMUAY',
        'lat': 11.694,
        'lon': -70.218,
        'glosa': 'Carirubana',
        'locacion': None,
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Carirubana:orilla': {
        'tipo': 'locacion',
        'sitio': 'Carirubana',
        'nodo': 'AMUAY',
        'lat': 11.694,
        'lon': -70.218,
        'glosa': 'la orilla de Carirubana',
        'locacion': 'orilla',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Carirubana:taller': {
        'tipo': 'locacion',
        'sitio': 'Carirubana',
        'nodo': 'AMUAY',
        'lat': 11.694,
        'lon': -70.218,
        'glosa': 'el taller de Carirubana',
        'locacion': 'taller',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Carirubana:taller_canoas': {
        'tipo': 'locacion',
        'sitio': 'Carirubana',
        'nodo': 'AMUAY',
        'lat': 11.694,
        'lon': -70.218,
        'glosa': 'el taller de canoas de Carirubana',
        'locacion': 'taller_canoas',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Caseto': {
        'tipo': 'aldea',
        'sitio': 'Caseto',
        'nodo': 'AMUAY',
        'lat': 11.762,
        'lon': -70.017,
        'glosa': 'Caseto',
        'locacion': None,
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Caseto:conuco': {
        'tipo': 'locacion',
        'sitio': 'Caseto',
        'nodo': 'AMUAY',
        'lat': 11.762,
        'lon': -70.017,
        'glosa': 'el conuco de Caseto',
        'locacion': 'conuco',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Caseto:orilla': {
        'tipo': 'locacion',
        'sitio': 'Caseto',
        'nodo': 'AMUAY',
        'lat': 11.762,
        'lon': -70.017,
        'glosa': 'la orilla de Caseto',
        'locacion': 'orilla',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Caseto:taller': {
        'tipo': 'locacion',
        'sitio': 'Caseto',
        'nodo': 'AMUAY',
        'lat': 11.762,
        'lon': -70.017,
        'glosa': 'el taller de Caseto',
        'locacion': 'taller',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'El Cayude': {
        'tipo': 'aldea',
        'sitio': 'El Cayude',
        'nodo': 'GUARANAO',
        'lat': 11.701,
        'lon': -69.957,
        'glosa': 'El Cayude',
        'locacion': None,
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'El Cayude:jaguey': {
        'tipo': 'locacion',
        'sitio': 'El Cayude',
        'nodo': 'GUARANAO',
        'lat': 11.701,
        'lon': -69.957,
        'glosa': 'el jagüey de El Cayude',
        'locacion': 'jaguey',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'El Cayude:matorral': {
        'tipo': 'locacion',
        'sitio': 'El Cayude',
        'nodo': 'GUARANAO',
        'lat': 11.701,
        'lon': -69.957,
        'glosa': 'el matorral de El Cayude',
        'locacion': 'matorral',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'El Cayude:orilla': {
        'tipo': 'locacion',
        'sitio': 'El Cayude',
        'nodo': 'GUARANAO',
        'lat': 11.701,
        'lon': -69.957,
        'glosa': 'la orilla de El Cayude',
        'locacion': 'orilla',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'El Cayude:punta': {
        'tipo': 'locacion',
        'sitio': 'El Cayude',
        'nodo': 'GUARANAO',
        'lat': 11.649,
        'lon': -69.925,
        'glosa': 'la punta de El Cayude',
        'locacion': 'punta',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Moruy': {
        'tipo': 'aldea',
        'sitio': 'Moruy',
        'nodo': 'GUARANAO',
        'lat': 11.822,
        'lon': -69.983,
        'glosa': 'Moruy',
        'locacion': None,
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Moruy:taller': {
        'tipo': 'locacion',
        'sitio': 'Moruy',
        'nodo': 'GUARANAO',
        'lat': 11.822,
        'lon': -69.983,
        'glosa': 'el taller de Moruy',
        'locacion': 'taller',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Tacuato': {
        'tipo': 'aldea',
        'sitio': 'Tacuato',
        'nodo': 'GUARANAO',
        'lat': 11.708,
        'lon': -69.841,
        'glosa': 'Tacuato',
        'locacion': None,
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Tacuato:conuco': {
        'tipo': 'locacion',
        'sitio': 'Tacuato',
        'nodo': 'GUARANAO',
        'lat': 11.708,
        'lon': -69.841,
        'glosa': 'el conuco de Tacuato',
        'locacion': 'conuco',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Tacuato:jaguey': {
        'tipo': 'locacion',
        'sitio': 'Tacuato',
        'nodo': 'GUARANAO',
        'lat': 11.708,
        'lon': -69.841,
        'glosa': 'el jagüey de Tacuato',
        'locacion': 'jaguey',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Tacuato:matorral': {
        'tipo': 'locacion',
        'sitio': 'Tacuato',
        'nodo': 'GUARANAO',
        'lat': 11.708,
        'lon': -69.841,
        'glosa': 'el matorral de Tacuato',
        'locacion': 'matorral',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Tacuato:orilla': {
        'tipo': 'locacion',
        'sitio': 'Tacuato',
        'nodo': 'GUARANAO',
        'lat': 11.708,
        'lon': -69.841,
        'glosa': 'la orilla de Tacuato',
        'locacion': 'orilla',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Tacuato:salinar': {
        'tipo': 'locacion',
        'sitio': 'Tacuato',
        'nodo': 'GUARANAO',
        'lat': 11.708,
        'lon': -69.841,
        'glosa': 'el salinar de Tacuato',
        'locacion': 'salinar',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'Tacuato:taller': {
        'tipo': 'locacion',
        'sitio': 'Tacuato',
        'nodo': 'GUARANAO',
        'lat': 11.708,
        'lon': -69.841,
        'glosa': 'el taller de Tacuato',
        'locacion': 'taller',
        'extremos': None,
        'puntos': None,
        'compartido': None,
    },
    'ZA1': {
        'tipo': 'zona',
        'sitio': None,
        'nodo': 'AMUAY',
        'lat': 11.85729,
        'lon': -70.24486,
        'glosa': 'la costa oeste',
        'locacion': None,
        'extremos': None,
        'puntos': [[11.775, -70.241], [11.738, -70.234], [11.745, -70.212], [11.825, -70.252], [11.855, -70.301], [11.98, -70.257], [12.083, -70.217]],
        'compartido': None,
    },
    'ZG2': {
        'tipo': 'zona',
        'sitio': None,
        'nodo': 'GUARANAO',
        'lat': 11.6746,
        'lon': -69.9182,
        'glosa': 'la orilla del Golfete',
        'locacion': None,
        'extremos': None,
        'puntos': [[11.64, -70.069], [11.701, -69.957], [11.649, -69.925], [11.708, -69.841], [11.675, -69.799]],
        'compartido': None,
    },
    'camino:El Cayude': {
        'tipo': 'camino',
        'sitio': None,
        'nodo': 'GUARANAO',
        'lat': 11.701,
        'lon': -69.957,
        'glosa': 'el camino que sale de El Cayude',
        'locacion': None,
        'extremos': ['El Cayude'],
        'puntos': None,
        'compartido': None,
    },
    'camino:Moruy-Caseto': {
        'tipo': 'camino',
        'sitio': None,
        'nodo': 'COMPARTIDO',
        'lat': 11.792,
        'lon': -70.0,
        'glosa': 'el camino de Moruy a Caseto',
        'locacion': None,
        'extremos': ['Moruy', 'Caseto'],
        'puntos': [[11.822, -69.983], [11.762, -70.017]],
        'compartido': 'el elenco lo llama «la alianza»: «Caseto es el sitio de AMUAY más cercano a Moruy —unos ocho kilómetros por tierra, contra veinticinco— y ese camino corto ES la alianza: la esposa principal viene por él y el aporte de AMUAY al cerro baja por él» — 6-fusion/elenco_era2.yaml casas[los Guasicures de Caseto].razon_del_linaje',
    },
}

# ============================================================
# LA ESCENA — 63 agentes × 3 períodos × 6 momentos
# ============================================================

ESCENA = {
    'Amaka': {
        'viento': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
        'seca_larga': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
        'siembra': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
    },
    'Arika': {
        'viento': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana:taller', 'Carirubana', 'Carirubana'),
        'seca_larga': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana:taller', 'Carirubana', 'Carirubana'),
        'siembra': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana:taller', 'Carirubana', 'Carirubana'),
    },
    'Bajari': {
        'viento': ('Caseto', 'camino:Moruy-Caseto', 'camino:Moruy-Caseto', 'camino:Moruy-Caseto', 'Caseto', 'Caseto'),
        'seca_larga': ('Caseto', 'camino:Moruy-Caseto', 'camino:Moruy-Caseto', 'camino:Moruy-Caseto', 'Caseto', 'Caseto'),
        'siembra': ('Caseto', 'camino:Moruy-Caseto', 'camino:Moruy-Caseto', 'camino:Moruy-Caseto', 'Caseto', 'Caseto'),
    },
    'Dakawa': {
        'viento': ('Carirubana:orilla', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana'),
        'seca_larga': ('Carirubana:orilla', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana'),
        'siembra': ('Carirubana:orilla', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana'),
    },
    'Dipopo': {
        'viento': ('Caseto', 'Caseto', 'Caseto', 'Caseto:taller', 'Caseto', 'Caseto'),
        'seca_larga': ('Caseto', 'Caseto', 'Caseto', 'Caseto:taller', 'Caseto', 'Caseto'),
        'siembra': ('Caseto', 'Caseto', 'Caseto', 'Caseto:taller', 'Caseto', 'Caseto'),
    },
    'Ebokoa': {
        'viento': ('ZA1', 'ZA1', 'Carirubana', 'Carirubana:orilla', 'Carirubana:orilla', 'ZA1'),
        'seca_larga': ('ZA1', 'ZA1', 'Carirubana', 'Carirubana:orilla', 'Carirubana:orilla', 'Carirubana'),
        'siembra': ('ZA1', 'ZA1', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
    },
    'Isiro': {
        'viento': ('Carirubana:orilla', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana'),
        'seca_larga': ('Carirubana:orilla', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana'),
        'siembra': ('Carirubana:orilla', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana'),
    },
    'Karama': {
        'viento': ('Caseto:conuco', 'Caseto:conuco', 'Caseto', 'Caseto:conuco', 'Caseto', 'Caseto'),
        'seca_larga': ('Caseto:conuco', 'Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
        'siembra': ('Caseto:conuco', 'Caseto:conuco', 'Caseto', 'Caseto:conuco', 'Caseto', 'Caseto'),
    },
    'Kasebo': {
        'viento': ('ZA1', 'ZA1', 'Caseto', 'Caseto:orilla', 'Caseto:orilla', 'ZA1'),
        'seca_larga': ('ZA1', 'ZA1', 'Caseto', 'Caseto:orilla', 'Caseto:orilla', 'Caseto'),
        'siembra': ('ZA1', 'ZA1', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
    },
    'Kiwakoa': {
        'viento': ('Carirubana:orilla', 'Carirubana:orilla', 'Carirubana', 'Carirubana:orilla', 'Carirubana', 'Carirubana'),
        'seca_larga': ('Carirubana:orilla', 'Carirubana:orilla', 'Carirubana', 'Carirubana:orilla', 'Carirubana', 'Carirubana'),
        'siembra': ('Carirubana:orilla', 'Carirubana:orilla', 'Carirubana', 'Carirubana:orilla', 'Carirubana', 'Carirubana'),
    },
    'Mene': {
        'viento': ('Carirubana:orilla', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana'),
        'seca_larga': ('Carirubana:orilla', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana'),
        'siembra': ('Carirubana:orilla', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana:taller_canoas', 'Carirubana', 'Carirubana'),
    },
    'Paugis': {
        'viento': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
        'seca_larga': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
        'siembra': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
    },
    'Saruro': {
        'viento': ('Caseto', 'Caseto:taller', 'Caseto', 'Caseto:taller', 'Caseto', 'Caseto'),
        'seca_larga': ('Caseto', 'Caseto:taller', 'Caseto', 'Caseto:taller', 'Caseto', 'Caseto'),
        'siembra': ('Caseto', 'Caseto:taller', 'Caseto', 'Caseto:taller', 'Caseto', 'Caseto'),
    },
    'Siwa': {
        'viento': ('Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
        'seca_larga': ('Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
        'siembra': ('Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
    },
    'Tabri': {
        'viento': ('Caseto:conuco', 'Caseto:conuco', 'Caseto', 'Caseto:conuco', 'Caseto', 'Caseto'),
        'seca_larga': ('Caseto:conuco', 'Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
        'siembra': ('Caseto:conuco', 'Caseto:conuco', 'Caseto', 'Caseto:conuco', 'Caseto', 'Caseto'),
    },
    'Talata': {
        'viento': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
        'seca_larga': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
        'siembra': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
    },
    'Tauta': {
        'viento': ('Carirubana:orilla', 'Carirubana:orilla', 'Carirubana', 'Carirubana:orilla', 'Carirubana', 'Carirubana'),
        'seca_larga': ('Carirubana:orilla', 'Carirubana:orilla', 'Carirubana', 'Carirubana:orilla', 'Carirubana', 'Carirubana'),
        'siembra': ('Carirubana:orilla', 'Carirubana:orilla', 'Carirubana', 'Carirubana:orilla', 'Carirubana', 'Carirubana'),
    },
    'Tebekoa': {
        'viento': ('Caseto:conuco', 'Caseto:conuco', 'Caseto', 'Caseto:conuco', 'Caseto', 'Caseto'),
        'seca_larga': ('Caseto:conuco', 'Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
        'siembra': ('Caseto:conuco', 'Caseto:conuco', 'Caseto', 'Caseto:conuco', 'Caseto', 'Caseto'),
    },
    'Tigi': {
        'viento': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
        'seca_larga': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
        'siembra': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
    },
    'Tijua': {
        'viento': ('Caseto', 'Caseto', 'Caseto', 'Caseto:taller', 'Caseto', 'Caseto'),
        'seca_larga': ('Caseto', 'Caseto', 'Caseto', 'Caseto:taller', 'Caseto', 'Caseto'),
        'siembra': ('Caseto', 'Caseto', 'Caseto', 'Caseto:taller', 'Caseto', 'Caseto'),
    },
    'Turicha': {
        'viento': ('Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
        'seca_larga': ('Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
        'siembra': ('Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
    },
    'Waitiao': {
        'viento': ('ZA1', 'ZA1', 'Caseto', 'Caseto:orilla', 'Caseto:orilla', 'ZA1'),
        'seca_larga': ('ZA1', 'ZA1', 'Caseto', 'Caseto:orilla', 'Caseto:orilla', 'Caseto'),
        'siembra': ('ZA1', 'ZA1', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
    },
    'Waru': {
        'viento': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
        'seca_larga': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
        'siembra': ('Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana', 'Carirubana'),
    },
    'Wasima': {
        'viento': ('Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
        'seca_larga': ('Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
        'siembra': ('Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto', 'Caseto'),
    },
    'Akaure': {
        'viento': ('Tacuato', 'Tacuato', 'Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato'),
        'seca_larga': ('Tacuato', 'Tacuato', 'Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato'),
        'siembra': ('Tacuato', 'Tacuato', 'Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato'),
    },
    'Apoaure': {
        'viento': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'seca_larga': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'siembra': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
    },
    'Birokoa': {
        'viento': ('Tacuato:salinar', 'Tacuato:salinar', 'Tacuato', 'Tacuato:salinar', 'Tacuato', 'Tacuato'),
        'seca_larga': ('Tacuato:salinar', 'Tacuato:salinar', 'Tacuato', 'Tacuato:salinar', 'Tacuato', 'Tacuato'),
        'siembra': ('Tacuato', 'Tacuato:conuco', 'Tacuato', 'Tacuato:conuco', 'Tacuato', 'Tacuato'),
    },
    'Buriche': {
        'viento': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'seca_larga': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'siembra': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
    },
    'Cege': {
        'viento': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
        'seca_larga': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
        'siembra': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
    },
    'Chakamba': {
        'viento': ('Tacuato', 'Tacuato', 'Tacuato', 'Tacuato', 'Tacuato', 'Tacuato'),
        'seca_larga': ('Tacuato', 'Tacuato', 'Tacuato', 'Tacuato', 'Tacuato', 'Tacuato'),
        'siembra': ('Tacuato', 'Tacuato', 'Tacuato', 'Tacuato', 'Tacuato', 'Tacuato'),
    },
    'Chirwa': {
        'viento': ('Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato'),
        'seca_larga': ('Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato'),
        'siembra': ('Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato'),
    },
    'Chuchubi': {
        'viento': ('El Cayude', 'camino:El Cayude', 'camino:El Cayude', 'camino:El Cayude', 'El Cayude', 'El Cayude'),
        'seca_larga': ('El Cayude', 'camino:El Cayude', 'camino:El Cayude', 'camino:El Cayude', 'El Cayude', 'El Cayude'),
        'siembra': ('El Cayude', 'camino:El Cayude', 'camino:El Cayude', 'camino:El Cayude', 'El Cayude', 'El Cayude'),
    },
    'Dabuda': {
        'viento': ('Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato'),
        'seca_larga': ('Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato'),
        'siembra': ('Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato:taller', 'Tacuato', 'Tacuato'),
    },
    'Dara-bana': {
        'viento': ('El Cayude:punta', 'El Cayude:punta', 'El Cayude', 'El Cayude:punta', 'El Cayude', 'El Cayude'),
        'seca_larga': ('El Cayude:punta', 'El Cayude:punta', 'El Cayude', 'El Cayude:punta', 'El Cayude', 'El Cayude'),
        'siembra': ('El Cayude:punta', 'El Cayude:punta', 'El Cayude', 'El Cayude:punta', 'El Cayude', 'El Cayude'),
    },
    'Dato': {
        'viento': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'seca_larga': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'siembra': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
    },
    'Dichiba': {
        'viento': ('Tacuato', 'Tacuato:conuco', 'Tacuato', 'Tacuato:orilla', 'Tacuato', 'Tacuato'),
        'seca_larga': ('Tacuato', 'Tacuato:conuco', 'Tacuato', 'Tacuato:orilla', 'Tacuato', 'Tacuato'),
        'siembra': ('Tacuato', 'Tacuato:conuco', 'Tacuato', 'Tacuato:orilla', 'Tacuato', 'Tacuato'),
    },
    'Dunakoa': {
        'viento': ('El Cayude:jaguey', 'El Cayude:jaguey', 'El Cayude', 'El Cayude:jaguey', 'El Cayude', 'El Cayude'),
        'seca_larga': ('Capubana:fuente', 'Capubana:fuente', 'El Cayude', 'Capubana:fuente', 'El Cayude', 'El Cayude'),
        'siembra': ('El Cayude:jaguey', 'El Cayude:jaguey', 'El Cayude', 'El Cayude:jaguey', 'El Cayude', 'El Cayude'),
    },
    'Duraboa': {
        'viento': ('ZG2', 'ZG2', 'Tacuato', 'Tacuato:orilla', 'Tacuato:orilla', 'ZG2'),
        'seca_larga': ('ZG2', 'ZG2', 'Tacuato', 'Tacuato:orilla', 'Tacuato:orilla', 'Tacuato'),
        'siembra': ('ZG2', 'ZG2', 'Tacuato', 'Tacuato', 'Tacuato', 'Tacuato'),
    },
    'Harifuche': {
        'viento': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'seca_larga': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'siembra': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
    },
    'Hayo': {
        'viento': ('Capubana', 'Capubana', 'Capubana', 'Capubana', 'Capubana', 'Capubana'),
        'seca_larga': ('Capubana', 'Capubana', 'Capubana', 'Capubana', 'Capubana', 'Capubana'),
        'siembra': ('Capubana', 'Capubana', 'Capubana', 'Capubana', 'Capubana', 'Capubana'),
    },
    'Hiko': {
        'viento': ('Moruy', 'Moruy', 'Moruy', 'Moruy:taller', 'Moruy', 'Moruy'),
        'seca_larga': ('Moruy', 'Moruy', 'Moruy', 'Moruy:taller', 'Moruy', 'Moruy'),
        'siembra': ('Moruy', 'Moruy', 'Moruy', 'Moruy:taller', 'Moruy', 'Moruy'),
    },
    'Humohumo': {
        'viento': ('Moruy', 'camino:Moruy-Caseto', 'camino:Moruy-Caseto', 'camino:Moruy-Caseto', 'Moruy', 'Moruy'),
        'seca_larga': ('Moruy', 'camino:Moruy-Caseto', 'camino:Moruy-Caseto', 'camino:Moruy-Caseto', 'Moruy', 'Moruy'),
        'siembra': ('Moruy', 'camino:Moruy-Caseto', 'camino:Moruy-Caseto', 'camino:Moruy-Caseto', 'Moruy', 'Moruy'),
    },
    'Jachos': {
        'viento': ('ZG2', 'ZG2', 'El Cayude', 'El Cayude:orilla', 'El Cayude:orilla', 'ZG2'),
        'seca_larga': ('ZG2', 'ZG2', 'El Cayude', 'El Cayude:orilla', 'El Cayude:orilla', 'El Cayude'),
        'siembra': ('ZG2', 'ZG2', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
    },
    'Jaiata': {
        'viento': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
        'seca_larga': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
        'siembra': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
    },
    'Jakura': {
        'viento': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'seca_larga': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'siembra': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
    },
    'Karebe': {
        'viento': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'seca_larga': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'siembra': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
    },
    'Katiata': {
        'viento': ('El Cayude', 'El Cayude:matorral', 'El Cayude', 'El Cayude:matorral', 'El Cayude', 'El Cayude'),
        'seca_larga': ('El Cayude', 'El Cayude:matorral', 'El Cayude', 'El Cayude:matorral', 'El Cayude', 'El Cayude'),
        'siembra': ('El Cayude', 'El Cayude:matorral', 'El Cayude', 'El Cayude:matorral', 'El Cayude', 'El Cayude'),
    },
    'Kumarawa': {
        'viento': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'seca_larga': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'siembra': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
    },
    'Kunaro-bana': {
        'viento': ('ZG2', 'ZG2', 'Tacuato', 'Tacuato:orilla', 'Tacuato:orilla', 'ZG2'),
        'seca_larga': ('ZG2', 'ZG2', 'Tacuato', 'Tacuato:orilla', 'Tacuato:orilla', 'Tacuato'),
        'siembra': ('Tacuato:conuco', 'Tacuato:conuco', 'Tacuato', 'Tacuato:conuco', 'Tacuato', 'Tacuato'),
    },
    'Manaure': {
        'viento': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'seca_larga': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'siembra': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
    },
    'Naure': {
        'viento': ('Tacuato:conuco', 'Tacuato:conuco', 'Tacuato', 'Tacuato:conuco', 'Tacuato', 'Tacuato'),
        'seca_larga': ('Tacuato:conuco', 'Tacuato', 'Tacuato', 'Tacuato', 'Tacuato', 'Tacuato'),
        'siembra': ('Tacuato:conuco', 'Tacuato:conuco', 'Tacuato', 'Tacuato:conuco', 'Tacuato', 'Tacuato'),
    },
    'Patapati': {
        'viento': ('Tacuato:jaguey', 'Tacuato:jaguey', 'Tacuato', 'Tacuato:jaguey', 'Tacuato', 'Tacuato'),
        'seca_larga': ('Capubana:fuente', 'Capubana:fuente', 'Tacuato', 'Capubana:fuente', 'Tacuato', 'Tacuato'),
        'siembra': ('Tacuato:jaguey', 'Tacuato:jaguey', 'Tacuato', 'Tacuato:jaguey', 'Tacuato', 'Tacuato'),
    },
    'Ruata': {
        'viento': ('El Cayude:punta', 'El Cayude:punta', 'El Cayude', 'El Cayude:punta', 'El Cayude', 'El Cayude'),
        'seca_larga': ('El Cayude:punta', 'El Cayude:punta', 'El Cayude', 'El Cayude:punta', 'El Cayude', 'El Cayude'),
        'siembra': ('El Cayude:punta', 'El Cayude:punta', 'El Cayude', 'El Cayude:punta', 'El Cayude', 'El Cayude'),
    },
    'Sawaka': {
        'viento': ('Capubana', 'Capubana', 'Capubana', 'Capubana', 'Capubana', 'Capubana'),
        'seca_larga': ('Capubana', 'Capubana', 'Capubana', 'Capubana', 'Capubana', 'Capubana'),
        'siembra': ('Capubana', 'Capubana', 'Capubana', 'Capubana', 'Capubana', 'Capubana'),
    },
    'Simaure': {
        'viento': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'seca_larga': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
        'siembra': ('Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy', 'Moruy'),
    },
    'Ucibo': {
        'viento': ('ZG2', 'ZG2', 'Tacuato', 'Tacuato:orilla', 'Tacuato:orilla', 'ZG2'),
        'seca_larga': ('ZG2', 'ZG2', 'Tacuato', 'Tacuato:orilla', 'Tacuato:orilla', 'Tacuato'),
        'siembra': ('ZG2', 'ZG2', 'Tacuato', 'Tacuato', 'Tacuato', 'Tacuato'),
    },
    'Urari': {
        'viento': ('Tacuato', 'Tacuato:matorral', 'Tacuato', 'Tacuato:matorral', 'Tacuato', 'Tacuato'),
        'seca_larga': ('Tacuato', 'Tacuato:matorral', 'Tacuato', 'Tacuato:matorral', 'Tacuato', 'Tacuato'),
        'siembra': ('Tacuato', 'Tacuato:matorral', 'Tacuato', 'Tacuato:matorral', 'Tacuato', 'Tacuato'),
    },
    'Uria': {
        'viento': ('Tacuato:conuco', 'Tacuato:conuco', 'Tacuato', 'Tacuato:conuco', 'Tacuato', 'Tacuato'),
        'seca_larga': ('Tacuato:conuco', 'Tacuato', 'Tacuato', 'Tacuato', 'Tacuato', 'Tacuato'),
        'siembra': ('Tacuato:conuco', 'Tacuato:conuco', 'Tacuato', 'Tacuato:conuco', 'Tacuato', 'Tacuato'),
    },
    'Wache': {
        'viento': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
        'seca_larga': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
        'siembra': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
    },
    'Wairon': {
        'viento': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
        'seca_larga': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
        'siembra': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
    },
    'Wamipa': {
        'viento': ('Capubana:fuente', 'Capubana:fuente', 'Moruy', 'Capubana:fuente', 'Moruy', 'Moruy'),
        'seca_larga': ('Capubana:fuente', 'Capubana:fuente', 'Moruy', 'Capubana:fuente', 'Moruy', 'Moruy'),
        'siembra': ('Capubana:fuente', 'Capubana:fuente', 'Moruy', 'Capubana:fuente', 'Moruy', 'Moruy'),
    },
    'Wanepe': {
        'viento': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
        'seca_larga': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
        'siembra': ('El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
    },
    'Waranaro': {
        'viento': ('ZG2', 'ZG2', 'El Cayude', 'El Cayude:orilla', 'El Cayude:orilla', 'ZG2'),
        'seca_larga': ('ZG2', 'ZG2', 'El Cayude', 'El Cayude:orilla', 'El Cayude:orilla', 'El Cayude'),
        'siembra': ('ZG2', 'ZG2', 'El Cayude', 'El Cayude', 'El Cayude', 'El Cayude'),
    },
}

# La clase de oficio de cada agente, y con qué se sostiene el día de
# esa clase (canon con fuente / canon-simulación).
CLASE_DE = {
    'Akaure': 'fibra',
    'Amaka': 'huesos',
    'Apoaure': 'mando',
    'Arika': 'fibra',
    'Bajari': 'mensajeria',
    'Birokoa': 'sal',
    'Buriche': 'merejuy',
    'Cege': 'vision',
    'Chakamba': 'ninez',
    'Chirwa': 'alfareria',
    'Chuchubi': 'mensajeria',
    'Dabuda': 'alfareria',
    'Dakawa': 'canoa',
    'Dara-bana': 'vigia',
    'Dato': 'ninez',
    'Dichiba': 'arbitraje',
    'Dipopo': 'fibra',
    'Dunakoa': 'agua_dulce',
    'Duraboa': 'pesca',
    'Ebokoa': 'pesca',
    'Harifuche': 'casa',
    'Hayo': 'oraculo',
    'Hiko': 'fibra',
    'Humohumo': 'mensajeria',
    'Isiro': 'canoa',
    'Jachos': 'pesca',
    'Jaiata': 'ninez',
    'Jakura': 'memoria_de_casa',
    'Karama': 'conuco',
    'Karebe': 'mando',
    'Kasebo': 'pesca',
    'Katiata': 'monte',
    'Kiwakoa': 'marisqueo',
    'Kumarawa': 'casa',
    'Kunaro-bana': 'pesca',
    'Manaure': 'mando',
    'Mene': 'canoa',
    'Naure': 'conuco',
    'Patapati': 'agua_dulce',
    'Paugis': 'curacion',
    'Ruata': 'vigia',
    'Saruro': 'alfareria',
    'Sawaka': 'oraculo',
    'Simaure': 'memoria_de_casa',
    'Siwa': 'ninez',
    'Tabri': 'conuco',
    'Talata': 'ninez',
    'Tauta': 'marisqueo',
    'Tebekoa': 'conuco',
    'Tigi': 'ninez',
    'Tijua': 'fibra',
    'Turicha': 'cantor',
    'Ucibo': 'pesca',
    'Urari': 'monte',
    'Uria': 'conuco',
    'Wache': 'casa',
    'Wairon': 'casa',
    'Waitiao': 'pesca',
    'Wamipa': 'agua_dulce',
    'Wanepe': 'casa',
    'Waranaro': 'pesca',
    'Waru': 'huesos',
    'Wasima': 'memoria_de_casa',
}

ETIQUETAS = {
    'pesca': {
        'etiqueta': 'canon-simulacion',
        'fuente': ['ecologia-015', 'ecologia-026', 'ecologia-036', 'ecologia-078', 'clima_era2.yaml frases_del_cargador'],
    },
    'marisqueo': {
        'etiqueta': 'canon-simulacion',
        'fuente': ['ecologia-012', 'ecologia-044', 'ecologia-061', 'ecologia-081'],
    },
    'vigia': {
        'etiqueta': 'atestiguado (la atalaya); canon-simulacion (el día)',
        'fuente': ['ecologia-080', 'hueco-lex-002', 'sitios_era2.yaml Carirubana.mar_y_pesca'],
    },
    'sal': {
        'etiqueta': 'atestiguado (el ciclo); canon-simulacion (el día)',
        'fuente': ['ecologia-009', 'ecologia-010', 'hueco-lex-005', 'clima_era2.yaml abre_y_cierra.Tacuato'],
    },
    'conuco': {
        'etiqueta': 'atestiguado (el conuco); canon-simulacion (el día)',
        'fuente': ['ecologia-029', 'ecologia-030', 'ecologia-083', 'sitios_era2.yaml Caseto.tierra'],
    },
    'agua_dulce': {
        'etiqueta': 'atestiguado (la fuente del cerro); canon-simulacion (el oficio)',
        'fuente': ['ecologia-008', 'ecologia-028', 'arcaya-1920 p. 22', 'estructura_social_era2.yaml of-06', 'clima_era2.yaml abre_y_cierra.Capubana'],
    },
    'monte': {
        'etiqueta': 'canon-simulacion',
        'fuente': ['ecologia-018', 'ecologia-019', 'ecologia-077', 'ecologia-082', 'creencia-020'],
    },
    'alfareria': {
        'etiqueta': 'atestiguado (la cadena técnica); canon-simulacion (el día)',
        'fuente': ['ecologia-013', 'ecologia-014', 'ecologia-025', 'transmision-003'],
    },
    'fibra': {
        'etiqueta': 'canon-simulacion',
        'fuente': ['ecologia-023', 'ecologia-024', 'sitios_era2.yaml *.materiales'],
    },
    'canoa': {
        'etiqueta': 'atestiguado (la canoa); canon-simulacion (el día)',
        'fuente': ['ecologia-031', 'ecologia-032', 'hueco-lex-008', 'transmision-002'],
    },
    'casa': {
        'etiqueta': 'canon-simulacion',
        'fuente': ['transmision-007', 'ecologia-081', 'estructura_social_era2.yaml niveles'],
    },
    'mando': {
        'etiqueta': 'atestiguado (el diao que redistribuye); canon-simulacion (el día)',
        'fuente': ['creencia-001b', 'creencia-013', 'parentesco-037', 'estructura_social_era2.yaml of-01'],
    },
    'mensajeria': {
        'etiqueta': 'reconstruido (of-12); canon-simulacion (el recorrido)',
        'fuente': ['estructura_social_era2.yaml of-12', 'creencia-010', 'elenco_era2.yaml agentes[Humohumo|Chuchubi|Bajari].oficio'],
    },
    'oraculo': {
        'etiqueta': 'atestiguado (el encierro de 1-3 días); canon-simulacion (que viva en el cerro)',
        'fuente': ['creencia-002', 'creencia-004', 'arcaya-1920 pp. 97-100', 'estructura_social_era2.yaml of-02, of-04'],
    },
    'curacion': {
        'etiqueta': 'atestiguado (un boratio por pueblo principal)',
        'fuente': ['creencia-001', 'creencia-007', 'arcaya-1920 pp. 97-100', 'estructura_social_era2.yaml of-03'],
    },
    'huesos': {
        'etiqueta': 'atestiguado (el rito); reconstruido (quién lo hace)',
        'fuente': ['creencia-010b', 'creencia-010c', 'creencia-011', 'estructura_social_era2.yaml of-09'],
    },
    'cantor': {
        'etiqueta': 'atestiguado (el canto de noche)',
        'fuente': ['creencia-010', 'transmision-006', 'transmision-018', 'estructura_social_era2.yaml of-08'],
    },
    'arbitraje': {
        'etiqueta': 'hipotetico (of-13)',
        'fuente': ['estructura_social_era2.yaml of-13', 'oliver-1989-cap3 p. 275'],
    },
    'merejuy': {
        'etiqueta': 'hipotetico (of-07)',
        'fuente': ['estructura_social_era2.yaml of-07', 'clima_era2.yaml abre_y_cierra.Moruy'],
    },
    'memoria_de_casa': {
        'etiqueta': 'reconstruido (la matriarca)',
        'fuente': ['parentesco-005', 'parentesco-022', 'transmision-008'],
    },
    'vision': {
        'etiqueta': 'canon-simulacion',
        'fuente': ['transmision-014', 'creencia-005'],
    },
    'ninez': {
        'etiqueta': 'canon-simulacion',
        'fuente': ['transmision-025', 'transmision-027', 'transmision-029'],
    },
}

NODO_DE = {
    'Amaka': 'AMUAY',
    'Arika': 'AMUAY',
    'Bajari': 'AMUAY',
    'Dakawa': 'AMUAY',
    'Dipopo': 'AMUAY',
    'Ebokoa': 'AMUAY',
    'Isiro': 'AMUAY',
    'Karama': 'AMUAY',
    'Kasebo': 'AMUAY',
    'Kiwakoa': 'AMUAY',
    'Mene': 'AMUAY',
    'Paugis': 'AMUAY',
    'Saruro': 'AMUAY',
    'Siwa': 'AMUAY',
    'Tabri': 'AMUAY',
    'Talata': 'AMUAY',
    'Tauta': 'AMUAY',
    'Tebekoa': 'AMUAY',
    'Tigi': 'AMUAY',
    'Tijua': 'AMUAY',
    'Turicha': 'AMUAY',
    'Waitiao': 'AMUAY',
    'Waru': 'AMUAY',
    'Wasima': 'AMUAY',
    'Akaure': 'GUARANAO',
    'Apoaure': 'GUARANAO',
    'Birokoa': 'GUARANAO',
    'Buriche': 'GUARANAO',
    'Cege': 'GUARANAO',
    'Chakamba': 'GUARANAO',
    'Chirwa': 'GUARANAO',
    'Chuchubi': 'GUARANAO',
    'Dabuda': 'GUARANAO',
    'Dara-bana': 'GUARANAO',
    'Dato': 'GUARANAO',
    'Dichiba': 'GUARANAO',
    'Dunakoa': 'GUARANAO',
    'Duraboa': 'GUARANAO',
    'Harifuche': 'GUARANAO',
    'Hayo': 'GUARANAO',
    'Hiko': 'GUARANAO',
    'Humohumo': 'GUARANAO',
    'Jachos': 'GUARANAO',
    'Jaiata': 'GUARANAO',
    'Jakura': 'GUARANAO',
    'Karebe': 'GUARANAO',
    'Katiata': 'GUARANAO',
    'Kumarawa': 'GUARANAO',
    'Kunaro-bana': 'GUARANAO',
    'Manaure': 'GUARANAO',
    'Naure': 'GUARANAO',
    'Patapati': 'GUARANAO',
    'Ruata': 'GUARANAO',
    'Sawaka': 'GUARANAO',
    'Simaure': 'GUARANAO',
    'Ucibo': 'GUARANAO',
    'Urari': 'GUARANAO',
    'Uria': 'GUARANAO',
    'Wache': 'GUARANAO',
    'Wairon': 'GUARANAO',
    'Wamipa': 'GUARANAO',
    'Wanepe': 'GUARANAO',
    'Waranaro': 'GUARANAO',
}

SITIO_DE = {
    'Amaka': 'Carirubana',
    'Arika': 'Carirubana',
    'Bajari': 'Caseto',
    'Dakawa': 'Carirubana',
    'Dipopo': 'Caseto',
    'Ebokoa': 'Carirubana',
    'Isiro': 'Carirubana',
    'Karama': 'Caseto',
    'Kasebo': 'Caseto',
    'Kiwakoa': 'Carirubana',
    'Mene': 'Carirubana',
    'Paugis': 'Carirubana',
    'Saruro': 'Caseto',
    'Siwa': 'Caseto',
    'Tabri': 'Caseto',
    'Talata': 'Carirubana',
    'Tauta': 'Carirubana',
    'Tebekoa': 'Caseto',
    'Tigi': 'Carirubana',
    'Tijua': 'Caseto',
    'Turicha': 'Caseto',
    'Waitiao': 'Caseto',
    'Waru': 'Carirubana',
    'Wasima': 'Caseto',
    'Akaure': 'Tacuato',
    'Apoaure': 'Moruy',
    'Birokoa': 'Tacuato',
    'Buriche': 'Moruy',
    'Cege': 'El Cayude',
    'Chakamba': 'Tacuato',
    'Chirwa': 'Tacuato',
    'Chuchubi': 'El Cayude',
    'Dabuda': 'Tacuato',
    'Dara-bana': 'El Cayude',
    'Dato': 'Moruy',
    'Dichiba': 'Tacuato',
    'Dunakoa': 'El Cayude',
    'Duraboa': 'Tacuato',
    'Harifuche': 'Moruy',
    'Hayo': 'Moruy',
    'Hiko': 'Moruy',
    'Humohumo': 'Moruy',
    'Jachos': 'El Cayude',
    'Jaiata': 'El Cayude',
    'Jakura': 'Moruy',
    'Karebe': 'Moruy',
    'Katiata': 'El Cayude',
    'Kumarawa': 'Moruy',
    'Kunaro-bana': 'Tacuato',
    'Manaure': 'Moruy',
    'Naure': 'Tacuato',
    'Patapati': 'Tacuato',
    'Ruata': 'El Cayude',
    'Sawaka': 'Capubana',
    'Simaure': 'Moruy',
    'Ucibo': 'Tacuato',
    'Urari': 'Tacuato',
    'Uria': 'Tacuato',
    'Wache': 'El Cayude',
    'Wairon': 'El Cayude',
    'Wamipa': 'Moruy',
    'Wanepe': 'El Cayude',
    'Waranaro': 'El Cayude',
}

# Los lugares que la decisión 2 → B declara compartidos entre los nodos.
COMPARTIDOS = {
    'Capubana': 'estructura_social_era2.yaml decision_creativa_2026-09-14.capubana',
    'Capubana:fuente': 'clima_era2.yaml abre_y_cierra.Capubana (NO CIERRA NUNCA)',
    'camino:Moruy-Caseto': 'el elenco lo llama «la alianza»: «Caseto es el sitio de AMUAY más cercano a Moruy —unos ocho kilómetros por tierra, contra veinticinco— y ese camino corto ES la alianza: la esposa principal viene por él y el aporte de AMUAY al cerro baja por él» — 6-fusion/elenco_era2.yaml casas[los Guasicures de Caseto].razon_del_linaje',
}

# El camino de la alianza: quién lo cruza y cuándo (derivado, no escrito).
TRAVESIA = {
    'filas': [{
        'lugar': 'camino:Moruy-Caseto',
        'extremos': ['Moruy', 'Caseto'],
        'agentes': ['Karebe'],
        'encajan_en_la_geografia_pero_no_en_la_frase': ['Wamipa'],
        'momentos': ['mañana', 'mediodia', 'tarde'],
        'cuando': 'vispera_de_capubana',
        'glosa_del_cuando': 'la víspera del día de Capubana (día N donde (N+1) % capubana_cada == 0)',
        'etiqueta': 'canon-simulacion (la cadencia); canon (el camino y su papel)',
        'fuente': '6-fusion/elenco_era2.yaml casas[los Guasicures de Caseto].razon_del_linaje',
    }],
    'derivacion': 'cruzado por matrimonio cuyo {sitio_origen, vive_en} son los dos extremos del camino declarado',
}

# El cerro y el día de la convergencia (cadencia: --capubana-cada N).
CAPUBANA = {
    'lugar': 'Capubana',
    'cadencia': 'parámetro del run: --capubana-cada N, sellado en simulation_runs.config (decisión 7 → A; N = 3 en la primera cadena)',
    'que_pasa_ese_dia': 'los 63 están en el Capubana los seis momentos',
    'etiqueta': 'atestiguado (que hay convergencia y que suben y bajan delegaciones); canon-simulacion (la cadencia)',
    'fuente': ['6-fusion/estructura_social_era2.yaml §ciclo_ritual_merejuy (CM fases 4 y 5)', 'creencia-013', 'Ampíes f. 14', '6-fusion/clima_era2.yaml abre_y_cierra.Capubana'],
}


AGENTES = tuple(sorted(ESCENA))


def lugar_de(agente, periodo, momento):
    """El lugar de un agente en un momento de un período, o None."""
    fila = ESCENA.get(agente)
    if not fila or periodo not in fila or momento not in MOMENTOS:
        return None
    return fila[periodo][MOMENTOS.index(momento)]


def glosa_de(lugar):
    """Cómo se dice ese lugar en prosa: «la orilla de Tacuato»."""
    return (LUGARES.get(lugar) or {}).get('glosa') or lugar
