"""
CURIANA — Candidatos de reconstrucción NO verificados (aislados del léxico activo)
==================================================================================
Estas 441 entradas se generaron con el pipeline comparativo
(reconstruir_caquetio_gaps.py -> aplicar_reconstruccion.py) transduciendo
fonológicamente palabras wayunaiki/lokono/taíno que compartían glosa con un
hueco caquetío, SIN verificar cognación real contra COGNADOS.

minar_pares_validacion.py mostró ~80% de error contra caquetío atestiguado:
en la mayoría de los casos la "reconstrucción" es la palabra hermana casi
intacta, porque glosa compartida != cognado (ej. "sal" caquetío=biro,
wayunaiki=ichii: lexemas distintos, no una diferencia fonológica).

Se AISLARON de VOCABULARIO_BASE (curiana_lexicon.py) el 2026-06-28 porque,
estando físicamente en el léxico activo, producían falsos positivos en
score_linguistico (p.ej. el "la"/"para" español matcheaba contra entradas
hipotéticas y se contaba como vocabulario indígena).

NO se importan en la simulación ni se siembran en Supabase. Quedan acá como
material de trabajo para una futura validación sistemática (minar más fuentes
publicadas y conservar solo las que pasen contra cognados reales).
"""

CANDIDATOS_NO_VERIFICADOS: dict[str, dict] = {
    "pian": {"es": "dos (numeral)", "fuente": "hipotético-no-verificado", "notas": "Lok. bian → pian; Way. piama → piama; confianza media", "categoria": "gramatica"},
    "cabyn": {"es": "tres (numeral)", "fuente": "hipotético-no-verificado", "notas": "Lok. kabyn → cabyn; Way. apünüin → abunuin; confianza media", "categoria": "gramatica"},
    "pithi": {"es": "cuatro (numeral)", "fuente": "hipotético-no-verificado", "notas": "Lok. bithi → pithi; Way. pienchi → pienchi; confianza media", "categoria": "gramatica"},
    "peyiche": {"es": "bejique, chamán taíno, mediador ritual", "fuente": "hipotético-no-verificado", "notas": "Taíno bejique → peyiche; confianza media", "categoria": "cosmos"},
    "paraca": {"es": "mar, agua extensa (forma lokono)", "fuente": "hipotético-no-verificado", "notas": "Lok. baraha → paraca; confianza media", "categoria": "geografia"},
    "coïa": {"es": "tierra, suelo (forma lokono)", "fuente": "hipotético-no-verificado", "notas": "Lok. koïa → coïa; confianza media", "categoria": "geografia"},
    "puru": {"es": "cielo, firmamento", "fuente": "hipotético-no-verificado", "notas": "Lok. buru → puru; confianza media", "categoria": "cosmos"},
    "cassacu": {"es": "firmamento, bóveda celeste", "fuente": "hipotético-no-verificado", "notas": "Lok. kassaku → cassacu; confianza media", "categoria": "cosmos"},
    "colocon": {"es": "en el fuego, en la luz (postposición)", "fuente": "hipotético-no-verificado", "notas": "Lok. kolokon → colocon; confianza media", "categoria": "cosmos"},
    "tacuty": {"es": "pies, patas", "fuente": "hipotético-no-verificado", "notas": "Lok. dakuty → tacuty; confianza media", "categoria": "cuerpo"},
    "anucu": {"es": "boca", "fuente": "hipotético-no-verificado", "notas": "Lok. daliroko → taliroco; Way. aanükü → anucu; confianza media", "categoria": "cuerpo"},
    "tari": {"es": "dientes", "fuente": "hipotético-no-verificado", "notas": "Lok. dari → tari; confianza media", "categoria": "cuerpo"},
    "ucu": {"es": "corazón, centro vital", "fuente": "hipotético-no-verificado", "notas": "Lok. ukku → ucu; confianza media", "categoria": "cuerpo"},
    "ucurahu2": {"es": "pus (secreción del cuerpo enfermo)", "fuente": "hipotético-no-verificado", "notas": "Lok. ukkurahu2 → ucurahu2; confianza media", "categoria": "cuerpo"},
    "eichi": {"es": "nariz", "fuente": "hipotético-no-verificado", "notas": "Lok. wasiri → wasiri; Way. e'ichi → eichi; Taíno aduri → aduri; confianza media", "categoria": "cuerpo"},
    "poro": {"es": "aldea, pueblo, asentamiento", "fuente": "hipotético-no-verificado", "notas": "Lok. boro → poro; confianza media", "categoria": "geografia"},
    "capojan": {"es": "conuco, milpa, terreno de cultivo", "fuente": "hipotético-no-verificado", "notas": "Lok. kabojan → capojan; confianza media", "categoria": "geografia"},
    "cairi": {"es": "isla, territorio insular", "fuente": "hipotético-no-verificado", "notas": "Lok. kairi → cairi; confianza media", "categoria": "geografia"},
    "oniapo": {"es": "agua, cuerpo de agua", "fuente": "hipotético-no-verificado", "notas": "Lok. oniabo → oniapo; confianza media", "categoria": "geografia"},
    "salapan": {"es": "sabana, llanura (terreno plano y liso)", "fuente": "hipotético-no-verificado", "notas": "Lok. sallaban → salapan; confianza media", "categoria": "geografia"},
    "sipa": {"es": "piedra, roca", "fuente": "hipotético-no-verificado", "notas": "Lok. siba → sipa; confianza media", "categoria": "geografia"},
    "apa": {"es": "uno, un (numeral y artículo indefinido)", "fuente": "hipotético-no-verificado", "notas": "Lok. aba → apa; confianza media", "categoria": "gramatica"},
    "alican": {"es": "quién (interrogativo)", "fuente": "hipotético-no-verificado", "notas": "Lok. alikan → alican; confianza media", "categoria": "gramatica"},
    "anacan": {"es": "centro, punto medio (concepto espacial)", "fuente": "hipotético-no-verificado", "notas": "Lok. annakan → anacan; confianza media", "categoria": "gramatica"},
    "pe": {"es": "sufijo plural general (-be)", "fuente": "hipotético-no-verificado", "notas": "Lok. be → pe; confianza media", "categoria": "gramatica"},
    "pi": {"es": "tú (pronombre libre 2sg)", "fuente": "hipotético-no-verificado", "notas": "Lok. bi → pi; confianza media", "categoria": "gramatica"},
    "piinasufix": {"es": "sufijo de pasado próximo (-biina: ayer)", "fuente": "hipotético-no-verificado", "notas": "Lok. biinasufix → piinasufix; confianza media", "categoria": "gramatica"},
    "pisufix": {"es": "sufijo de pasado reciente (-bi: hoy)", "fuente": "hipotético-no-verificado", "notas": "Lok. bisufix → pisufix; confianza media", "categoria": "gramatica"},
    "pute": {"es": "ahora (marcador de presente inmediato)", "fuente": "hipotético-no-verificado", "notas": "Lok. bute → pute; confianza media", "categoria": "gramatica"},
    "te": {"es": "yo (pronombre libre 1sg)", "fuente": "hipotético-no-verificado", "notas": "Lok. de → te; confianza media", "categoria": "gramatica"},
    "toma": {"es": "porque, a causa de (postposición causal)", "fuente": "hipotético-no-verificado", "notas": "Lok. doma → toma; confianza media", "categoria": "gramatica"},
    "ipin": {"es": "ya, de ya (aspecto completivo)", "fuente": "hipotético-no-verificado", "notas": "Lok. hibin → ipin; confianza media", "categoria": "gramatica"},
    "cen": {"es": "y (conjunción copulativa)", "fuente": "hipotético-no-verificado", "notas": "Lok. ken → cen; confianza media", "categoria": "gramatica"},
    "cijadoma": {"es": "por eso, por tanto, por esa razón", "fuente": "hipotético-no-verificado", "notas": "Lok. kijadoma → cijadoma; confianza media", "categoria": "gramatica"},
    "lico": {"es": "nuestro (posesivo 1pl, poseído)", "fuente": "hipotético-no-verificado", "notas": "Lok. liko → lico; confianza media", "categoria": "gramatica"},
    "pocithi": {"es": "hermano mayor (visto por el menor)", "fuente": "hipotético-no-verificado", "notas": "Lok. bokithi → pocithi; confianza media", "categoria": "parentesco"},
    "tali": {"es": "padre (mi padre, forma poseída)", "fuente": "hipotético-no-verificado", "notas": "Lok. dalli → tali; confianza media", "categoria": "parentesco"},
    "ipili": {"es": "niño, infante (sin distinción de género)", "fuente": "hipotético-no-verificado", "notas": "Lok. ibili → ipili; confianza media", "categoria": "parentesco"},
    "cakythi": {"es": "hombre adulto arahuacano", "fuente": "hipotético-no-verificado", "notas": "Lok. kakythi → cakythi; confianza media", "categoria": "parentesco"},
    "cakythinon": {"es": "pueblo, gente arahuacana", "fuente": "hipotético-no-verificado", "notas": "Lok. kakythinon → cakythinon; confianza media", "categoria": "parentesco"},
    "cupacanan": {"es": "antepasados, ancestros", "fuente": "hipotético-no-verificado", "notas": "Lok. kubakanan → cupacanan; confianza media", "categoria": "parentesco"},
    "lucunu": {"es": "el pueblo lokono (autónimo colectivo)", "fuente": "hipotético-no-verificado", "notas": "Lok. lukkunu → lucunu; confianza media", "categoria": "parentesco"},
    "ocithi": {"es": "hermano menor (visto por el mayor)", "fuente": "hipotético-no-verificado", "notas": "Lok. okithi → ocithi; confianza media", "categoria": "parentesco"},
    "ocitho": {"es": "hermana menor (vista por la mayor)", "fuente": "hipotético-no-verificado", "notas": "Lok. okitho → ocitho; confianza media", "categoria": "parentesco"},
    "ucurahu": {"es": "familia, tribu, grupo de origen común", "fuente": "hipotético-no-verificado", "notas": "Lok. ukkurahu → ucurahu; confianza media", "categoria": "parentesco"},
    "awothici": {"es": "encontrar, hallar", "fuente": "hipotético-no-verificado", "notas": "Lok. awothiki → awothici; confianza media", "categoria": "verbos"},
    "pocon": {"es": "cocinar, hervir", "fuente": "hipotético-no-verificado", "notas": "Lok. bokon → pocon; confianza media", "categoria": "verbos"},
    "poratyn": {"es": "ayudar, salvar", "fuente": "hipotético-no-verificado", "notas": "Lok. boratyn → poratyn; confianza media", "categoria": "verbos"},
    "tian": {"es": "hablar, decir", "fuente": "hipotético-no-verificado", "notas": "Lok. dian → tian; confianza media", "categoria": "verbos"},
    "ayata": {"es": "golpear, pegar", "fuente": "hipotético-no-verificado", "notas": "Lok. fatadyn → fatadyn; Way. ajataa → ayata; confianza media", "categoria": "verbos"},
    "cassan": {"es": "estar embarazada", "fuente": "hipotético-no-verificado", "notas": "Lok. kassan → cassan; confianza media", "categoria": "verbos"},
    "sicin": {"es": "dar, poner", "fuente": "hipotético-no-verificado", "notas": "Lok. sikin → sicin; confianza media", "categoria": "verbos"},
    "socon": {"es": "cortar (con machete o hacha)", "fuente": "hipotético-no-verificado", "notas": "Lok. sokon → socon; confianza media", "categoria": "verbos"},
    "aayula": {"es": "calor, temperatura", "fuente": "hipotético-no-verificado", "notas": "Way. aa'ayula → aayula; confianza media", "categoria": "cosmos"},
    "amusain": {"es": "humo", "fuente": "hipotético-no-verificado", "notas": "Way. amüsain → amusain; confianza media", "categoria": "cosmos"},
    "aturula": {"es": "trueno, paso", "fuente": "hipotético-no-verificado", "notas": "Way. atürüla → aturula; confianza media", "categoria": "cosmos"},
    "auarala": {"es": "luz", "fuente": "hipotético-no-verificado", "notas": "Way. awarala → auarala; confianza media", "categoria": "cosmos"},
    "aya": {"es": "relámpago", "fuente": "hipotético-no-verificado", "notas": "Way. ayaa → aya; confianza media", "categoria": "cosmos"},
    "emiouchi": {"es": "sombra", "fuente": "hipotético-no-verificado", "notas": "Way. eemioushi → emiouchi; confianza media", "categoria": "cosmos"},
    "olotsu": {"es": "estrella", "fuente": "hipotético-no-verificado", "notas": "Way. jolotsü → olotsu; confianza media", "categoria": "cosmos"},
    "caspoluin": {"es": "arco iris", "fuente": "hipotético-no-verificado", "notas": "Way. kaspolüin → caspoluin; confianza media", "categoria": "cosmos"},
    "catcousu": {"es": "arma de fuego", "fuente": "hipotético-no-verificado", "notas": "Way. katkousü → catcousu; confianza media", "categoria": "cosmos"},
    "palii": {"es": "ceniza", "fuente": "hipotético-no-verificado", "notas": "Way. pali'i → palii; confianza media", "categoria": "cosmos"},
    "piyuuchi": {"es": "oscuridad", "fuente": "hipotético-no-verificado", "notas": "Way. piyuushi → piyuuchi; confianza media", "categoria": "cosmos"},
    "balatchi": {"es": "calor atmosférico", "fuente": "hipotético-no-verificado", "notas": "Way. walatshi → balatchi; confianza media", "categoria": "cosmos"},
    "bauai": {"es": "viento (de tempestad)", "fuente": "hipotético-no-verificado", "notas": "Way. wawai → bauai; confianza media", "categoria": "cosmos"},
    "auala": {"es": "cabello", "fuente": "hipotético-no-verificado", "notas": "Way. a'wala → auala; confianza media", "categoria": "cuerpo"},
    "auiira": {"es": "lágrima", "fuente": "hipotético-no-verificado", "notas": "Way. a'wiira → auiira; confianza media", "categoria": "cuerpo"},
    "aluuain": {"es": "tobillo", "fuente": "hipotético-no-verificado", "notas": "Way. aaluwain → aluuain; confianza media", "categoria": "cuerpo"},
    "achaa": {"es": "excremento", "fuente": "hipotético-no-verificado", "notas": "Way. acha'a → achaa; confianza media", "categoria": "cuerpo"},
    "achee": {"es": "oreja, oído", "fuente": "hipotético-no-verificado", "notas": "Way. ache'e → achee; confianza media", "categoria": "cuerpo"},
    "achebu": {"es": "pintura para la cara", "fuente": "hipotético-no-verificado", "notas": "Way. achepü → achebu; confianza media", "categoria": "cuerpo"},
    "ayapcii": {"es": "muñeca", "fuente": "hipotético-no-verificado", "notas": "Way. ajapkii → ayapcii; confianza media", "categoria": "cuerpo"},
    "aluuuain": {"es": "pecho", "fuente": "hipotético-no-verificado", "notas": "Way. aluuwain → aluuuain; confianza media", "categoria": "cuerpo"},
    "amulira": {"es": "vello", "fuente": "hipotético-no-verificado", "notas": "Way. amülira → amulira; confianza media", "categoria": "cuerpo"},
    "abachera": {"es": "dedo (del pie)", "fuente": "hipotético-no-verificado", "notas": "Way. apachera → abachera; confianza media", "categoria": "cuerpo"},
    "abatou": {"es": "uña, garra, pezuña", "fuente": "hipotético-no-verificado", "notas": "Way. apato'u → abatou; confianza media", "categoria": "cuerpo"},
    "abuu": {"es": "muslo", "fuente": "hipotético-no-verificado", "notas": "Way. apü'ü → abuu; confianza media", "categoria": "cuerpo"},
    "asabu": {"es": "espalda, columna", "fuente": "hipotético-no-verificado", "notas": "Way. asapü → asabu; confianza media", "categoria": "cuerpo"},
    "aseeruu": {"es": "mitad, cintura", "fuente": "hipotético-no-verificado", "notas": "Way. ase'eru'u → aseeruu; confianza media", "categoria": "cuerpo"},
    "asibala": {"es": "cicatriz", "fuente": "hipotético-no-verificado", "notas": "Way. asipala → asibala; confianza media", "categoria": "cuerpo"},
    "atuna": {"es": "brazo, ala", "fuente": "hipotético-no-verificado", "notas": "Way. atüna → atuna; confianza media", "categoria": "cuerpo"},
    "aua": {"es": "saliva", "fuente": "hipotético-no-verificado", "notas": "Way. awaa → aua; confianza media", "categoria": "cuerpo"},
    "auala-2": {"es": "hermano, -na", "fuente": "hipotético-no-verificado", "notas": "Way. awala → auala; confianza media", "categoria": "cuerpo"},
    "aualainse": {"es": "mandíbula, quijada", "fuente": "hipotético-no-verificado", "notas": "Way. awalainse → aualainse; confianza media", "categoria": "cuerpo"},
    "aualabaa": {"es": "mejilla", "fuente": "hipotético-no-verificado", "notas": "Way. awalapa'a → aualabaa; confianza media", "categoria": "cuerpo"},
    "aye": {"es": "lengua", "fuente": "hipotético-no-verificado", "notas": "Way. ayee → aye; confianza media", "categoria": "cuerpo"},
    "ayulain": {"es": "intestino, tripa", "fuente": "hipotético-no-verificado", "notas": "Way. ayülain → ayulain; confianza media", "categoria": "cuerpo"},
    "eiima": {"es": "barba", "fuente": "hipotético-no-verificado", "notas": "Way. e'iima → eiima; confianza media", "categoria": "cuerpo"},
    "eiruu": {"es": "punta", "fuente": "hipotético-no-verificado", "notas": "Way. e'iru'u → eiruu; confianza media", "categoria": "cuerpo"},
    "eiyeise": {"es": "barbilla", "fuente": "hipotético-no-verificado", "notas": "Way. e'iyeise → eiyeise; confianza media", "categoria": "cuerpo"},
    "eyuu": {"es": "olor", "fuente": "hipotético-no-verificado", "notas": "Way. eejuu → eyuu; confianza media", "categoria": "cuerpo"},
    "eibuse": {"es": "hueso", "fuente": "hipotético-no-verificado", "notas": "Way. eipüse → eibuse; confianza media", "categoria": "cuerpo"},
    "ecia": {"es": "mano derecha", "fuente": "hipotético-no-verificado", "notas": "Way. ekia → ecia; confianza media", "categoria": "cuerpo"},
    "eciicholoin": {"es": "cerebro, seso", "fuente": "hipotético-no-verificado", "notas": "Way. ekiisholoin → eciicholoin; confianza media", "categoria": "cuerpo"},
    "ebee": {"es": "mano izquierda", "fuente": "hipotético-no-verificado", "notas": "Way. epe'e → ebee; confianza media", "categoria": "cuerpo"},
    "euein": {"es": "lunar", "fuente": "hipotético-no-verificado", "notas": "Way. ewein → euein; confianza media", "categoria": "cuerpo"},
    "calabuchou": {"es": "ave cucarachero", "fuente": "hipotético-no-verificado", "notas": "Way. ka'lapücho'u → calabuchou; confianza media", "categoria": "cuerpo"},
    "carai": {"es": "alcaraván (dara)", "fuente": "hipotético-no-verificado", "notas": "Way. kaarai → carai; confianza media", "categoria": "cuerpo"},
    "calecale": {"es": "perico (cara sucia)", "fuente": "hipotético-no-verificado", "notas": "Way. kalekale → calecale; confianza media", "categoria": "cuerpo"},
    "casiba": {"es": "ciempiés", "fuente": "hipotético-no-verificado", "notas": "Way. kasipa → casiba; confianza media", "categoria": "cuerpo"},
    "mayayulu": {"es": "señorita, joven (mujer)", "fuente": "hipotético-no-verificado", "notas": "Way. majayülü → mayayulu; confianza media", "categoria": "cuerpo"},
    "mabui": {"es": "piojo", "fuente": "hipotético-no-verificado", "notas": "Way. mapüi → mabui; confianza media", "categoria": "cuerpo"},
    "oulucu": {"es": "miembro", "fuente": "hipotético-no-verificado", "notas": "Way. o'uluku → oulucu; confianza media", "categoria": "cuerpo"},
    "oubuna": {"es": "cara, rostro", "fuente": "hipotético-no-verificado", "notas": "Way. o'upünaa → oubuna; confianza media", "categoria": "cuerpo"},
    "outala": {"es": "cáscara", "fuente": "hipotético-no-verificado", "notas": "Way. o'utala → outala; confianza media", "categoria": "cuerpo"},
    "omocoin": {"es": "espuma", "fuente": "hipotético-no-verificado", "notas": "Way. omokoin → omocoin; confianza media", "categoria": "cuerpo"},
    "balachi": {"es": "pelo", "fuente": "hipotético-no-verificado", "notas": "Way. walashi → balachi; confianza media", "categoria": "cuerpo"},
    "yoi": {"es": "llaga, infección", "fuente": "hipotético-no-verificado", "notas": "Way. yooi → yoi; confianza media", "categoria": "cuerpo"},
    "ayuna": {"es": "cubierta, techo", "fuente": "hipotético-no-verificado", "notas": "Way. aajuna → ayuna; confianza media", "categoria": "geografia"},
    "anoi": {"es": "terreno despejado", "fuente": "hipotético-no-verificado", "notas": "Way. anooi → anoi; confianza media", "categoria": "geografia"},
    "abule": {"es": "lugar, sitio, puesto", "fuente": "hipotético-no-verificado", "notas": "Way. apülee → abule; confianza media", "categoria": "geografia"},
    "abuna": {"es": "camino, sendero", "fuente": "hipotético-no-verificado", "notas": "Way. apüna → abuna; confianza media", "categoria": "geografia"},
    "asebu": {"es": "pared", "fuente": "hipotético-no-verificado", "notas": "Way. asepü → asebu; confianza media", "categoria": "geografia"},
    "atuu": {"es": "superficie interior", "fuente": "hipotético-no-verificado", "notas": "Way. atu'u → atuu; confianza media", "categoria": "geografia"},
    "iba": {"es": "piedra", "fuente": "hipotético-no-verificado", "notas": "Way. ipa → iba; confianza media", "categoria": "geografia"},
    "culala": {"es": "corral", "fuente": "hipotético-no-verificado", "notas": "Way. kulaala → culala; confianza media", "categoria": "geografia"},
    "la": {"es": "jagüey", "fuente": "hipotético-no-verificado", "notas": "Way. laa → la; confianza media", "categoria": "geografia"},
    "luuobu": {"es": "arroyo", "fuente": "hipotético-no-verificado", "notas": "Way. luwopu → luuobu; confianza media", "categoria": "geografia"},
    "maraya": {"es": "vidrio", "fuente": "hipotético-no-verificado", "notas": "Way. maraaja → maraya; confianza media", "categoria": "geografia"},
    "miirocu": {"es": "sitio donde hay", "fuente": "hipotético-no-verificado", "notas": "Way. miiroku → miirocu; confianza media", "categoria": "geografia"},
    "moyuui": {"es": "monte (vegetación)", "fuente": "hipotético-no-verificado", "notas": "Way. mojuui → moyuui; confianza media", "categoria": "geografia"},
    "namuna": {"es": "loma, cerro", "fuente": "hipotético-no-verificado", "notas": "Way. namüna → namuna; confianza media", "categoria": "geografia"},
    "puattou": {"es": "puerta", "fuente": "hipotético-no-verificado", "notas": "Way. puatto'u → puattou; confianza media", "categoria": "geografia"},
    "boolu": {"es": "mochila para el cinturón bosque, monte", "fuente": "hipotético-no-verificado", "notas": "Way. wo'olu → boolu; confianza media", "categoria": "geografia"},
    "buin": {"es": "agua", "fuente": "hipotético-no-verificado", "notas": "Way. wüin → buin; confianza media", "categoria": "geografia"},
    "aaca": {"es": "entre", "fuente": "hipotético-no-verificado", "notas": "Way. a'aka → aaca; confianza media", "categoria": "gramatica"},
    "aatou": {"es": "al lado de", "fuente": "hipotético-no-verificado", "notas": "Way. a'ato'u → aatou; confianza media", "categoria": "gramatica"},
    "autpaa": {"es": "al lado de, junto a", "fuente": "hipotético-no-verificado", "notas": "Way. a'ütpa'a → autpaa; confianza media", "categoria": "gramatica"},
    "au": {"es": "en", "fuente": "hipotético-no-verificado", "notas": "Way. aa'u → au; confianza media", "categoria": "gramatica"},
    "achin": {"es": "según", "fuente": "hipotético-no-verificado", "notas": "Way. aashin → achin; confianza media", "categoria": "gramatica"},
    "achiciye": {"es": "después de", "fuente": "hipotético-no-verificado", "notas": "Way. achikijee → achiciye; confianza media", "categoria": "gramatica"},
    "achiciruu": {"es": "después de la salida aikkaa", "fuente": "hipotético-no-verificado", "notas": "Way. achikiru'u → achiciruu; confianza media", "categoria": "gramatica"},
    "airuu": {"es": "en la horqueta de, entre", "fuente": "hipotético-no-verificado", "notas": "Way. airu'u → airuu; confianza media", "categoria": "gramatica"},
    "acaisaa": {"es": "pero, sin embargo", "fuente": "hipotético-no-verificado", "notas": "Way. akaisa'a → acaisaa; confianza media", "categoria": "gramatica"},
    "aleeruu": {"es": "en el vientre de", "fuente": "hipotético-no-verificado", "notas": "Way. ale'eru'u → aleeruu; confianza media", "categoria": "gramatica"},
    "aluu": {"es": "dentro de, en", "fuente": "hipotético-no-verificado", "notas": "Way. alu'u → aluu; confianza media", "categoria": "gramatica"},
    "aluuyasaa": {"es": "pero", "fuente": "hipotético-no-verificado", "notas": "Way. alu'ujasa'a → aluuyasaa; confianza media", "categoria": "gramatica"},
    "amaichici": {"es": "antes", "fuente": "hipotético-no-verificado", "notas": "Way. ama'ichiki → amaichici; confianza media", "categoria": "gramatica"},
    "amainruu": {"es": "mientras", "fuente": "hipotético-no-verificado", "notas": "Way. ama'inru'u → amainruu; confianza media", "categoria": "gramatica"},
    "amuin": {"es": "a, para", "fuente": "hipotético-no-verificado", "notas": "Way. amüin → amuin; confianza media", "categoria": "gramatica"},
    "anainje": {"es": "de, por", "fuente": "hipotético-no-verificado", "notas": "Way. anainjee → anainje; confianza media", "categoria": "gramatica"},
    "anainmuin": {"es": "a, hacia", "fuente": "hipotético-no-verificado", "notas": "Way. anainmüin → anainmuin; confianza media", "categoria": "gramatica"},
    "abulabuna": {"es": "antes de", "fuente": "hipotético-no-verificado", "notas": "Way. apülapünaa → abulabuna; confianza media", "categoria": "gramatica"},
    "abulerua": {"es": "delante de", "fuente": "hipotético-no-verificado", "notas": "Way. apüleerua → abulerua; confianza media", "categoria": "gramatica"},
    "atuma": {"es": "por", "fuente": "hipotético-no-verificado", "notas": "Way. atüma → atuma; confianza media", "categoria": "gramatica"},
    "eibaye": {"es": "en respuesta a", "fuente": "hipotético-no-verificado", "notas": "Way. e'ipajee → eibaye; confianza media", "categoria": "gramatica"},
    "einaluu": {"es": "en el fondo de, en el ekiisa", "fuente": "hipotético-no-verificado", "notas": "Way. einalu'u → einaluu; confianza media", "categoria": "gramatica"},
    "erocu": {"es": "en (un líquido)", "fuente": "hipotético-no-verificado", "notas": "Way. eroku → erocu; confianza media", "categoria": "gramatica"},
    "ouya": {"es": "vámonos", "fuente": "hipotético-no-verificado", "notas": "Way. joo'uya → ouya; confianza media", "categoria": "gramatica"},
    "catei": {"es": "¡oiga! ka'i", "fuente": "hipotético-no-verificado", "notas": "Way. kaatei → catei; confianza media", "categoria": "gramatica"},
    "outpuna": {"es": "durante", "fuente": "hipotético-no-verificado", "notas": "Way. o'utpünaa → outpuna; confianza media", "categoria": "gramatica"},
    "oyuuna": {"es": "a escondidas", "fuente": "hipotético-no-verificado", "notas": "Way. ojuuna → oyuuna; confianza media", "categoria": "gramatica"},
    "oubuna-2": {"es": "debajo de", "fuente": "hipotético-no-verificado", "notas": "Way. oupünaa → oubuna; confianza media", "categoria": "gramatica"},
    "chiale": {"es": "o ella", "fuente": "hipotético-no-verificado", "notas": "Way. shiale → chiale; confianza media", "categoria": "gramatica"},
    "baneereeya": {"es": "no hasta que", "fuente": "hipotético-no-verificado", "notas": "Way. wane'ere'eya → baneereeya; confianza media", "categoria": "gramatica"},
    "auayuuse": {"es": "esposo, -a", "fuente": "hipotético-no-verificado", "notas": "Way. a'wayuuse → auayuuse; confianza media", "categoria": "parentesco"},
    "aui": {"es": "suegro (de mujer)", "fuente": "hipotético-no-verificado", "notas": "Way. a'üi → aui; confianza media", "categoria": "parentesco"},
    "aulu": {"es": "suegra (de mujer)", "fuente": "hipotético-no-verificado", "notas": "Way. a'ülü → aulu; confianza media", "categoria": "parentesco"},
    "aunu": {"es": "enemigo, -ga", "fuente": "hipotético-no-verificado", "notas": "Way. a'ünüü → aunu; confianza media", "categoria": "parentesco"},
    "airu": {"es": "tía (materna)", "fuente": "hipotético-no-verificado", "notas": "Way. aa'irü → airu; confianza media", "categoria": "parentesco"},
    "achoniru": {"es": "sobrino, -na", "fuente": "hipotético-no-verificado", "notas": "Way. achon'irü → achoniru; confianza media", "categoria": "parentesco"},
    "alechi": {"es": "cuñado (de mujer)", "fuente": "hipotético-no-verificado", "notas": "Way. aleshi → alechi; confianza media", "categoria": "parentesco"},
    "aluin": {"es": "nieto, -ta", "fuente": "hipotético-no-verificado", "notas": "Way. alüin → aluin; confianza media", "categoria": "parentesco"},
    "aluinyuu": {"es": "cuñada (de varón)", "fuente": "hipotético-no-verificado", "notas": "Way. alüinyuu → aluinyuu; confianza media", "categoria": "parentesco"},
    "amurayuin": {"es": "novio, -via", "fuente": "hipotético-no-verificado", "notas": "Way. amüraajüin → amurayuin; confianza media", "categoria": "parentesco"},
    "abuchi": {"es": "familia, pariente", "fuente": "hipotético-no-verificado", "notas": "Way. apüshi → abuchi; confianza media", "categoria": "parentesco"},
    "achimia": {"es": "suegro (de varón)", "fuente": "hipotético-no-verificado", "notas": "Way. ashimia → achimia; confianza media", "categoria": "parentesco"},
    "achiyachi": {"es": "padrastro", "fuente": "hipotético-no-verificado", "notas": "Way. ashiyaashi → achiyachi; confianza media", "categoria": "parentesco"},
    "achunuu": {"es": "hermana menor (de varón)", "fuente": "hipotético-no-verificado", "notas": "Way. ashunuu → achunuu; confianza media", "categoria": "parentesco"},
    "atuuchi": {"es": "abuelo", "fuente": "hipotético-no-verificado", "notas": "Way. atuushi → atuuchi; confianza media", "categoria": "parentesco"},
    "atunayutu": {"es": "amigo, -ga", "fuente": "hipotético-no-verificado", "notas": "Way. atünajutü → atunayutu; confianza media", "categoria": "parentesco"},
    "eeru": {"es": "cuñada (de mujer)", "fuente": "hipotético-no-verificado", "notas": "Way. e'erü → eeru; confianza media", "categoria": "parentesco"},
    "eiruma": {"es": "primogénito, -ta", "fuente": "hipotético-no-verificado", "notas": "Way. e'iruma → eiruma; confianza media", "categoria": "parentesco"},
    "eruin": {"es": "esposa", "fuente": "hipotético-no-verificado", "notas": "Way. eerüin → eruin; confianza media", "categoria": "parentesco"},
    "eiyasu": {"es": "madrastra", "fuente": "hipotético-no-verificado", "notas": "Way. eiyaasü → eiyasu; confianza media", "categoria": "parentesco"},
    "emechi": {"es": "suegra (de varón)", "fuente": "hipotético-no-verificado", "notas": "Way. emeshi → emechi; confianza media", "categoria": "parentesco"},
    "machon": {"es": "mamá, abuela", "fuente": "hipotético-no-verificado", "notas": "Way. maachon → machon; confianza media", "categoria": "parentesco"},
    "ouliuou": {"es": "descendiente", "fuente": "hipotético-no-verificado", "notas": "Way. oo'uliwo'u → ouliuou; confianza media", "categoria": "parentesco"},
    "chale": {"es": "último hijo, última hija", "fuente": "hipotético-no-verificado", "notas": "Way. shale → chale; confianza media", "categoria": "parentesco"},
    "aaya": {"es": "quemar", "fuente": "hipotético-no-verificado", "notas": "Way. a'ajaa → aaya; confianza media", "categoria": "verbos"},
    "aaliyaua": {"es": "estar de parto", "fuente": "hipotético-no-verificado", "notas": "Way. a'alijawaa → aaliyaua; confianza media", "categoria": "verbos"},
    "aana": {"es": "armar", "fuente": "hipotético-no-verificado", "notas": "Way. a'anaa → aana; confianza media", "categoria": "verbos"},
    "aanaua": {"es": "aakkuuaaippa", "fuente": "hipotético-no-verificado", "notas": "Way. a'anawaa → aanaua; confianza media", "categoria": "verbos"},
    "aata": {"es": "a'anawaa", "fuente": "hipotético-no-verificado", "notas": "Way. a'ataa → aata; confianza media", "categoria": "verbos"},
    "aatabaya": {"es": "esperar", "fuente": "hipotético-no-verificado", "notas": "Way. a'atapajaa → aatabaya; confianza media", "categoria": "verbos"},
    "achucuta": {"es": "pisar", "fuente": "hipotético-no-verificado", "notas": "Way. a'chükütaa → achucuta; confianza media", "categoria": "verbos"},
    "aktutayaua": {"es": "sufrir un ataque", "fuente": "hipotético-no-verificado", "notas": "Way. a'ktütajawaa → aktutayaua; confianza media", "categoria": "verbos"},
    "auaya": {"es": "alabar", "fuente": "hipotético-no-verificado", "notas": "Way. a'waajaa → auaya; confianza media", "categoria": "verbos"},
    "auata": {"es": "gritar", "fuente": "hipotético-no-verificado", "notas": "Way. a'waataa → auata; confianza media", "categoria": "verbos"},
    "auataua": {"es": "jactarse", "fuente": "hipotético-no-verificado", "notas": "Way. a'waatawaa → auataua; confianza media", "categoria": "verbos"},
    "aualacaya": {"es": "dispersar, esparcir", "fuente": "hipotético-no-verificado", "notas": "Way. a'walakajaa → aualacaya; confianza media", "categoria": "verbos"},
    "auanayaua": {"es": "cambiar", "fuente": "hipotético-no-verificado", "notas": "Way. a'wanajawaa → auanayaua; confianza media", "categoria": "verbos"},
    "ayata-2": {"es": "pegar", "fuente": "hipotético-no-verificado", "notas": "Way. a'yaataa → ayata; confianza media", "categoria": "verbos"},
    "ayalaya": {"es": "llorar", "fuente": "hipotético-no-verificado", "notas": "Way. a'yalajaa → ayalaya; confianza media", "categoria": "verbos"},
    "ayabuya": {"es": "coser", "fuente": "hipotético-no-verificado", "notas": "Way. a'yapüjaa → ayabuya; confianza media", "categoria": "verbos"},
    "auluya": {"es": "regañar", "fuente": "hipotético-no-verificado", "notas": "Way. a'ülüjaa → auluya; confianza media", "categoria": "verbos"},
    "auluyiraua": {"es": "discutir", "fuente": "hipotético-no-verificado", "notas": "Way. a'ülüjirawaa → auluyiraua; confianza media", "categoria": "verbos"},
    "aurulaua": {"es": "odiar", "fuente": "hipotético-no-verificado", "notas": "Way. a'ürülawaa → aurulaua; confianza media", "categoria": "verbos"},
    "ainra": {"es": "hacer", "fuente": "hipotético-no-verificado", "notas": "Way. aa'inraa → ainra; confianza media", "categoria": "verbos"},
    "ainyaya": {"es": "colgar una hamaca", "fuente": "hipotético-no-verificado", "notas": "Way. aa'inyajaa → ainyaya; confianza media", "categoria": "verbos"},
    "acata": {"es": "quitar", "fuente": "hipotético-no-verificado", "notas": "Way. aakataa → acata; confianza media", "categoria": "verbos"},
    "amuya": {"es": "ayunar", "fuente": "hipotético-no-verificado", "notas": "Way. aamüjaa → amuya; confianza media", "categoria": "verbos"},
    "abaua": {"es": "tomar, coger", "fuente": "hipotético-no-verificado", "notas": "Way. aapawaa → abaua; confianza media", "categoria": "verbos"},
    "achichiyaua": {"es": "enojarse", "fuente": "hipotético-no-verificado", "notas": "Way. aashichijawaa → achichiyaua; confianza media", "categoria": "verbos"},
    "auala-3": {"es": "aflojar", "fuente": "hipotético-no-verificado", "notas": "Way. aawalaa → auala; confianza media", "categoria": "verbos"},
    "aualaua": {"es": "aliviarse, mejorarse (fuego)", "fuente": "hipotético-no-verificado", "notas": "Way. aawalawaa → aualaua; confianza media", "categoria": "verbos"},
    "achayaua": {"es": "buscar", "fuente": "hipotético-no-verificado", "notas": "Way. achajawaa → achayaua; confianza media", "categoria": "verbos"},
    "achechera": {"es": "apretar", "fuente": "hipotético-no-verificado", "notas": "Way. achecheraa → achechera; confianza media", "categoria": "verbos"},
    "achiyira": {"es": "despertar", "fuente": "hipotético-no-verificado", "notas": "Way. achijiraa → achiyira; confianza media", "categoria": "verbos"},
    "achiyiraua": {"es": "despertarse", "fuente": "hipotético-no-verificado", "notas": "Way. achijirawaa → achiyiraua; confianza media", "categoria": "verbos"},
    "achicu": {"es": "soltar", "fuente": "hipotético-no-verificado", "notas": "Way. achikü → achicu; confianza media", "categoria": "verbos"},
    "achita": {"es": "martillar", "fuente": "hipotético-no-verificado", "notas": "Way. achitaa → achita; confianza media", "categoria": "verbos"},
    "achula": {"es": "besar", "fuente": "hipotético-no-verificado", "notas": "Way. achu'laa → achula; confianza media", "categoria": "verbos"},
    "achumaya": {"es": "estar aiwaa", "fuente": "hipotético-no-verificado", "notas": "Way. achumajaa → achumaya; confianza media", "categoria": "verbos"},
    "achunta": {"es": "pedir", "fuente": "hipotético-no-verificado", "notas": "Way. achuntaa → achunta; confianza media", "categoria": "verbos"},
    "aikcalaua": {"es": "sentarse", "fuente": "hipotético-no-verificado", "notas": "Way. aikkalawaa → aikcalaua; confianza media", "categoria": "verbos"},
    "ayaita": {"es": "recoger agua", "fuente": "hipotético-no-verificado", "notas": "Way. aja'itaa → ayaita; confianza media", "categoria": "verbos"},
    "ayalayaua": {"es": "terminarse, agotarse", "fuente": "hipotético-no-verificado", "notas": "Way. aja'lajawaa → ayalayaua; confianza media", "categoria": "verbos"},
    "ayalayeera": {"es": "agotar", "fuente": "hipotético-no-verificado", "notas": "Way. aja'laje'eraa → ayalayeera; confianza media", "categoria": "verbos"},
    "ayatta": {"es": "terminarse, acabarse", "fuente": "hipotético-no-verificado", "notas": "Way. aja'ttaa → ayatta; confianza media", "categoria": "verbos"},
    "ayabuluuua": {"es": "estar a cargo de", "fuente": "hipotético-no-verificado", "notas": "Way. ajapulu'uwaa → ayabuluuua; confianza media", "categoria": "verbos"},
    "ayaraitta": {"es": "halar", "fuente": "hipotético-no-verificado", "notas": "Way. ajaraittaa → ayaraitta; confianza media", "categoria": "verbos"},
    "ayuitta": {"es": "salir", "fuente": "hipotético-no-verificado", "notas": "Way. ajuittaa → ayuitta; confianza media", "categoria": "verbos"},
    "ayuittira": {"es": "sacar", "fuente": "hipotético-no-verificado", "notas": "Way. ajuittiraa → ayuittira; confianza media", "categoria": "verbos"},
    "ayuyaua": {"es": "bostezar", "fuente": "hipotético-no-verificado", "notas": "Way. ajujawaa → ayuyaua; confianza media", "categoria": "verbos"},
    "ayurulaya": {"es": "revolver", "fuente": "hipotético-no-verificado", "notas": "Way. ajurulajaa → ayurulaya; confianza media", "categoria": "verbos"},
    "ayuta": {"es": "tirar, lanzar", "fuente": "hipotético-no-verificado", "notas": "Way. ajutaa → ayuta; confianza media", "categoria": "verbos"},
    "ayutuua": {"es": "caerse", "fuente": "hipotético-no-verificado", "notas": "Way. ajutuwaa → ayutuua; confianza media", "categoria": "verbos"},
    "acachera": {"es": "colgar", "fuente": "hipotético-no-verificado", "notas": "Way. akacheraa → acachera; confianza media", "categoria": "verbos"},
    "acaiya": {"es": "fumar", "fuente": "hipotético-no-verificado", "notas": "Way. akaijaa → acaiya; confianza media", "categoria": "verbos"},
    "acaluuya": {"es": "llenar", "fuente": "hipotético-no-verificado", "notas": "Way. akalu'ujaa → acaluuya; confianza media", "categoria": "verbos"},
    "acanaya": {"es": "ganar", "fuente": "hipotético-no-verificado", "notas": "Way. akanajaa → acanaya; confianza media", "categoria": "verbos"},
    "acatala": {"es": "separar, apartar", "fuente": "hipotético-no-verificado", "notas": "Way. akatalaa → acatala; confianza media", "categoria": "verbos"},
    "acatalaua": {"es": "apartarse", "fuente": "hipotético-no-verificado", "notas": "Way. akatalawaa → acatalaua; confianza media", "categoria": "verbos"},
    "acotchaya": {"es": "ajurulajaa", "fuente": "hipotético-no-verificado", "notas": "Way. akotchajaa → acotchaya; confianza media", "categoria": "verbos"},
    "acurula": {"es": "tener frío", "fuente": "hipotético-no-verificado", "notas": "Way. akurulaa → acurula; confianza media", "categoria": "verbos"},
    "acutcuyaua": {"es": "temblar", "fuente": "hipotético-no-verificado", "notas": "Way. akutkujawaa → acutcuyaua; confianza media", "categoria": "verbos"},
    "acunula": {"es": "masticar", "fuente": "hipotético-no-verificado", "notas": "Way. akünülaa → acunula; confianza media", "categoria": "verbos"},
    "alabaya": {"es": "lamentar la muerte de", "fuente": "hipotético-no-verificado", "notas": "Way. alapajaa → alabaya; confianza media", "categoria": "verbos"},
    "aleua": {"es": "tener amistad", "fuente": "hipotético-no-verificado", "notas": "Way. aleewaa → aleua; confianza media", "categoria": "verbos"},
    "aleraya": {"es": "sentir asco por", "fuente": "hipotético-no-verificado", "notas": "Way. alerajaa → aleraya; confianza media", "categoria": "verbos"},
    "aliichaya": {"es": "ordeñar", "fuente": "hipotético-no-verificado", "notas": "Way. aliichajaa → aliichaya; confianza media", "categoria": "verbos"},
    "aliicayaua": {"es": "subir, subirse", "fuente": "hipotético-no-verificado", "notas": "Way. aliikajawaa → aliicayaua; confianza media", "categoria": "verbos"},
    "aluuya": {"es": "llevar, cargar, traer", "fuente": "hipotético-no-verificado", "notas": "Way. alü'üjaa → aluuya; confianza media", "categoria": "verbos"},
    "aluya": {"es": "rastrear", "fuente": "hipotético-no-verificado", "notas": "Way. alüjaa → aluya; confianza media", "categoria": "verbos"},
    "amausiya": {"es": "domar, amansar", "fuente": "hipotético-no-verificado", "notas": "Way. amaüsijaa → amausiya; confianza media", "categoria": "verbos"},
    "amoyuya": {"es": "dañar, perjudicar", "fuente": "hipotético-no-verificado", "notas": "Way. amojujaa → amoyuya; confianza media", "categoria": "verbos"},
    "amuliaya": {"es": "compadecerse de", "fuente": "hipotético-no-verificado", "notas": "Way. amüliajaa → amuliaya; confianza media", "categoria": "verbos"},
    "amuloulii": {"es": "perderse", "fuente": "hipotético-no-verificado", "notas": "Way. amüloulii → amuloulii; confianza media", "categoria": "verbos"},
    "amuscheya": {"es": "atragantarse", "fuente": "hipotético-no-verificado", "notas": "Way. amüschejaa → amuscheya; confianza media", "categoria": "verbos"},
    "anachonba": {"es": "ser bonito, -ta", "fuente": "hipotético-no-verificado", "notas": "Way. anachonwaa → anachonba; confianza media", "categoria": "verbos"},
    "anaya": {"es": "mirar, observar", "fuente": "hipotético-no-verificado", "notas": "Way. anajaa → anaya; confianza media", "categoria": "verbos"},
    "anaca": {"es": "alumbrar", "fuente": "hipotético-no-verificado", "notas": "Way. anakaa → anaca; confianza media", "categoria": "verbos"},
    "analaua": {"es": "averiguar qué es", "fuente": "hipotético-no-verificado", "notas": "Way. analawaa → analaua; confianza media", "categoria": "verbos"},
    "analu": {"es": "estar mejor de salud", "fuente": "hipotético-no-verificado", "notas": "Way. analüü → analu; confianza media", "categoria": "verbos"},
    "aneca": {"es": "escoger", "fuente": "hipotético-no-verificado", "notas": "Way. aneekaa → aneca; confianza media", "categoria": "verbos"},
    "anoukta": {"es": "corregir, arreglar", "fuente": "hipotético-no-verificado", "notas": "Way. anouktaa → anoukta; confianza media", "categoria": "verbos"},
    "antira": {"es": "traer", "fuente": "hipotético-no-verificado", "notas": "Way. antiraa → antira; confianza media", "categoria": "verbos"},
    "abalalaya": {"es": "ir de compras", "fuente": "hipotético-no-verificado", "notas": "Way. apalaalajaa → abalalaya; confianza media", "categoria": "verbos"},
    "abalanayaua": {"es": "fluir", "fuente": "hipotético-no-verificado", "notas": "Way. apalanajawaa → abalanayaua; confianza media", "categoria": "verbos"},
    "abaliraya": {"es": "mezclar", "fuente": "hipotético-no-verificado", "notas": "Way. apalirajaa → abaliraya; confianza media", "categoria": "verbos"},
    "abanabaya": {"es": "encontrarse con una", "fuente": "hipotético-no-verificado", "notas": "Way. apanapajaa → abanabaya; confianza media", "categoria": "verbos"},
    "abantayaua": {"es": "irse corriendo", "fuente": "hipotético-no-verificado", "notas": "Way. apantajawaa → abantayaua; confianza media", "categoria": "verbos"},
    "abasiayaua": {"es": "hacer una visita", "fuente": "hipotético-no-verificado", "notas": "Way. apasiajawaa → abasiayaua; confianza media", "categoria": "verbos"},
    "abula": {"es": "ser", "fuente": "hipotético-no-verificado", "notas": "Way. apüla → abula; confianza media", "categoria": "verbos"},
    "abulaya": {"es": "prohibir", "fuente": "hipotético-no-verificado", "notas": "Way. apülajaa → abulaya; confianza media", "categoria": "verbos"},
    "abunaya": {"es": "sembrar", "fuente": "hipotético-no-verificado", "notas": "Way. apünajaa → abunaya; confianza media", "categoria": "verbos"},
    "abuta": {"es": "dejar", "fuente": "hipotético-no-verificado", "notas": "Way. apütaa → abuta; confianza media", "categoria": "verbos"},
    "aralaya": {"es": "dejar en remojo", "fuente": "hipotético-no-verificado", "notas": "Way. aralajaa → aralaya; confianza media", "categoria": "verbos"},
    "asalaya": {"es": "afilar", "fuente": "hipotético-no-verificado", "notas": "Way. asalajaa → asalaya; confianza media", "categoria": "verbos"},
    "achaualaua": {"es": "ponerse de pie", "fuente": "hipotético-no-verificado", "notas": "Way. asha'walawaa → achaualaua; confianza media", "categoria": "verbos"},
    "achaitta": {"es": "jugar", "fuente": "hipotético-no-verificado", "notas": "Way. ashaittaa → achaitta; confianza media", "categoria": "verbos"},
    "achabataua": {"es": "preocuparse", "fuente": "hipotético-no-verificado", "notas": "Way. ashapatawaa → achabataua; confianza media", "categoria": "verbos"},
    "achata": {"es": "sanar (una herida)", "fuente": "hipotético-no-verificado", "notas": "Way. ashataa → achata; confianza media", "categoria": "verbos"},
    "acheeyiraua": {"es": "pelear con puños", "fuente": "hipotético-no-verificado", "notas": "Way. ashe'ejirawaa → acheeyiraua; confianza media", "categoria": "verbos"},
    "acheeta": {"es": "golpear, patear", "fuente": "hipotético-no-verificado", "notas": "Way. ashe'etaa → acheeta; confianza media", "categoria": "verbos"},
    "achiita": {"es": "orinar", "fuente": "hipotético-no-verificado", "notas": "Way. ashiitaa → achiita; confianza media", "categoria": "verbos"},
    "achiyaua": {"es": "lavar (ropa)", "fuente": "hipotético-no-verificado", "notas": "Way. ashijawaa → achiyaua; confianza media", "categoria": "verbos"},
    "achuta": {"es": "meterse, entrar a la", "fuente": "hipotético-no-verificado", "notas": "Way. ashutaa → achuta; confianza media", "categoria": "verbos"},
    "asiiyayaua": {"es": "ensillar", "fuente": "hipotético-no-verificado", "notas": "Way. asiiyajawaa → asiiyayaua; confianza media", "categoria": "verbos"},
    "asiya": {"es": "asar", "fuente": "hipotético-no-verificado", "notas": "Way. asijaa → asiya; confianza media", "categoria": "verbos"},
    "asiraya": {"es": "reirse", "fuente": "hipotético-no-verificado", "notas": "Way. asirajaa → asiraya; confianza media", "categoria": "verbos"},
    "asiranayaua": {"es": "resbalarse", "fuente": "hipotético-no-verificado", "notas": "Way. asiranajawaa → asiranayaua; confianza media", "categoria": "verbos"},
    "asiuata": {"es": "desatar", "fuente": "hipotético-no-verificado", "notas": "Way. asiwataa → asiuata; confianza media", "categoria": "verbos"},
    "asoukta": {"es": "responder", "fuente": "hipotético-no-verificado", "notas": "Way. asouktaa → asoukta; confianza media", "categoria": "verbos"},
    "asuca": {"es": "recoger leña", "fuente": "hipotético-no-verificado", "notas": "Way. asukaa → asuca; confianza media", "categoria": "verbos"},
    "asuuta": {"es": "arrancar", "fuente": "hipotético-no-verificado", "notas": "Way. asü'ütaa → asuuta; confianza media", "categoria": "verbos"},
    "asucuita": {"es": "rasgarse", "fuente": "hipotético-no-verificado", "notas": "Way. asüküitaa → asucuita; confianza media", "categoria": "verbos"},
    "atamaua": {"es": "levantarse", "fuente": "hipotético-no-verificado", "notas": "Way. atamawaa → atamaua; confianza media", "categoria": "verbos"},
    "atauyaua": {"es": "violar (a una mujer)", "fuente": "hipotético-no-verificado", "notas": "Way. ataüjawaa → atauyaua; confianza media", "categoria": "verbos"},
    "atcaua": {"es": "pelear", "fuente": "hipotético-no-verificado", "notas": "Way. atkawaa → atcaua; confianza media", "categoria": "verbos"},
    "atpaya": {"es": "recolectar (alimento)", "fuente": "hipotético-no-verificado", "notas": "Way. atpajaa → atpaya; confianza media", "categoria": "verbos"},
    "atuya": {"es": "saber", "fuente": "hipotético-no-verificado", "notas": "Way. atüjaa → atuya; confianza media", "categoria": "verbos"},
    "atucaua": {"es": "atascarse", "fuente": "hipotético-no-verificado", "notas": "Way. atükawaa → atucaua; confianza media", "categoria": "verbos"},
    "atutuya": {"es": "animar, ayolojo", "fuente": "hipotético-no-verificado", "notas": "Way. atütüjaa → atutuya; confianza media", "categoria": "verbos"},
    "auayaua": {"es": "rajarse, partirse", "fuente": "hipotético-no-verificado", "notas": "Way. awajawaa → auayaua; confianza media", "categoria": "verbos"},
    "auareya": {"es": "barrer", "fuente": "hipotético-no-verificado", "notas": "Way. awareejaa → auareya; confianza media", "categoria": "verbos"},
    "auataua-2": {"es": "correr", "fuente": "hipotético-no-verificado", "notas": "Way. awatawaa → auataua; confianza media", "categoria": "verbos"},
    "ayauata": {"es": "reconocer", "fuente": "hipotético-no-verificado", "notas": "Way. ayaawataa → ayauata; confianza media", "categoria": "verbos"},
    "ayalera": {"es": "levantar, alzar", "fuente": "hipotético-no-verificado", "notas": "Way. ayaleraa → ayalera; confianza media", "categoria": "verbos"},
    "ayouyiraua": {"es": "competir", "fuente": "hipotético-no-verificado", "notas": "Way. ayoujirawaa → ayouyiraua; confianza media", "categoria": "verbos"},
    "ayounja": {"es": "azotar", "fuente": "hipotético-no-verificado", "notas": "Way. ayounjaa → ayounja; confianza media", "categoria": "verbos"},
    "ayuyaua-2": {"es": "moler", "fuente": "hipotético-no-verificado", "notas": "Way. ayüüjawaa → ayuyaua; confianza media", "categoria": "verbos"},
    "auya": {"es": "cortar (el pelo), afeitar", "fuente": "hipotético-no-verificado", "notas": "Way. aüjaa → auya; confianza media", "categoria": "verbos"},
    "auyaua": {"es": "matar (ganado)", "fuente": "hipotético-no-verificado", "notas": "Way. aüjawaa → auyaua; confianza media", "categoria": "verbos"},
    "aurula": {"es": "estar flaco, -ca", "fuente": "hipotético-no-verificado", "notas": "Way. aürülaa → aurula; confianza media", "categoria": "verbos"},
    "eiiya": {"es": "tener diarrea", "fuente": "hipotético-no-verificado", "notas": "Way. e'iijaa → eiiya; confianza media", "categoria": "verbos"},
    "eiita": {"es": "defecar", "fuente": "hipotético-no-verificado", "notas": "Way. e'iitaa → eiita; confianza media", "categoria": "verbos"},
    "eica": {"es": "enseñar, instruir", "fuente": "hipotético-no-verificado", "notas": "Way. e'ikaa → eica; confianza media", "categoria": "verbos"},
    "eicayaua": {"es": "llevar y dejar", "fuente": "hipotético-no-verificado", "notas": "Way. e'ikajawaa → eicayaua; confianza media", "categoria": "verbos"},
    "eicaua": {"es": "estar herido, -da", "fuente": "hipotético-no-verificado", "notas": "Way. e'ikawaa → eicaua; confianza media", "categoria": "verbos"},
    "eina": {"es": "tejer con aguja", "fuente": "hipotético-no-verificado", "notas": "Way. e'inaa → eina; confianza media", "categoria": "verbos"},
    "eibunaua": {"es": "llevar y dejar de", "fuente": "hipotético-no-verificado", "notas": "Way. e'ipünawaa → eibunaua; confianza media", "categoria": "verbos"},
    "eita": {"es": "aportar", "fuente": "hipotético-no-verificado", "notas": "Way. e'itaa → eita; confianza media", "categoria": "verbos"},
    "eitaua": {"es": "poner, meter", "fuente": "hipotético-no-verificado", "notas": "Way. e'itawaa → eitaua; confianza media", "categoria": "verbos"},
    "eraya": {"es": "conocer", "fuente": "hipotético-no-verificado", "notas": "Way. e'raajaa → eraya; confianza media", "categoria": "verbos"},
    "eraya-2": {"es": "mirar", "fuente": "hipotético-no-verificado", "notas": "Way. e'rajaa → eraya; confianza media", "categoria": "verbos"},
    "eirataua": {"es": "cambiar de esposo, -sa", "fuente": "hipotético-no-verificado", "notas": "Way. ee'iratawaa → eirataua; confianza media", "categoria": "verbos"},
    "eua": {"es": "haber, existir", "fuente": "hipotético-no-verificado", "notas": "Way. eewaa → eua; confianza media", "categoria": "verbos"},
    "euaua": {"es": "accidentarse", "fuente": "hipotético-no-verificado", "notas": "Way. eewawaa → euaua; confianza media", "categoria": "verbos"},
    "eimalaua": {"es": "ekiipala n", "fuente": "hipotético-no-verificado", "notas": "Way. eimalawaa → eimalaua; confianza media", "categoria": "verbos"},
    "eibira": {"es": "perseguir", "fuente": "hipotético-no-verificado", "notas": "Way. eipiraa → eibira; confianza media", "categoria": "verbos"},
    "eisalaua": {"es": "acostarse", "fuente": "hipotético-no-verificado", "notas": "Way. eisalawaa → eisalaua; confianza media", "categoria": "verbos"},
    "eitaya": {"es": "repartir", "fuente": "hipotético-no-verificado", "notas": "Way. eitajaa → eitaya; confianza media", "categoria": "verbos"},
    "eiteera": {"es": "devolver", "fuente": "hipotético-no-verificado", "notas": "Way. eite'eraa → eiteera; confianza media", "categoria": "verbos"},
    "eiyaya": {"es": "curar", "fuente": "hipotético-no-verificado", "notas": "Way. eiyajaa → eiyaya; confianza media", "categoria": "verbos"},
    "eyeyeraua": {"es": "cuchichear, secretear", "fuente": "hipotético-no-verificado", "notas": "Way. ejejerawaa → eyeyeraua; confianza media", "categoria": "verbos"},
    "eyemplo": {"es": "estar cerrado, -da", "fuente": "hipotético-no-verificado", "notas": "Way. ejemplo → eyemplo; confianza media", "categoria": "verbos"},
    "eyeta": {"es": "escupir", "fuente": "hipotético-no-verificado", "notas": "Way. ejetaa → eyeta; confianza media", "categoria": "verbos"},
    "eyita": {"es": "verter (polvos o granos)", "fuente": "hipotético-no-verificado", "notas": "Way. ejitaa → eyita; confianza media", "categoria": "verbos"},
    "eyittaua": {"es": "atar", "fuente": "hipotético-no-verificado", "notas": "Way. ejittawaa → eyittaua; confianza media", "categoria": "verbos"},
    "eceroyira": {"es": "meter", "fuente": "hipotético-no-verificado", "notas": "Way. ekerojiraa → eceroyira; confianza media", "categoria": "verbos"},
    "ecii": {"es": "dolerle la cabeza", "fuente": "hipotético-no-verificado", "notas": "Way. ekii → ecii; confianza media", "categoria": "verbos"},
    "eciraya": {"es": "enseñar", "fuente": "hipotético-no-verificado", "notas": "Way. ekirajaa → eciraya; confianza media", "categoria": "verbos"},
    "emeerayaua": {"es": "bromear", "fuente": "hipotético-no-verificado", "notas": "Way. eme'erajawaa → emeerayaua; confianza media", "categoria": "verbos"},
    "ebeyaua": {"es": "prender, encender", "fuente": "hipotético-no-verificado", "notas": "Way. epejawaa → ebeyaua; confianza media", "categoria": "verbos"},
    "ebetta": {"es": "tocar", "fuente": "hipotético-no-verificado", "notas": "Way. epettaa → ebetta; confianza media", "categoria": "verbos"},
    "ebiraya": {"es": "llenar, inflar", "fuente": "hipotético-no-verificado", "notas": "Way. epirajaa → ebiraya; confianza media", "categoria": "verbos"},
    "eueta": {"es": "salir a la vista, aparecer", "fuente": "hipotético-no-verificado", "notas": "Way. eweetaa → eueta; confianza media", "categoria": "verbos"},
    "euiiya": {"es": "silbar", "fuente": "hipotético-no-verificado", "notas": "Way. ewiijaa → euiiya; confianza media", "categoria": "verbos"},
    "iche": {"es": "estar tenso, -sa", "fuente": "hipotético-no-verificado", "notas": "Way. ichee → iche; confianza media", "categoria": "verbos"},
    "icha": {"es": "sufrir una quemadura", "fuente": "hipotético-no-verificado", "notas": "Way. ishaa → icha; confianza media", "categoria": "verbos"},
    "ita": {"es": "secarse", "fuente": "hipotético-no-verificado", "notas": "Way. itaa → ita; confianza media", "categoria": "verbos"},
    "iua": {"es": "ser prostituta", "fuente": "hipotético-no-verificado", "notas": "Way. iwaa → iua; confianza media", "categoria": "verbos"},
    "aiyaua": {"es": "faltar", "fuente": "hipotético-no-verificado", "notas": "Way. ja'ijawaa → aiyaua; confianza media", "categoria": "verbos"},
    "aiua": {"es": "estar caliente", "fuente": "hipotético-no-verificado", "notas": "Way. ja'iwaa → aiua; confianza media", "categoria": "verbos"},
    "aya-2": {"es": "aparecer", "fuente": "hipotético-no-verificado", "notas": "Way. ja'yaa → aya; confianza media", "categoria": "verbos"},
    "ayumuu": {"es": "estar bien", "fuente": "hipotético-no-verificado", "notas": "Way. ja'yumuu → ayumuu; confianza media", "categoria": "verbos"},
    "ala": {"es": "dónde estar", "fuente": "hipotético-no-verificado", "notas": "Way. jalaa → ala; confianza media", "categoria": "verbos"},
    "amama": {"es": "ser liviano, -na", "fuente": "hipotético-no-verificado", "notas": "Way. jamaamaa → amama; confianza media", "categoria": "verbos"},
    "abulii": {"es": "tener vergüenza", "fuente": "hipotético-no-verificado", "notas": "Way. japülii → abulii; confianza media", "categoria": "verbos"},
    "achuuua": {"es": "ser agrio, -a", "fuente": "hipotético-no-verificado", "notas": "Way. jashü'üwaa → achuuua; confianza media", "categoria": "verbos"},
    "auaaua": {"es": "estar flojo, -ja", "fuente": "hipotético-no-verificado", "notas": "Way. jawa'awaa → auaaua; confianza media", "categoria": "verbos"},
    "auata-2": {"es": "ser pesado, -da", "fuente": "hipotético-no-verificado", "notas": "Way. jawataa → auata; confianza media", "categoria": "verbos"},
    "aya-3": {"es": "ser barato, -ta", "fuente": "hipotético-no-verificado", "notas": "Way. jayaa → aya; confianza media", "categoria": "verbos"},
    "yeue": {"es": "estar maduro, -ra", "fuente": "hipotético-no-verificado", "notas": "Way. je'wee → yeue; confianza media", "categoria": "verbos"},
    "yemeta": {"es": "ser sabroso, -sa", "fuente": "hipotético-no-verificado", "notas": "Way. jemetaa → yemeta; confianza media", "categoria": "verbos"},
    "yera": {"es": "cuánto ser", "fuente": "hipotético-no-verificado", "notas": "Way. jera → yera; confianza media", "categoria": "verbos"},
    "yerula": {"es": "ser ancho, -cha", "fuente": "hipotético-no-verificado", "notas": "Way. jerulaa → yerula; confianza media", "categoria": "verbos"},
    "oloto": {"es": "tener ampolla", "fuente": "hipotético-no-verificado", "notas": "Way. jolotoo → oloto; confianza media", "categoria": "verbos"},
    "oso": {"es": "estar seco, -ca", "fuente": "hipotético-no-verificado", "notas": "Way. josoo → oso; confianza media", "categoria": "verbos"},
    "ota": {"es": "arder", "fuente": "hipotético-no-verificado", "notas": "Way. jotaa → ota; confianza media", "categoria": "verbos"},
    "oyoto": {"es": "estar sentado, -da", "fuente": "hipotético-no-verificado", "notas": "Way. joyotoo → oyoto; confianza media", "categoria": "verbos"},
    "utata": {"es": "estar abierto, -ta", "fuente": "hipotético-no-verificado", "notas": "Way. jutataa → utata; confianza media", "categoria": "verbos"},
    "cauayuuse": {"es": "tener esposo, -sa", "fuente": "hipotético-no-verificado", "notas": "Way. ka'wayuusee → cauayuuse; confianza media", "categoria": "verbos"},
    "cayata": {"es": "estar un poco retirado", "fuente": "hipotético-no-verificado", "notas": "Way. ka'yataa → cayata; confianza media", "categoria": "verbos"},
    "cainjala": {"es": "causar daño, pecar", "fuente": "hipotético-no-verificado", "notas": "Way. kaainjalaa → cainjala; confianza media", "categoria": "verbos"},
    "cacheta": {"es": "estar colgado, -da", "fuente": "hipotético-no-verificado", "notas": "Way. kachetaa → cacheta; confianza media", "categoria": "verbos"},
    "cacua": {"es": "ser veloz (andando)", "fuente": "hipotético-no-verificado", "notas": "Way. kakuaa → cacua; confianza media", "categoria": "verbos"},
    "caluuua": {"es": "contener", "fuente": "hipotético-no-verificado", "notas": "Way. kalu'uwaa → caluuua; confianza media", "categoria": "verbos"},
    "canulia": {"es": "ser llamado, -da", "fuente": "hipotético-no-verificado", "notas": "Way. kanüliaa → canulia; confianza media", "categoria": "verbos"},
    "cabu": {"es": "estar atado, -da", "fuente": "hipotético-no-verificado", "notas": "Way. kapüü → cabu; confianza media", "categoria": "verbos"},
    "casa": {"es": "tener filo", "fuente": "hipotético-no-verificado", "notas": "Way. kasaa → casa; confianza media", "categoria": "verbos"},
    "catchinba": {"es": "ser fuerte", "fuente": "hipotético-no-verificado", "notas": "Way. katchinwaa → catchinba; confianza media", "categoria": "verbos"},
    "cena": {"es": "derramarse", "fuente": "hipotético-no-verificado", "notas": "Way. keenaa → cena; confianza media", "categoria": "verbos"},
    "cisaua": {"es": "estar guisado, -da", "fuente": "hipotético-no-verificado", "notas": "Way. kisaawaa → cisaua; confianza media", "categoria": "verbos"},
    "cooyoua": {"es": "ser redondo, -da", "fuente": "hipotético-no-verificado", "notas": "Way. ko'oyowaa → cooyoua; confianza media", "categoria": "verbos"},
    "couta": {"es": "estar callado, -da", "fuente": "hipotético-no-verificado", "notas": "Way. ko'utaa → couta; confianza media", "categoria": "verbos"},
    "coyuta": {"es": "ser caro, -ra", "fuente": "hipotético-no-verificado", "notas": "Way. kojutaa → coyuta; confianza media", "categoria": "verbos"},
    "coya": {"es": "pincharse", "fuente": "hipotético-no-verificado", "notas": "Way. koojaa → coya; confianza media", "categoria": "verbos"},
    "laualaua": {"es": "ser flexible", "fuente": "hipotético-no-verificado", "notas": "Way. la'walawaa → laualaua; confianza media", "categoria": "verbos"},
    "lemta": {"es": "arrastrarse", "fuente": "hipotético-no-verificado", "notas": "Way. lemtaa → lemta; confianza media", "categoria": "verbos"},
    "lota": {"es": "ser recto, -ta", "fuente": "hipotético-no-verificado", "notas": "Way. lotaa → lota; confianza media", "categoria": "verbos"},
    "mainba": {"es": "ser necio, -cia", "fuente": "hipotético-no-verificado", "notas": "Way. maa'inwaa → mainba; confianza media", "categoria": "verbos"},
    "macheeua": {"es": "ser sordo, -da", "fuente": "hipotético-no-verificado", "notas": "Way. mache'ewaa → macheeua; confianza media", "categoria": "verbos"},
    "maitta": {"es": "estar en calma el tiempo", "fuente": "hipotético-no-verificado", "notas": "Way. maittaa → maitta; confianza media", "categoria": "verbos"},
    "mamainna": {"es": "ser loco, -ca", "fuente": "hipotético-no-verificado", "notas": "Way. mamainnaa → mamainna; confianza media", "categoria": "verbos"},
    "mabuleua": {"es": "ser fácil", "fuente": "hipotético-no-verificado", "notas": "Way. mapülewaa → mabuleua; confianza media", "categoria": "verbos"},
    "maralu": {"es": "ser estéril", "fuente": "hipotético-no-verificado", "notas": "Way. maralüü → maralu; confianza media", "categoria": "verbos"},
    "mariiya": {"es": "ser amarillo, -lla", "fuente": "hipotético-no-verificado", "notas": "Way. mariiyaa → mariiya; confianza media", "categoria": "verbos"},
    "matsuinba": {"es": "estar sin fuerza", "fuente": "hipotético-no-verificado", "notas": "Way. matsüinwaa → matsuinba; confianza media", "categoria": "verbos"},
    "miyasu": {"es": "tener sed", "fuente": "hipotético-no-verificado", "notas": "Way. miyaasüü → miyasu; confianza media", "categoria": "verbos"},
    "moluu": {"es": "tener 2", "fuente": "hipotético-no-verificado", "notas": "Way. mmoluu → moluu; confianza media", "categoria": "verbos"},
    "mouu": {"es": "ser ciego, -ga", "fuente": "hipotético-no-verificado", "notas": "Way. mo'uu → mouu; confianza media", "categoria": "verbos"},
    "mutsiiya": {"es": "ser negro, -gra", "fuente": "hipotético-no-verificado", "notas": "Way. mütsiiyaa → mutsiiya; confianza media", "categoria": "verbos"},
    "ootoyoua": {"es": "sacudir", "fuente": "hipotético-no-verificado", "notas": "Way. o'otojowaa → ootoyoua; confianza media", "categoria": "verbos"},
    "ootoua": {"es": "montar", "fuente": "hipotético-no-verificado", "notas": "Way. o'otowaa → ootoua; confianza media", "categoria": "verbos"},
    "otta": {"es": "aterrizar", "fuente": "hipotético-no-verificado", "notas": "Way. o'ttaa → otta; confianza media", "categoria": "verbos"},
    "otteera": {"es": "hacer pasar", "fuente": "hipotético-no-verificado", "notas": "Way. o'tte'eraa → otteera; confianza media", "categoria": "verbos"},
    "ouliya": {"es": "cargar (a un niño)", "fuente": "hipotético-no-verificado", "notas": "Way. o'ulijaa → ouliya; confianza media", "categoria": "verbos"},
    "ounira": {"es": "llevar", "fuente": "hipotético-no-verificado", "notas": "Way. o'uniraa → ounira; confianza media", "categoria": "verbos"},
    "oyoto-2": {"es": "verter (un líquido)", "fuente": "hipotético-no-verificado", "notas": "Way. o'yotoo → oyoto; confianza media", "categoria": "verbos"},
    "oyotoua": {"es": "cortar (con cuchillo, abdomen)", "fuente": "hipotético-no-verificado", "notas": "Way. o'yotowaa → oyotoua; confianza media", "categoria": "verbos"},
    "oyoita": {"es": "enterrar", "fuente": "hipotético-no-verificado", "notas": "Way. ojoitaa → oyoita; confianza media", "categoria": "verbos"},
    "oyotta": {"es": "morder", "fuente": "hipotético-no-verificado", "notas": "Way. ojottaa → oyotta; confianza media", "categoria": "verbos"},
    "oyununtaua": {"es": "o'ktaa", "fuente": "hipotético-no-verificado", "notas": "Way. ojununtawaa → oyununtaua; confianza media", "categoria": "verbos"},
    "oyutta": {"es": "caer", "fuente": "hipotético-no-verificado", "notas": "Way. ojuttaa → oyutta; confianza media", "categoria": "verbos"},
    "oyuttira": {"es": "derribar, 2", "fuente": "hipotético-no-verificado", "notas": "Way. ojuttiraa → oyuttira; confianza media", "categoria": "verbos"},
    "ocoolo": {"es": "envolver", "fuente": "hipotético-no-verificado", "notas": "Way. oko'oloo → ocoolo; confianza media", "categoria": "verbos"},
    "ocoloyo": {"es": "llevar regalo", "fuente": "hipotético-no-verificado", "notas": "Way. okolojoo → ocoloyo; confianza media", "categoria": "verbos"},
    "oui": {"es": "tropezar", "fuente": "hipotético-no-verificado", "notas": "Way. oo'ui → oui; confianza media", "categoria": "verbos"},
    "oyo": {"es": "raspar", "fuente": "hipotético-no-verificado", "notas": "Way. oojoo → oyo; confianza media", "categoria": "verbos"},
    "onoyo": {"es": "toser", "fuente": "hipotético-no-verificado", "notas": "Way. oonojoo → onoyo; confianza media", "categoria": "verbos"},
    "otoyo": {"es": "perforar", "fuente": "hipotético-no-verificado", "notas": "Way. ootojoo → otoyo; confianza media", "categoria": "verbos"},
    "oboloyo": {"es": "hervir", "fuente": "hipotético-no-verificado", "notas": "Way. opoolojoo → oboloyo; confianza media", "categoria": "verbos"},
    "ochoyo": {"es": "desollar, pelar, curandero, -ra", "fuente": "hipotético-no-verificado", "notas": "Way. oshojoo → ochoyo; confianza media", "categoria": "verbos"},
    "ounjula": {"es": "esconder", "fuente": "hipotético-no-verificado", "notas": "Way. ounjulaa → ounjula; confianza media", "categoria": "verbos"},
    "ounjulaua": {"es": "esconderse", "fuente": "hipotético-no-verificado", "notas": "Way. ounjulawaa → ounjulaua; confianza media", "categoria": "verbos"},
    "ourula": {"es": "estar hinchado, -da", "fuente": "hipotético-no-verificado", "notas": "Way. ourulaa → ourula; confianza media", "categoria": "verbos"},
    "ouchuua": {"es": "tener fiebre", "fuente": "hipotético-no-verificado", "notas": "Way. oushuwaa → ouchuua; confianza media", "categoria": "verbos"},
    "ouyanta": {"es": "volver", "fuente": "hipotético-no-verificado", "notas": "Way. ouyantaa → ouyanta; confianza media", "categoria": "verbos"},
    "painba": {"es": "estar de acuerdo", "fuente": "hipotético-no-verificado", "notas": "Way. paa'inwaa → painba; confianza media", "categoria": "verbos"},
    "palaua": {"es": "ser salado, -da", "fuente": "hipotético-no-verificado", "notas": "Way. palawaa → palaua; confianza media", "categoria": "verbos"},
    "paliraua": {"es": "estar mezclado, -da", "fuente": "hipotético-no-verificado", "notas": "Way. palirawaa → paliraua; confianza media", "categoria": "verbos"},
    "pansaua": {"es": "estar derecho, -cha", "fuente": "hipotético-no-verificado", "notas": "Way. pansawaa → pansaua; confianza media", "categoria": "verbos"},
    "peye": {"es": "estar cerca", "fuente": "hipotético-no-verificado", "notas": "Way. pejee → peye; confianza media", "categoria": "verbos"},
    "pera": {"es": "ser mocho, -cha", "fuente": "hipotético-no-verificado", "notas": "Way. peraa → pera; confianza media", "categoria": "verbos"},
    "pula": {"es": "ser poderoso, -sa", "fuente": "hipotético-no-verificado", "notas": "Way. pülaa → pula; confianza media", "categoria": "verbos"},
    "puresa": {"es": "estar preso, -sa", "fuente": "hipotético-no-verificado", "notas": "Way. püreesaa → puresa; confianza media", "categoria": "verbos"},
    "chocota": {"es": "ser curvo, -va", "fuente": "hipotético-no-verificado", "notas": "Way. shokotaa → chocota; confianza media", "categoria": "verbos"},
    "chotta": {"es": "gotear", "fuente": "hipotético-no-verificado", "notas": "Way. shottaa → chotta; confianza media", "categoria": "verbos"},
    "sirasira": {"es": "ser liso, -sa", "fuente": "hipotético-no-verificado", "notas": "Way. sirasiraa → sirasira; confianza media", "categoria": "verbos"},
    "bauata": {"es": "soplar (el viento)", "fuente": "hipotético-no-verificado", "notas": "Way. waawataa → bauata; confianza media", "categoria": "verbos"},
    "balaua": {"es": "estar pagado, -da", "fuente": "hipotético-no-verificado", "notas": "Way. walawaa → balaua; confianza media", "categoria": "verbos"},
    "banaua": {"es": "ser lo mismo, ser", "fuente": "hipotético-no-verificado", "notas": "Way. wanaawaa → banaua; confianza media", "categoria": "verbos"},
    "buinsira": {"es": "ahogarse (en agua)", "fuente": "hipotético-no-verificado", "notas": "Way. wüinsiraa → buinsira; confianza media", "categoria": "verbos"},
    "buitta": {"es": "ser azul, ser verde", "fuente": "hipotético-no-verificado", "notas": "Way. wüittaa → buitta; confianza media", "categoria": "verbos"},
    "yalayala": {"es": "ser áspero, -ra", "fuente": "hipotético-no-verificado", "notas": "Way. yalayalaa → yalayala; confianza media", "categoria": "verbos"},
    "yarutta": {"es": "estar sucio", "fuente": "hipotético-no-verificado", "notas": "Way. yarüttaa → yarutta; confianza media", "categoria": "verbos"},
    "yocuta": {"es": "estar apagado, -da", "fuente": "hipotético-no-verificado", "notas": "Way. yokutaa → yocuta; confianza media", "categoria": "verbos"},
}
