"""
CURIANA — Propuesta de minado de Alvarado 1921 (tarea F3)
============================================================

GENERADO por `minar_alvarado_glosario.py` — no editar a mano.

    Alvarado, Lisandro (1921). Glosario de voces indígenas de Venezuela.
    Ediciones Victoria, Caracas. → fuentes_caquetios/

⚠ NADA DE ESTE ARCHIVO ENTRA A `VOCABULARIO_BASE` SIN REVISIÓN HUMANA.
Alvarado es un glosario NACIONAL: caribe, cumanagoto, chaima, taíno,
guajiro, nahua y antillanismos castellanizados. La mayor parte no es
caquetío. Los niveles siguen la escala del protocolo
`investigacion/disenos/02_protocolo_habla_paraguanera.md` §5:

    A — atestación colonial o atribución caquetía explícita
    B — sobrevive a los 6 filtros + localización Coro/Falcón/Paraguaná
    C — sobrevive pero con señal débil
    D — descartada (documentada con su razón, para no re-minarla)

POLÍTICA D7: `glosa_fuente` es lo que dice Alvarado, verbatim — es la
que un agente hablaría. `identificacion_moderna` es el taxón, como nota
auditable. Cuando difieren, el conflicto queda visible, no resuelto.
"""


# ==================================================================
# NIVEL A — atestación colonial / atribución caquetía explícita
# ==================================================================
CANDIDATOS_A: dict[str, dict] = {
    "maure": {
        "glosa_fuente": "'Son a fuer de faxas mujeriles muy curiosas'. — — (Carv. 168). || En Coro vale la voz por pieza de dril fuerte para pantalones. (Véase Ernst, La Bxp. 561). '*A otros más honestos un pedazo De maure cu",
        "identificacion_moderna": "",
        "pagina": 216,
        "lema_alvarado": "MÁURE",
        "nivel": "A",
        "razon": "Atestada por Carvajal y Castellanos como faja/tejido, y viva en Coro en 1921 con la acepción de 'pieza de dril'. Doble anclaje: colonial y coriano.  [curación humana]",
    },
    "mene": {
        "glosa_fuente": "'Betún a manera de brea o pez derretida'. (Oviedo, II. 301). ^'Múne es una goma negra de Tierra Fir— me, de la que se sirven como de la pez'. (Bretón, Dice. car. fr.). 'Minas inagotables de menc o pez",
        "identificacion_moderna": "",
        "pagina": 218,
        "lema_alvarado": "MÉNE",
        "nivel": "A",
        "razon": "Atestación colonial de primera (Oviedo II.301) + localización en Coro y Maracaibo (Codazzi). Campo semántico local e intraducible.  [curación humana]",
    },
    "poporo": {
        "glosa_fuente": "Arma, a manera de porra, usada por los an tiguos Caquetíos y los Guagíros. Ref. Cast. Bleg. I. c. 3?; — A^. Reino, I. 46. 65. Cf. Bapóron, Tolondro, lobanillo, || chichón, tumor, o cosa así.~'Ya tendr",
        "identificacion_moderna": "",
        "pagina": 255,
        "lema_alvarado": "POPORO",
        "nivel": "A",
        "razon": "Alvarado la atribuye EXPLÍCITAMENTE a los antiguos Caquetíos (y a los Guajiros), citando a Castellanos. Es la única voz de todo el glosario con atribución caquetía directa.  [curación humana]",
    },
}


# ==================================================================
# NIVEL B — sobreviven a los 6 filtros, localizadas en Coro/Falcón/Paraguaná
# ==================================================================
CANDIDATOS_B: dict[str, dict] = {
    "achichive": {
        "glosa_fuente": "Árbol indeterminado de Coro. *",
        "identificacion_moderna": "",
        "pagina": 3,
        "lema_alvarado": "ACHICHIVE",
        "nivel": "B",
        "razon": "Árbol indeterminado de Coro. Sin filtro.  [curación humana]",
    },
    "aiton": {
        "glosa_fuente": "Sima profunda formada en algunos parajes delE. Falcón.",
        "identificacion_moderna": "",
        "pagina": 5,
        "lema_alvarado": "AITÓN",
        "nivel": "B",
        "razon": "'Sima profunda' del E. Falcón: término de PAISAJE, exactamente el hueco léxico que ecologia_lexicon_map.md daba por vacío. Sin competidor identificado en ninguno de los 6 filtros.  [curación humana]",
    },
    "anuano": {
        "glosa_fuente": "Árbol indeterminado de Coro y Yaracúi.",
        "identificacion_moderna": "",
        "pagina": 9,
        "lema_alvarado": "ANUANO",
        "nivel": "B",
        "razon": "Árbol indeterminado de Coro y Yaracuy. Sin filtro.  [curación humana]",
    },
    "araguan": {
        "glosa_fuente": "Árbol indeterminado de L^ra y Falcón, cuya madera, de un gris claro, pesada, con líneas de un gris más oscuro a lo largo, es usada en la construcción civil.",
        "identificacion_moderna": "",
        "pagina": 10,
        "lema_alvarado": "ARAGUÁN",
        "nivel": "B",
        "razon": "Árbol maderable de Lara y Falcón. Sin filtro.  [curación humana]",
    },
    "aripino": {
        "glosa_fuente": "Árbol indeterminado de Coro.",
        "identificacion_moderna": "",
        "pagina": 13,
        "lema_alvarado": "ARIPÍNO",
        "nivel": "B",
        "razon": "Árbol indeterminado de Coro. Sin filtro.  [curación humana]",
    },
    "barabara": {
        "glosa_fuente": "C. macrocarpa. Mirsináceas. Árbol de Coro. ''Madera dura y pesada, semejante a la de las especies de Jacquinia; se conoce fácilmente por los grandes radios medulares que son muy notables en la sección",
        "identificacion_moderna": "Clavija ornata",
        "pagina": 21,
        "lema_alvarado": "BARABARA",
        "nivel": "B",
        "razon": "sobrevive a los 6 filtros; localización Coro/Falcón/Paraguaná; campo semántico local",
    },
    "barimiso": {
        "glosa_fuente": "Árbol indeterminado de Lara, Coro y Zulia. El del primero de estos Estados es de ramas sarmentosas, armadas de fuertes púas, y las frutillas que produce son comestibles. Su madera carece de aplicación",
        "identificacion_moderna": "",
        "pagina": 23,
        "lema_alvarado": "BARIMÍSO",
        "nivel": "B",
        "razon": "Árbol indeterminado de Lara, Coro y Zulia. Sin filtro.  [curación humana]",
    },
    "barisigua": {
        "glosa_fuente": "Árbol indeterminado de Coro y Zulia.",
        "identificacion_moderna": "",
        "pagina": 23,
        "lema_alvarado": "BARISÍGUA",
        "nivel": "B",
        "razon": "Árbol indeterminado de Coro y Zulia. Sin filtro.  [curación humana]",
    },
    "boque": {
        "glosa_fuente": "Especie de árbol indeterminado. Coro.",
        "identificacion_moderna": "",
        "pagina": 231,
        "lema_alvarado": "BOQUE",
        "nivel": "B",
        "razon": "Árbol indeterminado de Coro. Sin filtro.  [curación humana]",
    },
    "camare": {
        "glosa_fuente": "Arbusto indeterminado de Coro.",
        "identificacion_moderna": "",
        "pagina": 48,
        "lema_alvarado": "CAMARE",
        "nivel": "B",
        "razon": "Arbusto indeterminado de Coro. Sin filtro.  [curación humana]",
    },
    "camaroa": {
        "glosa_fuente": "Árbol lactescente de Coro, de hojas algo parecidas a las del Papayo.",
        "identificacion_moderna": "",
        "pagina": 48,
        "lema_alvarado": "CAMARÓA",
        "nivel": "B",
        "razon": "sobrevive a los 6 filtros; localización Coro/Falcón/Paraguaná; campo semántico local",
    },
    "chaguanco": {
        "glosa_fuente": "Zorro. Voz usada en Coro. AGUARÁ CPI",
        "identificacion_moderna": "",
        "pagina": 112,
        "lema_alvarado": "CHAGUÁNCO",
        "nivel": "B",
        "razon": "sobrevive a los 6 filtros; localización Coro/Falcón/Paraguaná; campo semántico local",
    },
    "chiguare": {
        "glosa_fuente": "Árbol indeterminado de Coro. D. t. Chi huáre:. CHIGÜÉ. ''Hambre canina, desenfrenada, insaciable'. (Pie. lo5).",
        "identificacion_moderna": "",
        "pagina": 120,
        "lema_alvarado": "CHIGUÁRE",
        "nivel": "B",
        "razon": "Árbol indeterminado de Coro (var. chihuare). Sin filtro. ⚠ No confundir con el chiriguare (ave carroñera) del lexicón.  [curación humana]",
    },
    "chiriga": {
        "glosa_fuente": "Árbol de construcción. Madera no mui pesa da, de un amarillo claro y de textura algo astillosa. E. Falcón,",
        "identificacion_moderna": "",
        "pagina": 125,
        "lema_alvarado": "CHIRIGA",
        "nivel": "B",
        "razon": "Árbol de construcción del E. Falcón. Sin filtro.  [curación humana]",
    },
    "cuaguaro": {
        "glosa_fuente": "Árbol de madera amarilla o de un ro jizo jaspeado, tal cual nodosa, compacta, astillosa. Haylo en el Est. Falcón.",
        "identificacion_moderna": "",
        "pagina": 97,
        "lema_alvarado": "CUAGUÁRO",
        "nivel": "B",
        "razon": "Árbol maderable del E. Falcón. Sin filtro.  [curación humana]",
    },
    "cumaragua": {
        "glosa_fuente": "Especie de caracol de las costas de Paraguaná.",
        "identificacion_moderna": "",
        "pagina": 102,
        "lema_alvarado": "CUMARAGUA",
        "nivel": "B",
        "razon": "Única voz del glosario localizada en PARAGUANÁ. Campo semántico local (fauna marina). ⚠ CONFLICTO DE GLOSA con el lexicón: ver identificacion_moderna.  [curación humana]",
    },
    "cusuca": {
        "glosa_fuente": "Árbol frutal silvestre de Coro.",
        "identificacion_moderna": "",
        "pagina": 110,
        "lema_alvarado": "CUSÚCA",
        "nivel": "B",
        "razon": "Árbol frutal silvestre de Coro. Indeterminado. Sin filtro.  [curación humana]",
    },
    "dacagua": {
        "glosa_fuente": "Árbol de Coro y Barquisimeto, de corteza gris cenicienta cuando seca ; madera compacta, de color amarillento uniforme. Da trozos de 5 a 6 pulgadas de diámetro, con corazón excéntrico a veces.",
        "identificacion_moderna": "",
        "pagina": 130,
        "lema_alvarado": "DACÁGUA",
        "nivel": "B",
        "razon": "sobrevive a los 6 filtros; localización Coro/Falcón/Paraguaná; campo semántico local",
    },
    "guacuaro": {
        "glosa_fuente": "Palo de tinte que se produce en Coro.",
        "identificacion_moderna": "",
        "pagina": 143,
        "lema_alvarado": "GUACUARO",
        "nivel": "B",
        "razon": "Palo de tinte de Coro. Técnica local (tintorería). Sin filtro.  [curación humana]",
    },
    "guaitoco": {
        "glosa_fuente": "Árbol de construcción, de madera amarillenta, algo fibrosa, poco pesada, grano fino. E. Falcón.",
        "identificacion_moderna": "",
        "pagina": 147,
        "lema_alvarado": "GUAITOCO",
        "nivel": "B",
        "razon": "Árbol de construcción del E. Falcón. Sin filtro.  [curación humana]",
    },
    "igui": {
        "glosa_fuente": "Bu m cita buxifolia, Árbol maderable. Paují, Ma la rmo. Coro.",
        "identificacion_moderna": "",
        "pagina": 175,
        "lema_alvarado": "IGÜÍ",
        "nivel": "B",
        "razon": "sobrevive a los 6 filtros; localización Coro/Falcón/Paraguaná; campo semántico local",
    },
    "isicagua": {
        "glosa_fuente": "Árbol medicinal de Coro, que cree Ernst pueda ser una especie de Protium.",
        "identificacion_moderna": "",
        "pagina": 176,
        "lema_alvarado": "ISICÁGUA",
        "nivel": "B",
        "razon": "Árbol medicinal de Coro (Ernst conjetura Protium). Sin filtro.  [curación humana]",
    },
    "isiro": {
        "glosa_fuente": "Árbol de construcción de Coro.",
        "identificacion_moderna": "",
        "pagina": 176,
        "lema_alvarado": "ISÍRO",
        "nivel": "B",
        "razon": "sobrevive a los 6 filtros; localización Coro/Falcón/Paraguaná; campo semántico local",
    },
    "lauadri": {
        "glosa_fuente": "Árbol indeterminado del E. Falcón. D. t. Laguadrí.",
        "identificacion_moderna": "",
        "pagina": 184,
        "lema_alvarado": "LAUADRÍ",
        "nivel": "B",
        "razon": "Árbol indeterminado del E. Falcón (var. laguadrí). Sin filtro.  [curación humana]",
    },
    "manata": {
        "glosa_fuente": "Árbol indeterminado de Coro. .",
        "identificacion_moderna": "",
        "pagina": 200,
        "lema_alvarado": "MANÁTA",
        "nivel": "B",
        "razon": "Árbol indeterminado de Coro. Sin filtro.  [curación humana]",
    },
    "mapuare": {
        "glosa_fuente": "Árbol indeterminado de Coro. MAPUÉL Dioscorea trífida. Planta vivaz sarmentosa, voluble, cuya raíz, gruesa y feculenta, blanca o morada, usa — da como ordinaria verdura en el país, lleva el mismo nomb",
        "identificacion_moderna": "",
        "pagina": 207,
        "lema_alvarado": "MAPUARE",
        "nivel": "B",
        "razon": "Árbol indeterminado de Coro. Sin filtro.  [curación humana]",
    },
    "maque": {
        "glosa_fuente": "Esp. de árbol maderable del E. Falcón.",
        "identificacion_moderna": "",
        "pagina": 209,
        "lema_alvarado": "MAQUE",
        "nivel": "B",
        "razon": "Árbol maderable del E. Falcón. Sin filtro.  [curación humana]",
    },
    "orumo": {
        "glosa_fuente": "Myrcia cHcullata. Mirtáceas. 1—En Coro, el 1 AFÁMATE (?). Madera poco densa, fibrosa, pardusca o ama — rillenta matizada, del aspecto de la del pardillo. En Mé || rida, el yagrúmo.",
        "identificacion_moderna": "",
        "pagina": 234,
        "lema_alvarado": "ORÚMO",
        "nivel": "B",
        "razon": "sobrevive a los 6 filtros; localización Coro/Falcón/Paraguaná; campo semántico local; sin taxón en 1921 (no castellanizable)",
    },
    "pirota": {
        "glosa_fuente": "Árbol indeterminado de Coro. PISCA, Borrachera. Us. en la Cord.",
        "identificacion_moderna": "",
        "pagina": 253,
        "lema_alvarado": "PIRÓTA",
        "nivel": "B",
        "razon": "Árbol indeterminado de Coro. Sin filtro.  [curación humana]",
    },
    "ruba": {
        "glosa_fuente": "Especie de abeja silvestre negra de Coro. Véa— se RuBÍTA. 1 Planta de Mérida, y su raíz, que es un tu1 bérculo como la patata. Ref. Pie. 300.",
        "identificacion_moderna": "",
        "pagina": 266,
        "lema_alvarado": "RÚBA",
        "nivel": "B",
        "razon": "sobrevive a los 6 filtros; localización Coro/Falcón/Paraguaná; campo semántico local",
    },
    "sibucaro": {
        "glosa_fuente": "BoMihax sp. Especie át ceiba de Coro. Su corteza, de un color rojizo se emplea en cordelería. D. t. SiBUCÁRA.",
        "identificacion_moderna": "",
        "pagina": 277,
        "lema_alvarado": "SIBUCARO",
        "nivel": "B",
        "razon": "Ceiba de Coro cuya corteza se usa en cordelería: técnica local.  [curación humana]",
    },
    "tocororo": {
        "glosa_fuente": "Tallo leñoso del cirio o cardón. Lara, Falcón.",
        "identificacion_moderna": "",
        "pagina": 292,
        "lema_alvarado": "TOCORÓRO",
        "nivel": "B",
        "razon": "'Tallo leñoso del cirio o cardón' (Lara, Falcón): nombra una parte del cardón, planta central del paisaje caquetío. Sin filtro.  [curación humana]",
    },
    "turupia": {
        "glosa_fuente": "Especie de acacia o cují de Co ro. Cf. Trupillo.",
        "identificacion_moderna": "Acacia sp",
        "pagina": 302,
        "lema_alvarado": "TURÚPIA",
        "nivel": "B",
        "razon": "'Especie de acacia o cují de Coro'. Campo semántico local (flora xerófila), sin filtro.  [curación humana]",
    },
    "urupagua": {
        "glosa_fuente": "Árbol indeterminado de Coro. Fruto elipsoide, cuando seco, de 1^ pulgada de largo con cascara dura y un contenido libre, compacto, harinoso, amarillento.",
        "identificacion_moderna": "",
        "pagina": 305,
        "lema_alvarado": "URUPÁGUA",
        "nivel": "B",
        "razon": "Árbol de Coro, indeterminado en 1921 (la ciencia no supo darle taxón: señal de voz local no castellanizable).  [curación humana]",
    },
    "urupaguita": {
        "glosa_fuente": "Yerba que produce una frutilla amarga. Pasto de cabras. Coro.",
        "identificacion_moderna": "",
        "pagina": 305,
        "lema_alvarado": "URUPAGÜÍTA",
        "nivel": "B",
        "razon": "Diminutivo de urupagua, Coro. Confirma que la raíz es productiva en el habla local.  [curación humana]",
    },
    "yagruma": {
        "glosa_fuente": "En Coro es lo mismo que caracol (mo lusco )",
        "identificacion_moderna": "",
        "pagina": 309,
        "lema_alvarado": "YAGRUMA",
        "nivel": "B",
        "razon": "sobrevive a los 6 filtros; localización Coro/Falcón/Paraguaná; campo semántico local",
    },
}


# ==================================================================
# NIVEL C — plausibles, señal débil
# ==================================================================
CANDIDATOS_C: dict[str, dict] = {
    "bachure": {
        "glosa_fuente": "Maneto, patituerto. Us. en Coro.",
        "identificacion_moderna": "",
        "pagina": 19,
        "lema_alvarado": "BACHURE",
        "nivel": "C",
        "razon": "sobrevive pero señal débil: localización Coro/Falcón/Paraguaná",
    },
    "bariqui": {
        "glosa_fuente": "Especie de planta sarmentosa tintórea de — Occ. D. t. BARQUÍS. 1 Tinte de óxido de hierro, que usaban 1 o usan para pintarse los indios Ayamanes. —",
        "identificacion_moderna": "",
        "pagina": 23,
        "lema_alvarado": "BARIQUÍ",
        "nivel": "C",
        "razon": "Planta tintórea de Occ.; pero Alvarado la asocia al tinte de los indios AYAMANES (jirajaroide) → roza el filtro 6.  [curación humana]",
    },
    "buche": {
        "glosa_fuente": "Pichigüéi, abajo. Voz usada en Occ. *",
        "identificacion_moderna": "Melocactus communis",
        "pagina": 34,
        "lema_alvarado": "BUCHE",
        "nivel": "C",
        "razon": "sobrevive pero señal débil: localización Occ. (amplia); campo semántico local",
    },
    "cacuro": {
        "glosa_fuente": "En Coro significa avispero. .",
        "identificacion_moderna": "",
        "pagina": 40,
        "lema_alvarado": "CACURO",
        "nivel": "C",
        "razon": "sobrevive pero señal débil: localización Coro/Falcón/Paraguaná",
    },
    "camburito": {
        "glosa_fuente": "Especie de orquídea, así nombrada por el olor de su flor a cambur manzano. Portuguesa. [| Cereiis sp. Especie de cirio o cardón poco elevado, cuyo fruto alargado, amarillo, comestible, se asemeja a un",
        "identificacion_moderna": "",
        "pagina": 50,
        "lema_alvarado": "CAMBURÍTO",
        "nivel": "C",
        "razon": "Cactus de las sabanas septentrionales de Coro, pero el lema es un diminutivo romance de 'cambur': formación local moderna, no sustrato.  [curación humana]",
    },
    "canoito": {
        "glosa_fuente": "Árbol de Occ. útil en construcción para vigas y viguetas. Probablemente idéntico al que lleva igual nombre en el Guárico.",
        "identificacion_moderna": "",
        "pagina": 53,
        "lema_alvarado": "CANOÍTO",
        "nivel": "C",
        "razon": "Árbol de Occ. útil en construcción, pero el mismo nombre existe en el Guárico: distribución NO restringida.  [curación humana]",
    },
    "capadare": {
        "glosa_fuente": "Denominación comercial dada a los cigarros elaborados con tabaco de Capadare (E. Falcón). 'Se sentó en un butaque y prendió un capadare'. (Cabrera M., Mimí, 61).",
        "identificacion_moderna": "",
        "pagina": 54,
        "lema_alvarado": "CAPADÁRE",
        "nivel": "C",
        "razon": "Es un topónimo de Falcón usado como marca comercial de tabaco, no una voz del habla. Valor de canon toponímico, no léxico.  [curación humana]",
    },
    "caquetillo": {
        "glosa_fuente": "Árbol de construcción del Zulia. ¿Voz afín de caquetío?",
        "identificacion_moderna": "",
        "pagina": 56,
        "lema_alvarado": "CAQUETILLO",
        "nivel": "C",
        "razon": "'Árbol de construcción del Zulia. ¿Voz afín de caquetío?' — la pregunta es del propio Alvarado, y queda sin responder. Se registra por su interés etnonímico, no como voz del habla.  [curación humana]",
    },
    "guaraba": {
        "glosa_fuente": "Brownca Guaraba Pittier. Leguminosas. Árbol de unos 8 m. de alto, ramoso, de tronco cilindrico ; ho jas alternas, paripinadas, con 5 a 3 pares de hojuelas pecio-^ ladas, enteras, coriáceas, abarquilla",
        "identificacion_moderna": "",
        "pagina": 154,
        "lema_alvarado": "GUARÁBA",
        "nivel": "C",
        "razon": "Brownea guaraba Pittier, 'Occidente'. Sobrevive a los 6 filtros pero la única señal es la amplia (Occ.), sin anclaje coriano.  [curación humana]",
    },
    "ipunano": {
        "glosa_fuente": "Alfarda. Us. en Coro, Barcelona.",
        "identificacion_moderna": "",
        "pagina": 175,
        "lema_alvarado": "IPUNANO",
        "nivel": "C",
        "razon": "'Alfarda', usada en Coro y Barcelona. La coocurrencia con Barcelona (oriente caribe) debilita la atribución local.  [curación humana]",
    },
    "pororo": {
        "glosa_fuente": "de fruto comesti— ble. Crece en Occ. Quizá una Esterculiácea.",
        "identificacion_moderna": "Árbol indeterminado",
        "pagina": 124,
        "lema_alvarado": "PORORÓ",
        "nivel": "C",
        "razon": "Árbol de fruto comestible de Occ., sin más precisión.  [curación humana]",
    },
    "sibidigua": {
        "glosa_fuente": "Túatúa. Voz us. en Lara y Falcón.",
        "identificacion_moderna": "Jatropha gossypifolia",
        "pagina": 277,
        "lema_alvarado": "SIBIDÍGUA",
        "nivel": "C",
        "razon": "sobrevive pero señal débil: localización Coro/Falcón/Paraguaná",
    },
    "surupa": {
        "glosa_fuente": "Corredera, curiana. Sú rrttja en guajibo es cucaréicha; debe ser corrupción de su RÚPV, que a su vez parece tener la misma raíz que chi RÍPA (q. V.)",
        "identificacion_moderna": "Blatta orientalis",
        "pagina": 279,
        "lema_alvarado": "SURÚPA",
        "nivel": "C",
        "razon": "Blatta orientalis (cucaracha). Alvarado la compara con el guajibo *cucaréicha* y con CHIRÍPA; la señal es de familia, no local. ⚠ En esta entrada 'curiana' aparece como palabra ESPAÑOLA para cucaracha.  [curación humana]",
    },
}


# ==================================================================
# DESCARTES RAZONADOS — nivel D
# ==================================================================
# Documentar el descarte vale tanto como el hallazgo: evita que alguien
# re-mine la misma voz dentro de seis meses.
DESCARTES: dict[str, dict] = {
    "adorote": {"pagina": 3, "glosa_fuente": "Embalaje redondo o cuadrangular, hecho de mimbre y cordeles, para trasportar diversos objetos. 'Enjutas y secas ya cabez", "razon": "F6: documentado por Carvajal en el Apure; 'Us. en Occ.' es difusión, no origen.  [curación humana]"},
    "auyama": {"pagina": 16, "glosa_fuente": "Cucúrbita sp. pl. Calabacera bien conocida y el fruto que produce. 'Descubrimos auyamas y frísoles, | razonable manjar a", "razon": "F4/F6: Alvarado la marca 'Voz cum.' (cumanagota, familia caribe) y cita a Ruiz Blanco. Además es panvenezolana.  [curación humana]"},
    "bobo": {"pagina": 145, "glosa_fuente": "GuACHiTO. Cod. 118; guacito Humboldt, Viaje II. 6; Cod. I09. No sabemos cuál será lo mejor. GUÁL Bombax sp. Ceiba. Voz u", "razon": "artefacto de parseo (la entrada arrastra GUÁL/GUACHITO); no evaluable.  [curación humana]"},
    "butaque": {"pagina": 35, "glosa_fuente": "Asiento pequeño, usado por la gente pobre del país, a modo de un catrecillo, con el forro de madera o de cuero más o men", "razon": "F6: el equivalente occidental del ture chaima; voz de circulación nacional.  [curación humana]"},
    "cachipo": {"pagina": 43, "glosa_fuente": "Heliconia Bihai. Bijao, arriba. Ref. Gilii, — En I. 18o. 1 -Pecíolo- de la hoja seca y caduca del banano. — 1 arec. kasi", "razon": "F6: 'arec. kasipa' en la propia entrada; la acepción coriana ('colérico') es un uso secundario, no el origen.  [curación humana]"},
    "caimoni": {"pagina": 46, "glosa_fuente": "Planta herbá cea de ramos anguloso-estriados, algo tomentosos; hojas aovadas, acuminadas, casi enteras, algo crasas, esc", "razon": "F1: la entrada no localiza en Falcón; falso positivo del regex.  [curación humana]"},
    "camuro": {"pagina": 51, "glosa_fuente": "Camasa, arriba. La planta, el fruto y la vasija con éste aderezada tienen igual nombre en el Zulia. Del guajiro amuru, á", "razon": "F3: 'Del guajiro amuru, árbol de las calabazas' (A. Rojas).  [curación humana]"},
    "capucero": {"pagina": 56, "glosa_fuente": "Epíteto dado en Occ. a los federalistas en 1858, porque los primeros rebeldes fueron campesinos armados de flechas o cap", "razon": "F1: epíteto político venezolano de 1858, formación romance moderna.  [curación humana]"},
    "carebe": {"pagina": 62, "glosa_fuente": "de forma oval, a la que sirve de mango la parte más angosta del óvalo. Fabrícala del fruto del totumo y úsala en Occiden", "razon": "F6: el propio Alvarado dice que es 'voz tomada de algún dialecto andino' (cf. guagibo kariepa) y que en Oriente se desconoce.  [curación humana]"},
    "caucho": {"pagina": 73, "glosa_fuente": "Árbol del Alto Orinoco que produce la goma elástica. El género cons tituye árboles diversos con ramas follosas en el ápi", "razon": "F4: voz amazónica de circulación panamericana; la entrada no toca Coro (falso positivo del regex por 'Occ.').  [curación humana]"},
    "cayapa": {"pagina": 74, "glosa_fuente": "Concierto de obreros o peones para ejecutar — un trabajo particular sin recibir por él salario, sino sólo la comida. 'Al", "razon": "descartada por F6_caribe_jirajaroide"},
    "chapapote": {"pagina": 113, "glosa_fuente": "Asfalto. 'También ay chapapote en la Costa de Coro'. (Cisn. 23). Del azt. chapápotl. Ref. Bachi— ller, Cuba prim. 243. 1", "razon": "F4: 'Del azt. chapápotl' — nahuatlismo, pese a citarse en la Costa de Coro.  [curación humana]"},
    "chimbanquele": {"pagina": 121, "glosa_fuente": "Baile popular de Coro en honor de S. Benito, mencionado en la lei de policía provincial. También ha existido en el Zulia", "razon": "F5: baile afrodescendiente en honor de S. Benito (Coro y Zulia). Es cultura colonial afro, no sustrato indígena.  [curación humana]"},
    "chimbique": {"pagina": 122, "glosa_fuente": "Véase chimbánouELE. Voz usada en Coro. CHIM", "razon": "F5: variante de chimbánguele; mismo descarte.  [curación humana]"},
    "chimo": {"pagina": 122, "glosa_fuente": "Extracto Ijlando de tabaco alcalinizado y aroma,tizado. El álcali escogido es el urao (sesquicarbonato de sosa), o el bi", "razon": "F1/F6: producto andino-venezolano; el urao remite a Mérida, no a Coro.  [curación humana]"},
    "chirgua": {"pagina": 125, "glosa_fuente": "esférica u oblonga, de go llete corto y estrecho, destinada a trasportar agua. Usábanla los indios Guamos, según Gihi {E", "razon": "F6: 'Usábanla los indios Guamos' y 'en sáliba chírua'.  [curación humana]"},
    "choi": {"pagina": 128, "glosa_fuente": "Párvulo, niño de pecho. Lis. en Mérida. Ref, Pie. 134. CHOLA, Monacanthus occidenfalis. ( ?) Pez plectogna— to de la fam", "razon": "F1: 'Us. en Mérida' — andina, no coriana (falso positivo por 'Occidente' en la entrada contigua CHOLA).  [curación humana]"},
    "chorote": {"pagina": 129, "glosa_fuente": "Pequeño cazo de barro donde se cuece el — cacao tostado y molido para mezclarlo con agua. 1 Infusión 1 de cacao tostado ", "razon": "F1: voz de circulación nacional; la mención de Occidente es de difusión ('cerrero en Occidente'), no de origen.  [curación humana]"},
    "cipero": {"pagina": 80, "glosa_fuente": "Poso, heces, asiento, bagazo. ''PÍnía en el suelo, sujetándola con una piedra, la totuma llena de café donde flotaba el ", "razon": "F1: la entrada no localiza en Falcón; falso positivo del regex.  [curación humana]"},
    "cipote": {"pagina": 80, "glosa_fuente": "Arma de indios mencionada por Oviedo. Chi póte era, según Gagini, una especie de cachiporra usada por los indios de Nica", "razon": "F1/F4: Alvarado la compara con el chipote nicaragüense (Gagini); circulación centroamericana.  [curación humana]"},
    "cobalonga": {"pagina": 81, "glosa_fuente": "Fruta de sabor picante y aromático, proveniente de varias lauríneas de Occidente y la Cordillera, O V. g. la c otea Pich", "razon": "F4: nuez de lauríneas amazónicas (Licaria/Ocotea), de circulación comercial por arriería; 'Occidente y la Cordillera' es difusión.  [curación humana]"},
    "conuco": {"pagina": 89, "glosa_fuente": "Sementera, labranza. 'Esta labranza, en lenguaje de los indios desta isla, se llama conuco, la penúl tima luenga'. (Cas.", "razon": "F4: 'Voz taina' explícita (Las Casas). Es el étimo del kunuku del lexicón, vía español.  [curación humana]"},
    "cujisal": {"pagina": 101, "glosa_fuente": "Ver Cujiáe. '(Se les escapaban) hacia el coquetón cementerio blanco y verde, paramentado de rojo cuando florece el cujis", "razon": "F1: colectivo romance en -al sobre 'cují'.  [curación humana]"},
    "curiara": {"pagina": 107, "glosa_fuente": "Embarcación enteriza, pequeña, ligera, menor que la canoa, mui usada en la navegación fluvial. 'Se hallaban los buenos P", "razon": "F6: 'Voz de origen caribe' (kuliála / kuriara / kuliára).  [curación humana]"},
    "dibibe": {"pagina": 132, "glosa_fuente": "Hacho. Voz ayamán o gayón, us. en Lara.", "razon": "F6: 'Voz ayamán o gayón' — jirajaroide, no arahuaco.  [curación humana]"},
    "dispopo": {"pagina": 132, "glosa_fuente": "Fibra extraída de una variedad de eoeúi (Agave sp.) de Barquisimeto, usada en cordelería. Créese que es voz ayamán-gayón", "razon": "F6: 'Créese que es voz ayamán-gayón'.  [curación humana]"},
    "dividive": {"pagina": 132, "glosa_fuente": "Leguminosas. Árbol que se alza a 3o ó 4o y más pies, inerme, ramoso, corto de tronco, asaz corpulento (24 a 3o pulgadas ", "razon": "F4: nombre panvenezolano/pancaribeño de Caesalpinia coriaria; Alvarado registra además 'Guatapaná, en Cuba'.  [curación humana]"},
    "duro": {"pagina": 133, "glosa_fuente": "En el Occ. es un zoquete de madera que se usa — como asiento entre la clase proletaria. D. t. dure en otros lugares. -''", "razon": "F6: Alvarado lo identifica con el 'dure de los Caribes' (Carvajal).  [curación humana]"},
    "garitear": {"pagina": 66, "glosa_fuente": "Pescar carite:s en la época en que estos peces frecuentan sus sitios favoritos. Voz de pescadores. 'Esta madrugaíta esta", "razon": "F1: verbo romance derivado de 'carite'.  [curación humana]"},
    "guaca": {"pagina": 139, "glosa_fuente": "pl. Guacamaya. ''Las gua cas se detuvieron indecisas, luego batieron presurosas las alas y cambiaron de rumbo'. (Urbanej", "razon": "F4: 'Voz taina' en la acepción de tesoro escondido.  [curación humana]"},
    "guacoa": {"pagina": 143, "glosa_fuente": "Columba corcnsis y C. speciosa. Especies de paloma de Coro y el Zulia. Este nombre corresponde sin duda al de Bacóa, nom", "razon": "F6: del calínago 'uahikua', cum. 'huakúa', ch. 'guakúa'.  [curación humana]"},
    "guagua": {"pagina": 261, "glosa_fuente": "Especie de haba de Coro, grande y blanca. Cf. Caráota chivata.", "razon": "F4: 'guagua' es voz quechua/antillana de amplísima difusión; la acepción de haba coriana no basta.  [curación humana]"},
    "guairon": {"pagina": 147, "glosa_fuente": "Us. en Occ.", "razon": "F1: aumentativo romance de 'guaira'.  [curación humana]"},
    "guarear": {"pagina": 157, "glosa_fuente": "Atalayar animales dañinos desde un sobra do o troje, levantado en un sitio conveniente de un sembrado, para ahuyentarlos", "razon": "F1: verbo romance derivado de 'guaro'.  [curación humana]"},
    "guaro": {"pagina": 159, "glosa_fuente": "Psitfacus Acamil. Especie de cotorra del Zu lia. Designando al loro en general, se usa la voz en el Or. del país y en Ca", "razon": "F6: Alvarado dice explícitamente que la voz NO se usa en Occ. ('uarro es loro en carúsana').  [curación humana]"},
    "guatapanar": {"pagina": 163, "glosa_fuente": "Dividive:. Del cum. aragiiatapanár, oreja de araguato, por la forma del fru to, sin duda. Entre los Guayuncomos del Alto", "razon": "F6: Alvarado deriva la forma del cum. 'araguatapanár' (oreja de araguato). Es la voz que el lexicón registra como watapana.  [curación humana]"},
    "hamaca": {"pagina": 171, "glosa_fuente": "Coi o lecho colgante tejido con hilo de algodón a trama cerrada o con telas gruesas apropiadas. **Bien es que se diga qu", "razon": "F4: antillanismo panamericano; Alvarado discute taíno vs. caribe y señala que fue aceptada 'en todos los idiomas civilizados'.  [curación humana]"},
    "hicaquito": {"pagina": 172, "glosa_fuente": "Dim, de hicaco. Licania incana. || Rosáceas. Árbol silvestre que se eleva a 40 ó 50 pies, de tron co largo, derecho, gru", "razon": "F1: diminutivo romance de 'hicaco' (antillanismo).  [curación humana]"},
    "jirajara": {"pagina": 181, "glosa_fuente": "Especie de hormiga brava. Alusión a los indios Jirajaras, que fueron muí temidos por los colonizado res del Occidente de", "razon": "descartada por F6_caribe_jirajaroide"},
    "manare": {"pagina": 199, "glosa_fuente": "Harnero, cedazo, tamiz, hecho de tiras de caña entretejidas y destinado a cerner harina de yuca y otros usos. 'El común ", "razon": "F6: voz de circulación nacional documentada por Caulín en misiones caribes; no hay anclaje coriano.  [curación humana]"},
    "maruto": {"pagina": 213, "glosa_fuente": "Us. en el Alto — Llano. II Verruga, verdugón, roncha, pápula. Aragua. || Árbol maderable indeterminado. Coro.", "razon": "F1/F4: acepciones dispersas (Alto Llano, Aragua, Coro) sin unidad; distribución no restringida.  [curación humana]"},
    "mojanazo": {"pagina": 222, "glosa_fuente": "Maleficio, brujería, sortilegio, mal de ojo. 'Esta superstición aun se encuentra entre el pueblo bajo de las ciudades de", "razon": "F6/F1: derivado romance de *mohán*, voz andina; la localización en Occidente es de uso, no de origen.  [curación humana]"},
    "mulato": {"pagina": 202, "glosa_fuente": "|| negro. Avicennia nítida, A. tomentosa. Verbenáceas. Arboles peque ños del litoral, con ramos derechos, cuadrangulares", "razon": "F1: voz romance; la entrada es un fitónimo descriptivo.  [curación humana]"},
    "nopal": {"pagina": 228, "glosa_fuente": "Opunfia Ficus indica. Cactáceas. *'E1 árbol o más propiamente cardo, que lleva esta fruta nuchtli se lla— ma entre los i", "razon": "F4: 'Del azt. nopal' (Gómara); la mención de Coro es descriptiva.  [curación humana]"},
    "parcpta": {"pagina": 239, "glosa_fuente": "pl. Pasionaria. Genero de plantas herbáceas o subf rutescentes, «tle tallo trepador provis to de zarcillos; flores solit", "razon": "OCR corrupto de PARCHITA; voz de circulación nacional.  [curación humana]"},
    "pauji": {"pagina": 242, "glosa_fuente": "Crax sp. pl. Aves pertenecientes a la fam. de las Penelópidas, de pico fuerte, comprimido, convexo; anchas fosas nasales", "razon": "F6: Alvarado deriva el fitónimo del chaima. Además la glosa es un ÁRBOL (Bumelia buxifolia), no un ave.  [curación humana]"},
    "piache": {"pagina": 248, "glosa_fuente": "Sacerdote indígena, que, según los casos, era al mismo tiempo brujo, hechicero o herbolario. 'Usaban de médicos que los ", "razon": "F6: 'Voz cháima y tamanaca, con formas afines en otras lenguas caribes'. NO es arahuaca.  [curación humana]"},
    "piritu": {"pagina": 253, "glosa_fuente": "Bactris Piritu. Pequeña palmera, alta de 5 a 7 m., de tallo recto, delgado, cilindrico, con cicatrices peciolares de tre", "razon": "F6: 'En car. piritu, en cum. piríchu, lo mismo'. Crece en Lara, Coro y Yaracuy, pero la voz es caribe. ⚠ El lexicón la tiene como `caquetío` (vía Zavala #—, sigla A): candidata a reetiquetar en F1.  [curación humana]"},
    "purupuru": {"pagina": 259, "glosa_fuente": "Especie de gramínea mui crecida, cuyo tallo componen largos y gruesos internodios huecos. Crece en las montañas de Occ. ", "razon": "F4: Alvarado la compara con el piripiri peruano; además crece en montañas de Occ. y Carabobo — distribución no restringida.  [curación humana]"},
    "supe": {"pagina": 279, "glosa_fuente": "aderezada con salsa, para co merla a guisa de cena. Us. en Occidente. En el Perú y Chile llámanla chupe, voz quichua, qu", "razon": "descartada por F4_taino_panamericano"},
    "tamunango": {"pagina": 283, "glosa_fuente": "Baile de negros en Coro, en honor de Sah Antonio.", "razon": "F5: 'Baile de negros en Coro, en honor de San Antonio'.  [curación humana]"},
    "tequiara": {"pagina": 288, "glosa_fuente": "Corona o turbante de estambre que usan los indios Guagiros. Del guajiro tekiara, lo mismo. —", "razon": "F3: 'Del guajiro tekiara, lo mismo'.  [curación humana]"},
    "tococo": {"pagina": 292, "glosa_fuente": "'Pájaro grande que habita las costas del mar. La envergadura de sus alas es de casi 9 pies. Se balancea ligeramente en e", "razon": "F1: pelícano, voz de circulación costera nacional (Codazzi).  [curación humana]"},
    "tuque": {"pagina": 300, "glosa_fuente": "Árbol mui cor pulento que crece en los cerros de Carabobo, Cojedes, Lara, Falcón. Madera dura, más o menos pesada, poco ", "razon": "F1: crece en Carabobo, Cojedes, Lara y Falcón — distribución amplia.  [curación humana]"},
    "tura": {"pagina": 301, "glosa_fuente": "Especie de bambú de artículos largos, cilin dricos, huecos. E. Lara. Cf . Purupúru. Baile de tura. | | Baile indígena. *", "razon": "F6: el baile de Tura es de tradición ayamán/gayón (Churuguara, Falcón), jirajaroide. Localización correcta, filiación equivocada.  [curación humana]"},
    "ture": {"pagina": 301, "glosa_fuente": "Asiento pequeño de forma particular. Us. en Cumaná y Margarita. Es lo mismo que el butaque de Occidente. Voz cháima, que", "razon": "F6: 'Voz cháima' (Tauste), usada en Cumaná y Margarita — oriente caribe, no Coro. Además la glosa es 'asiento pequeño', no 'vasija'.  [curación humana]"},
    "turpial": {"pagina": 302, "glosa_fuente": "pl. Pájaros dentirrostros cuyo plumaje está exornado principalmente de amarillo y negro. En la especie oridnaria la cabe", "razon": "descartada por F6_caribe_jirajaroide"},
}


# ==================================================================
# F1 — AUDITORÍA DE LAS 82 ENTRADAS DE FAMILIA CAQUETÍA SIN CITA
# ==================================================================
# veredicto ∈ {confirma, reclasifica, no-concluyente}
AUDITORIA_82: dict[str, dict] = {
    "amaca": {
        "aparece": "lema",
        "pagina": 171,
        "forma_alvarado": 'HAMACA',
        "cita": "Coi o lecho colgante tejido con hilo de algodón a trama cerrada o con telas gruesas apropiadas. **Bien es que se diga qué camas tienen los indios en esta Isla Espa ñola, a la qual cama llaman hamaca'. (Ov. I, 131). 'La pa labra, dice Diez, también se halla en el caribe, y debe, s",
        "veredicto": "no-concluyente",
        "razon": "Solo aparece como variante de *hamaca* (antillanismo). No hay rastro de la glosa del lexicón ('sitio de moler maíz').",
    },
    "apana": {
        "aparece": "lema",
        "pagina": 229,
        "forma_alvarado": 'ÑAPA',
        "cita": "Adehala. 'Gaje o regalía, premio o percana que dan los venteros a los que han comprado algo'. (Carmona). Del quichua y apana, añadidura. En quichua moderno yapa es algo que se da sobre lo que se debe. Dn. Daniel Granada considera vulgarísima la forma ñapa {Vocabul. rioplaf., p. 2",
        "veredicto": "no-concluyente",
        "razon": "Solo aparece como quichua *apana* 'añadidura' (étimo de ñapa). Homógrafo: nada que ver con 'una luna'.",
    },
    "ateri": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "auyama": {
        "aparece": "lema",
        "pagina": 16,
        "forma_alvarado": 'AUYAMA',
        "cita": "Cucúrbita sp. pl. Calabacera bien conocida y el fruto que produce. 'Descubrimos auyamas y frísoles, | razonable manjar aunque liviano'. (Cast. Cabo de la Vela, oct. 80: Véase también Blog. de Rojas, 4?). Voz cum. que Ruiz Blanco traslada 'calabaza'. Agyama, que hallamos en la Rel",
        "veredicto": "reclasifica",
        "razon": "'Voz cum.' (cumanagota) según Ruiz Blanco, con variantes ayuyáma / huyáma. Familia CARIBE, no arahuaca: la etiqueta `caquetío-atestiguado` es errónea.",
    },
    "bajarí": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "barici": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "bariki": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "borojo": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "buco": {
        "aparece": "lema",
        "pagina": 34,
        "forma_alvarado": 'BUCO',
        "cita": "Caz, acequia. Voz antigua. En el resumen de — las actas del cabildo de Caracas, para julio de 1592, se lee, entre otros pasajes : 'Asi mismo mandaron se le notifique a Francisco Sánchez de Córdoba, que el agua del buco la haga repartir, para que baya por todas las asequias, pena ",
        "veredicto": "confirma",
        "razon": "'Caz, acequia' — la glosa del lexicón ('represa, canal') es compatible. ⚠ Alvarado la localiza en Lara y sugiere origen romance ('¿del ant. buca, boca?'): confirma la glosa, DUDA de la filiación.",
    },
    "buiamati": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "buko": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "bureche": {
        "aparece": "lema",
        "pagina": 34,
        "forma_alvarado": 'BURECHE',
        "cita": "Bebida fermentada que preparan los indios guayaneses poniendo por cierto tiempo en agua caliente — el casabe. [—'Aguardiente de caña sacado por los indios, | mui dulce y de olor algo desagradable'. (Montolieu). 'Se hallaban todos entilampados. con el yaraque, con el bure| che'. (",
        "veredicto": "reclasifica",
        "razon": "CONFLICTO DE GLOSA (D7): en Alvarado es una BEBIDA fermentada de los indios guayaneses; el lexicón lo registra como verbo 'hacer, fabricar'. La glosa de bebida coincide en cambio con *buriche* del propio lexicón.",
    },
    "buriche": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "cachicamo": {
        "aparece": "lema",
        "pagina": 41,
        "forma_alvarado": 'CACHICAMO',
        "cita": "Edentados de la fam. de los Dasipó didos, género Dásypus, cuya cubierta dérmica consta de pla cas óseas dispuestas en filas trasversas sobre el dorso y cola, formando una coraza movible; extremidades cortas, con garras arqueadas ; muelas pequeñas, cilindricas. Abundan en las saba",
        "veredicto": "confirma",
        "razon": "Glosa idéntica (Dasypus). Voz de circulación nacional, sin origen declarado: confirma la glosa, no la filiación.",
    },
    "caduchi": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "caraota": {
        "aparece": "lema",
        "pagina": 58,
        "forma_alvarado": 'CARAOTA',
        "cita": "Nombre dado corrientemente a varias cla ses de judías, habas o habichuelas producidas por plantas volubles de los géneros Phaseolus, Canavalia y Pachyrrhizus, fam. de la Leguminosas. Se conocen muchas especies en el co mercio, tales como la caráota blanca {Ph. linearis) : la c. n",
        "veredicto": "reclasifica",
        "razon": "Alvarado la describe como nombre corriente panvenezolano de las judías, sin origen indígena declarado. Filtro 4: no prueba nada local.",
    },
    "cari": {
        "aparece": "mención",
        "pagina": 65,
        "forma_alvarado": None,
        "cita": "icarito, — abajo. 1 Son y cantar populares. 1 CARICÁRL Polyborus ^ulgaris. Caricare. Ref. Cod. I90. CARI [65] CARITO. Bursera sp. Especie de árbol no bien determinado, de madera blandísima. 1 Hedwigia balsami1 fera. Burseráceas. Árbol de hojas alternaos, compu",
        "veredicto": "no-concluyente",
        "razon": "No es lema; solo aparecen CARICARE, CARITE, CARITIVÁ. Sin evidencia.",
    },
    "catarí": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "cati": {
        "aparece": "mención",
        "pagina": 168,
        "forma_alvarado": None,
        "cita": "como sinónimo de Yaraque, está en uso todavía. Ref. Carv. 349. [168] GUICHERE. Pithecolohkim Unguis Cati. Leguminosas. Arbusto de lo a 15 pies de alto, armado de estípulas espinosas diminutas, o a veces inerme y lampiño; hojas uniyugas con un par de hojuelas o",
        "veredicto": "no-concluyente",
        "razon": "Único hit es el latín 'Unguis Cati' en un nombre científico. Sin evidencia.",
    },
    "cazebo": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "cazi": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "cazicure": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "cazá": {
        "aparece": "mención",
        "pagina": 97,
        "forma_alvarado": None,
        "cita": "ncima. Es en extremo ponzoñosa, y sobre manera ágil cuando se irrita. Como otras especies análogas, caza por la noche. Habita en la Guayana. 'Su tamaño alcan za hasta tres varas, es de piel leonada con pintas blancas, cola de color más vivo que termina en una",
        "veredicto": "no-concluyente",
        "razon": "Los hits son la palabra española 'caza'. Sin evidencia.",
    },
    "chacamba": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "chiriguare": {
        "aparece": "mención",
        "pagina": 126,
        "forma_alvarado": None,
        "cita": "al necesitado que anda en busca de él'. (Med. 46).. Sin. Francisquito. || Después que samuro come, chiriguare roe: alusión al hábito del cliiríguarc de roer los huesos de las carroñas. Cf. Cari [126] CHIRIMORRIÑÓN. Anona sp. Variedad de chirimoya semejante al",
        "veredicto": "no-concluyente",
        "razon": "No es lema, pero aparece dos veces en refranes ('Después que samuro come, chiriguare roe'), lo que CONFIRMA la glosa de ave carroñera. Sin origen ni localización: no adjudica la filiación.",
    },
    "chogogo": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE. Igual que kadushi: forma papiamenta.",
    },
    "chuchubi": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE. Igual que kadushi: forma papiamenta.",
    },
    "corie": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "coro": {
        "aparece": "mención",
        "pagina": 3,
        "forma_alvarado": None,
        "cita": "parecida a la del acó. (Ref. Gros. II, 383). Cf. mucurutú. — [3] ACHICHIVE. Árbol indeterminado de Coro. * [3] ACHIOTE. Bixa Orellana. Onóto. 'Qué arvejones aquellos tan gustosos, ahogados en manteca derretida juntamente con el rojizo achiote en la cazuela'.",
        "veredicto": "no-concluyente",
        "razon": "'Coro' aparece 55 veces, siempre como TOPÓNIMO. No hay lema CORO con la glosa 'cardón' que le da el lexicón.",
    },
    "cudan": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "cudanga": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "cumaragua": {
        "aparece": "lema",
        "pagina": 102,
        "forma_alvarado": 'CUMARAGUA',
        "cita": "Especie de caracol de las costas de Paraguaná.",
        "veredicto": "reclasifica",
        "razon": "CONFLICTO DE GLOSA (D7): Alvarado = 'especie de caracol de las costas de Paraguaná'; el lexicón = 'ciruela, Spondias mombin'. La localización es la mejor de todo el glosario, pero la glosa del lexicón no se sostiene.",
    },
    "curiana": {
        "aparece": "mención",
        "pagina": 279,
        "forma_alvarado": None,
        "cita": "azar. 1 En Marida llaman así una es1 pecie de lechuza. [279] SURÚPA. Blatta orientalis. Corredera, curiana. Sú rrttja en guajibo es cucaréicha; debe ser corrupción de su RÚPV, que a su vez parece tener la misma raíz que chi RÍPA (q. V.) [279] SURÚRE. Planta i",
        "veredicto": "no-concluyente",
        "razon": "No es lema. Aparece UNA vez, y como palabra ESPAÑOLA para cucaracha (s.v. SURÚPA). El topónimo Curiana no está en el glosario.",
    },
    "cuté": {
        "aparece": "lema",
        "pagina": 110,
        "forma_alvarado": 'CUTÉ',
        "cita": "Véase Carári-:.",
        "veredicto": "no-concluyente",
        "razon": "El lema existe (p.110) pero solo remite a CARATE (enfermedad de la piel). Homógrafo: no dice nada sobre el pronombre dativo del lexicón.",
    },
    "dare": {
        "aparece": "mención",
        "pagina": 182,
        "forma_alvarado": None,
        "cita": "á. D. t. jujÓTo. || Arepa de jojoto, HALiyAQUiTA de JOJOTO : torta de ese mastelillo, cocida al bu— dare; o bollo del mismo, cocido en agua Con humo no sE 1 1 ASAN jojotos. No se tomó a Zamora en una hora. 'Se imagina usted (dispénseme lo vulgar del símil en g",
        "veredicto": "no-concluyente",
        "razon": "Único hit dentro de 'budare'. Sin evidencia.",
    },
    "datihao": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "duraboa": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "eroa": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "garabal": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "gua": {
        "aparece": "mención",
        "pagina": 81,
        "forma_alvarado": None,
        "cita": "COCA. Cicada grossa. 'Cigarra grande de canto muí pronunciado'. (Gorrochotegui). Hállase en Aragua, Guá— rico, etc. 'La virgen espesura, y donde cantan las cocas mis| teriosas'. (Id. Aramare, VII). 'El canto de las chicharras bajo los mustios cuj Ízales y a la",
        "veredicto": "no-concluyente",
        "razon": "Solo aparece dentro de compuestos (guaca, guacamaya…). Sin evidencia.",
    },
    "guaitiao": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "guanepe": {
        "aparece": "lema",
        "pagina": 152,
        "forma_alvarado": 'GUANEPE',
        "cita": "Asi llaman en Barcelona y Guayana una especie de cabestrillo o charpa en que las madres indígenas — — llevan sus niños de pecho cuando viajan. En los pasajes siguientes parece tener una acepción algo distinta. 'El saHó — para el pueblo con sus guanopes de pájaros'. (C. Peraza, Le",
        "veredicto": "reclasifica",
        "razon": "Confirma la glosa ('cabestrillo en que las madres llevan sus niños') pero la localiza en BARCELONA y GUAYANA — oriente caribe, no Coro. La atribución caquetía pierde su base geográfica.",
    },
    "gudamuen": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "güere": {
        "aparece": "mención",
        "pagina": 194,
        "forma_alvarado": None,
        "cita": "madura a los 70 días. Cultívasele en el E. Anzoátegui. Sin duda proveniente de las riberas del río Güere, en el mismo Estado. || paieón. Maíz alto, de mazorca grande, con hojas de envoltura, (hojas de maiz) teñidas de morado. Coséchase en climas cálidos a los",
        "veredicto": "no-concluyente",
        "razon": "Único hit: el río Güere del E. Anzoátegui — topónimo oriental. Sin evidencia para la glosa 'dar, entregar'.",
    },
    "güique": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "humocaro": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "iero": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "jacuque": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "jacura": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "jaguey": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "jai": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "kadushi": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario, y también su equivalente castellano no aparece como lema. Consistente con un origen papiamento (islas ABC) → F2, no con un caquetío de tierra firme documentado en 1921.",
    },
    "kama": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "koke": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "kukuisa": {
        "aparece": "lema",
        "pagina": 84,
        "forma_alvarado": 'COCUIZA',
        "cita": "Especies de Poureróya, fam. de las Amarilidáceas, de cuyas hojas, semejantes a las de la agave, se extrae la fibra textil llan;iada también cocuiza. Se conocen varias especies, por ejemplo. P. gigantea, F. euhcnsis, F. vivípara, F. geiuinispi'ña (esta última de Barquisimeto). La ",
        "veredicto": "reclasifica",
        "razon": "La forma venezolana atestiguada es COCUIZA (Furcraea spp.), de circulación nacional. Peor aún: Alvarado cita a Caulín (I.3) — 'una especie de pita que los indios llaman CARUATA y los españoles COCUIZA' (voz chaima; tam. karuatá, cum. karúata). Es decir, *cocuiza* es el nombre del lado ESPAÑOL. *kukuisa* es su forma papiamenta.",
    },
    "kunuku": {
        "aparece": "lema",
        "pagina": 89,
        "forma_alvarado": 'CONUCO',
        "cita": "Sementera, labranza. 'Esta labranza, en lenguaje de los indios desta isla, se llama conuco, la penúl tima luenga'. (Cas. V. 3o7). Dice Humboldt que es una 'ca bana cercada de tierras cultivadas'. (Viaje, VII. 23) ; pero en general la idea dominante son éstas, y no aquella. Voz ta",
        "veredicto": "reclasifica",
        "razon": "Alvarado: 'Voz taina' (Las Casas V.307). *kunuku* es la forma papiamenta del español *conuco*, taíno de origen. Filtro 4.",
    },
    "maure": {
        "aparece": "lema",
        "pagina": 216,
        "forma_alvarado": 'MÁURE',
        "cita": "'Son a fuer de faxas mujeriles muy curiosas'. — — (Carv. 168). || En Coro vale la voz por pieza de dril fuerte para pantalones. (Véase Ernst, La Bxp. 561). '*A otros más honestos un pedazo De maure cubre partes impuden| tes'. (Castellanos, Bleg. 2^ pte. introduce.) MÁUTE. — Becer",
        "veredicto": "confirma",
        "razon": "Carvajal 168 y Castellanos la registran como faja/tejido; en Coro vivía en 1921 como 'pieza de dril'. La glosa del lexicón ('fibra, hilo para tejer') es compatible.",
    },
    "mazato": {
        "aparece": "lema",
        "pagina": 217,
        "forma_alvarado": 'MAZATO',
        "cita": "Sustancia alimenticia líquida preparada con maíz. 'Qierto brevaje, que es muy espeso como magamorra o puches, que en algunas partes de España llaman poleadas o cabinas; y este magato es algo acedo, y tiénenlo por muy exgelente brevaje'. (Ov. IL 297, 300).—'Tampoco (ha ha bido var",
        "veredicto": "confirma",
        "razon": "Oviedo II.297,300 ('magato… brevaje'). Confirma la glosa. La forma es panamericana (masato peruano): filiación caquetía NO confirmada.",
    },
    "mene": {
        "aparece": "lema",
        "pagina": 218,
        "forma_alvarado": 'MÉNE',
        "cita": "'Betún a manera de brea o pez derretida'. (Oviedo, II. 301). ^'Múne es una goma negra de Tierra Fir— me, de la que se sirven como de la pez'. (Bretón, Dice. car. fr.). 'Minas inagotables de menc o pez mineral hai en las provincias de Mérida y Coro, y sobre todo en la de Maracaibo",
        "veredicto": "confirma",
        "razon": "Oviedo II.301 ('betún a manera de brea') + Codazzi localiza los yacimientos en Coro y Maracaibo. Glosa del lexicón compatible.",
    },
    "na": {
        "aparece": "mención",
        "pagina": 26,
        "forma_alvarado": None,
        "cita": "SACAR [26] BEJUCO. No lograr lo q. uno se II propone. 'M'as vale que Usted se vaye y no me diga más ná, porque conmigo no saca bejuco'. (Romero G., Peonía, — 222). ^AGAjERO. Planta sarmentosa, de hojas opuestas, en II teras, disticas ; flores temadas, corola g",
        "veredicto": "no-concluyente",
        "razon": "Los hits son la elisión coloquial de 'nada'. Sin evidencia.",
    },
    "pariri": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "paro": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "pauji": {
        "aparece": "lema",
        "pagina": 244,
        "forma_alvarado": 'PAUJÍ',
        "cita": "Bumclia huxifolia. Sapotáceas. Árbol espinoso, de hojas elípticas, redondeadas en el ápice, acuñadas en la base, enterísimas, medio coriáceas, lampiñas, relucientes; flores pequeñas, blancas ; cáliz lampiño con 5-6 laqnias elípticas, semirredondeadas ; corola hemisférico-campanul",
        "veredicto": "reclasifica",
        "razon": "CONFLICTO DE GLOSA (D7): en Alvarado paují es un ÁRBOL (Bumelia buxifolia, Sapotáceas; cf. IGÜÍ p.175 'Paují… Coro'), derivado del chaima. El lexicón lo glosa como ave ('pavo de monte').",
    },
    "piache": {
        "aparece": "lema",
        "pagina": 248,
        "forma_alvarado": 'PIACHE',
        "cita": "Sacerdote indígena, que, según los casos, era al mismo tiempo brujo, hechicero o herbolario. 'Usaban de médicos que los curasen, a los cuales llamaban Piaches'. (Aguado, I. 458). Voz cháima y tamanaca, con formas afines en otras lenguas caribes.",
        "veredicto": "reclasifica",
        "razon": "'Voz cháima y tamanaca, con formas afines en otras lenguas caribes'. Es la palabra para chamán: el error es visible en toda la simulación.",
    },
    "poporo": {
        "aparece": "lema",
        "pagina": 255,
        "forma_alvarado": 'POPORO',
        "cita": "Arma, a manera de porra, usada por los an tiguos Caquetíos y los Guagíros. Ref. Cast. Bleg. I. c. 3?; — A^. Reino, I. 46. 65. Cf. Bapóron, Tolondro, lobanillo, || chichón, tumor, o cosa así.~'Ya tendrá para entretenerse con los poporos y cardenales que le hice'. (Tosta G., Bl 19 ",
        "veredicto": "confirma",
        "razon": "Alvarado la atribuye a los antiguos Caquetíos y cita a Castellanos. La glosa del lexicón ('maza-porra, arma de combate') coincide. → `caquetío-atestiguado` queda JUSTIFICADO, con cita.",
    },
    "quidi": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "rao": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "sabuenen": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "saruro": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "sawaka": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "tabri": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "tara": {
        "aparece": "mención",
        "pagina": 283,
        "forma_alvarado": None,
        "cita": "ado. (Lo mismo que Ta TÁo?). — * [283] TAPARA. Fruto del Taparo, y vasija aderezada con ese fruto. 'Tara hacer la caza de los patos comenzaban por echar al agua muchas taparas'. (Cod. 256).—^**El que bebe agua en tapara, | o se casa en tierra ajena, | no sabe",
        "veredicto": "no-concluyente",
        "razon": "No es lema autónomo. En el glosario 'tara' aparece como polilla/mariposa (cf. TARÍTA 'mariposa o tara pequeña'), no como venado.",
    },
    "tarica": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "tata": {
        "aparece": "mención",
        "pagina": 71,
        "forma_alvarado": None,
        "cita": "r. kumakodóma, tam. kiauko-imo, cum. kiaueke-noto, kal. kumaka-yumu. Entre los indígenas de He rida tata-cuá, en el Ec. runavinci-mama) . Supónese entre el vulgo que son dobleandadores, que son venenosísimos, y por fin que son remedio soberano para hernias y f",
        "veredicto": "no-concluyente",
        "razon": "Solo en 'tata-cuá' (indígenas de Mérida) y en 'patata'. 'Tata' = padre es panamericano y romance-infantil: no sirve como evidencia.",
    },
    "tebe": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "tuqueque": {
        "aparece": "lema",
        "pagina": 300,
        "forma_alvarado": 'TUQUEQUE',
        "cita": "Saurios de la familia de los Ascalabo tos, de dientes implantados en el borde interno de la man díbula, faltando los palatinos; ojos grandes, sin párpados; lengua corta, gruesa, carnosa; artejos con pelotas adheren tes y garras casi siempre retráctiles; vértebras bicóncavas. Son ",
        "veredicto": "confirma",
        "razon": "Glosa idéntica (geco: Thecadactylus rapicaudus / Gonatodes albogularis). Pero Alvarado NO da origen ni localiza en Coro: confirma la GLOSA, no la filiación caquetía.",
    },
    "ture": {
        "aparece": "lema",
        "pagina": 301,
        "forma_alvarado": 'TURE',
        "cita": "Asiento pequeño de forma particular. Us. en Cumaná y Margarita. Es lo mismo que el butaque de Occidente. Voz cháima, que Tauste traduce: asiento pequeño de madera. Cf . duro, arriba.",
        "veredicto": "reclasifica",
        "razon": "Doble reclasificación: la glosa es 'asiento pequeño' (no 'vasija de barro') y la lengua es cháima (Tauste), usada en Cumaná y Margarita.",
    },
    "ucibo": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "urapa": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "wabarsure": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE del glosario: ni como lema ni como mención. Alvarado no adjudica ni a favor ni en contra.",
    },
    "warawara": {
        "aparece": "no",
        "pagina": None,
        "forma_alvarado": None,
        "cita": "",
        "veredicto": "no-concluyente",
        "razon": "AUSENTE (Alvarado registra GUARAGUAO como nombre del samuro en Margarita, no *warawara*).",
    },
    "watapana": {
        "aparece": "lema",
        "pagina": 163,
        "forma_alvarado": 'GUATAPANAR',
        "cita": "Caesalpinia coriaria. Dividive:. Del cum. aragiiatapanár, oreja de araguato, por la forma del fru to, sin duda. Entre los Guayuncomos del Alto Orinoco, arauo tá-fanári (oreja de araguato) es nombre propio. Ruiz Blan co traduce Ébano, sin duda por el color negro intenso de la made",
        "veredicto": "reclasifica",
        "razon": "Alvarado registra la forma venezolana GUATAPANAR y la deriva del cum. 'araguatapanár' (oreja de araguato). La forma *watapana* del lexicón es la papiamenta de las islas ABC (→ van-buurt-2014), no un caquetío atestiguado en tierra firme.",
    },
}


# ==================================================================
# CADENA DE CUSTODIA — sigla `A` de Zavala → página de Alvarado 1921
# ==================================================================
# Lisandro Alvarado es el compilador `A` del glosario de Zavala Reyes
# 2015. Toda entrada del lexicón con esa sigla debe poder rastrearse a
# una página concreta de ESTE glosario, o la cita es de tercera mano.
# Resultado: 24/26 rastreadas.
CADENA_CUSTODIA_ZAVALA_A: dict[str, dict] = {
    "bachure": {"pagina": 19, "lema_alvarado": "BACHURE", "texto": "Maneto, patituerto. Us. en Coro."},
    "barabara": {"pagina": 21, "lema_alvarado": "BARABARA", "texto": "Clavija ornata, C. macrocarpa. Mirsináceas. Árbol de Coro. ''Madera dura y pesada, semejante a la de las especies de Jacquinia; se conoce fácilmente p"},
    "cachipo": {"pagina": 43, "lema_alvarado": "CACHÍPO", "texto": "Heliconia Bihai. Bijao, arriba. Ref. Gilii, — En I. 18o. 1 -Pecíolo- de la hoja seca y caduca del banano. — 1 arec. kasipa. Sin. Baje^ro. En Coro es v"},
    "cacuro": {"pagina": 40, "lema_alvarado": "CACURO", "texto": "En Coro significa avispero. ."},
    "camaroa": {"pagina": 48, "lema_alvarado": "CAMARÓA", "texto": "Árbol lactescente de Coro, de hojas algo parecidas a las del Papayo."},
    "caquetillo": {"pagina": 56, "lema_alvarado": "CAQUETILLO", "texto": "Árbol de construcción del Zulia. ¿Voz afín de caquetío?"},
    "chaguanco": {"pagina": 112, "lema_alvarado": "CHAGUÁNCO", "texto": "Zorro. Voz usada en Coro. AGUARÁ CPI"},
    "dacagua": {"pagina": 130, "lema_alvarado": "DACÁGUA", "texto": "Árbol de Coro y Barquisimeto, de corteza gris cenicienta cuando seca ; madera compacta, de color amarillento uniforme. Da trozos de 5 a 6 pulgadas de "},
    "guacuaro": {"pagina": 143, "lema_alvarado": "GUACUARO", "texto": "Palo de tinte que se produce en Coro."},
    "guamacho": {"pagina": 148, "lema_alvarado": "GUAMÁCHO", "texto": "Nombre dado a varios árboles del géne ro Pcreskia, fam. de las Cactáceas, cuyo tronco está cubierto de manojillos de espinas en disposición quincuncia"},
    "isiro": {"pagina": 176, "lema_alvarado": "ISÍRO", "texto": "Árbol de construcción de Coro."},
    "jajato": {"pagina": 178, "lema_alvarado": "JAJÁTO", "texto": "Chloris radíala. Especie de yerba forrajera. Sin. Pata de gai.lina."},
    "laguari": {"pagina": 184, "lema_alvarado": "LAUADRÍ", "texto": "Árbol indeterminado del E. Falcón. D. t. Laguadrí."},
    "orumo": {"pagina": 234, "lema_alvarado": "ORÚMO", "texto": "Myrcia cHcullata. Mirtáceas. 1—En Coro, el 1 AFÁMATE (?). Madera poco densa, fibrosa, pardusca o ama — rillenta matizada, del aspecto de la del pardil"},
    "paugis": {"pagina": 244, "lema_alvarado": "PAUJÍ", "texto": "Bumclia huxifolia. Sapotáceas. Árbol espinoso, de hojas elípticas, redondeadas en el ápice, acuñadas en la base, enterísimas, medio coriáceas, lampiña"},
    "piritu": {"pagina": 253, "lema_alvarado": "PÍRITU", "texto": "Bactris Piritu. Pequeña palmera, alta de 5 a 7 m., de tallo recto, delgado, cilindrico, con cicatrices peciolares de trecho en trecho y espinas negras"},
    "quiguagua": {"pagina": 261, "lema_alvarado": "GUAGUA", "texto": "Especie de haba de Coro, grande y blanca. Cf. Caráota chivata."},
    "ruba": {"pagina": 266, "lema_alvarado": "RÚBA", "texto": "Especie de abeja silvestre negra de Coro. Véa— se RuBÍTA. 1 Planta de Mérida, y su raíz, que es un tu1 bérculo como la patata. Ref. Pie. 300."},
    "sibidigua": {"pagina": 277, "lema_alvarado": "SIBIDÍGUA", "texto": "Jatropha gossypifolia. Túatúa. Voz us. en Lara y Falcón."},
    "surupa": {"pagina": 279, "lema_alvarado": "SURÚPA", "texto": "Blatta orientalis. Corredera, curiana. Sú rrttja en guajibo es cucaréicha; debe ser corrupción de su RÚPV, que a su vez parece tener la misma raíz que"},
    "turupia": {"pagina": 302, "lema_alvarado": "TURÚPIA", "texto": "Acacia sp. Especie de acacia o cují de Co ro. Cf. Trupillo."},
    "ubeda": {"pagina": 303, "lema_alvarado": "ÚBEDA", "texto": "Acacia foetida. Mapurite:, Cují hediondo."},
    "yabo": {"pagina": 307, "lema_alvarado": "YABO", "texto": "Ccrcidium viride. Leguminosas. Árbol no muí elevado, ramoso, de tronco verde, resinoso ; hojas recompuestas, con 1 ó 2 pares de pínulas, y estas con 5"},
    "yagruma": {"pagina": 309, "lema_alvarado": "YAGRUMA", "texto": "En Coro es lo mismo que caracol (mo lusco )"},
    "cocuy": {"pagina": None, "lema_alvarado": None, "texto": "p.84, dentro del bloque COCUY/COCUIZA que el OCR fusionó ('D. t. cucúi, que es la forma primitiva')"},
    "guay": {"pagina": None, "lema_alvarado": None, "texto": "p.145, leído por el OCR como 'GUÁL. Bombax sp. Ceiba. Voz usada en Coro'"},
}


TOTALES = {
    "lemas_parseados": 1551,
    "evaluados": 109,
    "nivel_A": 3,
    "nivel_B": 36,
    "nivel_C": 13,
    "nivel_D": 57,
    "f1_confirma": 7,
    "f1_no_concluyente": 64,
    "f1_reclasifica": 11,
    "cadena_zavala_A_total": 26,
    "cadena_zavala_A_trazadas": 24,
}
