"""
CURIANA — Tabla A-2 de Oliver: la columna añú y el refuerzo lokono (D11)
========================================================================

GENERADO por `minar_a2_swadesh.py` — no editar a mano; la fuente es
6-fusion/tabla_a2_transcripcion.yaml (transcripción a ojo, 2026-08-31,
pendiente de segunda pasada de Miguel contra la imagen).

Implementa el rumbo de D11 (#39): rebalancear con lokono y abrir la
columna añú/paraujano (tenía CERO entradas del pariente costero más
cercano). Es vocabulario de COMPARACIÓN: alimenta la detección de fugas
de score_linguistico y las columnas del filtro fonotáctico. NO es habla
de agentes y no redefine el núcleo reconstruido (sesgo declarado del
cómputo de D11 — decisiones_tanda_2026-08-30.yaml §d11_rumbo).
"""


PARAUJANO_A2: dict[str, dict] = {
    "anai": {"es": "bueno", "fuente": "paraujano", "categoria": "cualidades", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 97 'good'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "ayip": {"es": "noche", "fuente": "paraujano", "categoria": "cosmos", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 92 'night'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "añu": {"es": "persona, gente", "fuente": "paraujano", "categoria": "parentesco", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 18 'person'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "chighe": {"es": "fuego", "fuente": "paraujano", "categoria": "utiles", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 82 'fire'; variantes: chigiga. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "eichire": {"es": "hombre", "fuente": "paraujano", "categoria": "parentesco", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 17 'man'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "hikiko": {"es": "todo, todos", "fuente": "paraujano", "categoria": "gramatica", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 9 'all'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "hniere": {"es": "mujer", "fuente": "paraujano", "categoria": "parentesco", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 16 'woman'; variantes: ñerika, añukar. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "ipah": {"es": "piedra", "fuente": "paraujano", "categoria": "geografia", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 77 'stone'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "jaradu": {"es": "seco", "fuente": "paraujano", "categoria": "cualidades", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 99 'dry'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "jatuge": {"es": "estrella", "fuente": "paraujano", "categoria": "cosmos", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 74 'star'; variantes: hatuge. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "jebagar": {"es": "rojo", "fuente": "paraujano", "categoria": "cualidades", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 87 'red'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "jeddiga": {"es": "pequeño", "fuente": "paraujano", "categoria": "cualidades", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 15 'small'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "jinghi": {"es": "árbol", "fuente": "paraujano", "categoria": "flora", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 23 'tree'; variantes: jiki. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "jirama": {"es": "cielo", "fuente": "paraujano", "categoria": "cosmos", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 80b 'sky'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "jirorgho": {"es": "nuevo", "fuente": "paraujano", "categoria": "cualidades", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 96 'new'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "jiyi": {"es": "garra, uña", "fuente": "paraujano", "categoria": "cuerpo", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 45 'claw'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "jundo": {"es": "corteza", "fuente": "paraujano", "categoria": "flora", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 27 'bark'; fila 28 'skin'; nota de la celda: =cuero. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "kaaya": {"es": "muchos", "fuente": "paraujano", "categoria": "gramatica", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 10 'many'; variantes: kaije. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "kai": {"es": "sol", "fuente": "paraujano", "categoria": "cosmos", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 72 'sun'; variantes: kei. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "keeti": {"es": "qué", "fuente": "paraujano", "categoria": "gramatica", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 7 'what'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "keichare": {"es": "luna", "fuente": "paraujano", "categoria": "cosmos", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 73 'moon'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "manei": {"es": "uno", "fuente": "paraujano", "categoria": "numerales", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 11 'one'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "mmo": {"es": "tierra", "fuente": "paraujano", "categoria": "geografia", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 79 'earth'; variantes: mogho. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "mo": {"es": "arena", "fuente": "paraujano", "categoria": "geografia", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 78 'sand'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "nawa": {"es": "no, negación", "fuente": "paraujano", "categoria": "gramatica", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 8 'not'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "ougda": {"es": "nadar", "fuente": "paraujano", "categoria": "acciones", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 63 'swim'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "pimu": {"es": "dos", "fuente": "paraujano", "categoria": "numerales", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 12 'two'; variantes: pimi. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "shira": {"es": "ese, esa", "fuente": "paraujano", "categoria": "gramatica", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 5 'that'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "tai": {"es": "diente", "fuente": "paraujano", "categoria": "cuerpo", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 43 'tooth'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "taki": {"es": "cabeza", "fuente": "paraujano", "categoria": "cuerpo", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 38 'head'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "tap": {"es": "mano", "fuente": "paraujano", "categoria": "cuerpo", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 48 'hand'; variantes: aapi. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "tapat": {"es": "pie", "fuente": "paraujano", "categoria": "cuerpo", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 46 'foot'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "tawala": {"es": "pelo, cabello", "fuente": "paraujano", "categoria": "cuerpo", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 37 'hair'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "tayiri": {"es": "pecho, seno", "fuente": "paraujano", "categoria": "cuerpo", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 51 'breast'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "tayu": {"es": "vientre, barriga", "fuente": "paraujano", "categoria": "cuerpo", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 49 'belly'; variantes: hyure. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "tehenye": {"es": "lengua", "fuente": "paraujano", "categoria": "cuerpo", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 44 'tongue'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "teiyi": {"es": "nariz", "fuente": "paraujano", "categoria": "cuerpo", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 41 'nose'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "togoin": {"es": "cuello", "fuente": "paraujano", "categoria": "cuerpo", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 50 'neck'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "tou": {"es": "ojo", "fuente": "paraujano", "categoria": "cuerpo", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 40 'eye'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "tounaga": {"es": "boca", "fuente": "paraujano", "categoria": "cuerpo", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 42 'mouth'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "utschi": {"es": "cerro, montaña", "fuente": "paraujano", "categoria": "geografia", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 86 'mountain'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "wegani": {"es": "nosotros", "fuente": "paraujano", "categoria": "gramatica", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 3 'we'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "wiagha": {"es": "lluvia", "fuente": "paraujano", "categoria": "cosmos", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 76 'rain'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "win": {"es": "agua", "fuente": "paraujano", "categoria": "geografia", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 75 'water'; variantes: winkari. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "you": {"es": "largo", "fuente": "paraujano", "categoria": "cualidades", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 14 'long'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "youghe": {"es": "grande", "fuente": "paraujano", "categoria": "cualidades", "notas": "Wilbert 1958-59 (Sinamaica) vía Oliver 1989, Apéndice A, Tabla A-2, fila 13 'big'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
}


LOKONO_A2: dict[str, dict] = {
    "ada": {"es": "árbol", "fuente": "lokono", "categoria": "flora", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 23 'tree'; variantes: kunnuku. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "adada": {"es": "corteza", "fuente": "lokono", "categoria": "flora", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 27 'bark'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "adobona": {"es": "hoja", "fuente": "lokono", "categoria": "flora", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 25 'leaf'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "ahonaha": {"es": "hueso", "fuente": "lokono", "categoria": "cuerpo", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 31 'bone'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "aithin": {"es": "saber, conocer", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 59 'know'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "akan": {"es": "decir", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 71 'say'; variantes: dian, man. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "andin": {"es": "venir", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 66 'come'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "arii": {"es": "diente", "fuente": "lokono", "categoria": "cuerpo", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 43 'tooth'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "balala": {"es": "redondo", "fuente": "lokono", "categoria": "cualidades", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 98 'round'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "balatin": {"es": "estar sentado", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 68 'sit'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "balisi": {"es": "ceniza", "fuente": "lokono", "categoria": "utiles", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 83 'ash'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "bii": {"es": "tú", "fuente": "lokono", "categoria": "gramatica", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 2 'thou'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "bithin": {"es": "arder, quemar", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 84 'burn'; variantes: bithonoan. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "dei": {"es": "yo", "fuente": "lokono", "categoria": "gramatica", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 1 'I'; variantes: dai. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "dikhin": {"es": "ver", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 57 'see'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "dinamin": {"es": "estar de pie", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 69 'stand'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "donkon": {"es": "dormir", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 60 'sleep'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "farin": {"es": "matar", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 62 'kill'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "hadali": {"es": "sol", "fuente": "lokono", "categoria": "cosmos", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 72 'sun'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "halikan": {"es": "quién", "fuente": "lokono", "categoria": "gramatica", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 6 'who'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "hime": {"es": "pez", "fuente": "lokono", "categoria": "fauna", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 19 'fish'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "hororo": {"es": "tierra", "fuente": "lokono", "categoria": "geografia", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 79 'earth'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "ichi": {"es": "piojo", "fuente": "lokono", "categoria": "fauna", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 22 'louse'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "ida": {"es": "piel, cuero", "fuente": "lokono", "categoria": "cuerpo", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 28 'skin'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "iikirahi": {"es": "raíz", "fuente": "lokono", "categoria": "flora", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 26 'root'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "isii": {"es": "semilla", "fuente": "lokono", "categoria": "flora", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 24 'seed'; fila 38 'head'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "ite": {"es": "vientre, barriga", "fuente": "lokono", "categoria": "cuerpo", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 49 'belly'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "kanabon": {"es": "oír", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 58 'hear'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "kasako": {"es": "cielo", "fuente": "lokono", "categoria": "cosmos", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 80b 'sky'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "kathi": {"es": "luna", "fuente": "lokono", "categoria": "cosmos", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 73 'moon'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "khoton": {"es": "comer", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 55 'eat'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "kodibiosa": {"es": "huevo", "fuente": "lokono", "categoria": "fauna", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 33 'egg'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "konan": {"es": "caminar", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 65 'walk'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "koreeli": {"es": "humo", "fuente": "lokono", "categoria": "utiles", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 81 'smoke'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "morodon": {"es": "volar", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 64 'fly'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "mothoko": {"es": "arena", "fuente": "lokono", "categoria": "geografia", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 78 'sand'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "oaboroko": {"es": "camino, senda", "fuente": "lokono", "categoria": "geografia", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 85 'path'; variantes: abonaha. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "oadili": {"es": "hombre", "fuente": "lokono", "categoria": "parentesco", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 17 'man'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "oai": {"es": "nosotros", "fuente": "lokono", "categoria": "gramatica", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 3 'we'; variantes: oei. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "oioa": {"es": "estrella", "fuente": "lokono", "categoria": "cosmos", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 74 'star'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "oloa": {"es": "corazón", "fuente": "lokono", "categoria": "cuerpo", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 52 'heart'; variantes: kakin. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "oraro": {"es": "nube", "fuente": "lokono", "categoria": "cosmos", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 80 'cloud'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "orebe": {"es": "caliente", "fuente": "lokono", "categoria": "cualidades", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 93 'hot'; nota de la celda: =warm. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "orika": {"es": "noche", "fuente": "lokono", "categoria": "cosmos", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 92 'night'; variantes: kasakoda. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "ridin": {"es": "morder", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 56 'bite'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "sirihi": {"es": "nariz", "fuente": "lokono", "categoria": "cuerpo", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 41 'nose'; variantes: siri. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "sirokoho": {"es": "carne", "fuente": "lokono", "categoria": "cuerpo", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 29 'flesh'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
    "torodon": {"es": "estar acostado", "fuente": "lokono", "categoria": "acciones", "notas": "Oliver 1989, Apéndice A, Tabla A-2, columna arawak/lokono, fila 67 'lie'. Transcripción a ojo del 2026-08-31, pendiente de verificación contra la imagen (D11 #39). Vocabulario de comparación, no habla de agentes"},
}


# Lo que NO entró, con su motivo — formas ligadas, reconstrucciones (*),
# segmentos opcionales, dudosas y marcas de préstamo. Es material
# comparativo de primera; solo que no son lemas de lexicón.
REFERENCIA_A2: dict[str, list] = {
    "paraujano": [
        ("1", "I", "te-", "forma ligada (guion): morfología, no lema"),
        ("1", "I", "ta-", "forma ligada (guion): morfología, no lema"),
        ("3", "we", "we-", "forma ligada (guion): morfología, no lema"),
        ("4", "this", "(tyi)", "segmento opcional entre paréntesis"),
        ("8", "not", "nou-", "forma ligada (guion): morfología, no lema"),
        ("19", "fish", "(oih) SPECIES", "préstamo o marca de Oliver, no forma nativa"),
        ("20", "bird", "SPANISH", "préstamo o marca de Oliver, no forma nativa"),
        ("21", "dog", "SPANISH (y-eri)", "préstamo o marca de Oliver, no forma nativa"),
        ("32", "fat", "kougdo (?) (=gordo?)", "transcripción dudosa «(?)» — verificar contra la imagen"),
        ("38", "head", "-ki", "forma ligada (guion): morfología, no lema"),
        ("39", "ear", "tachoo (ch=ty)", "segmento opcional entre paréntesis"),
        ("44", "tongue", "-weña", "forma ligada (guion): morfología, no lema"),
        ("47", "knee", "tai otroh (?)", "transcripción dudosa «(?)» — verificar contra la imagen"),
        ("52", "heart", "t-ein", "forma ligada (guion): morfología, no lema"),
        ("54", "drink", "hnooti (drank)", "segmento opcional entre paréntesis"),
        ("55", "eat", "akina-tete", "forma ligada (guion): morfología, no lema"),
        ("60", "sleep", "ata-mite", "forma ligada (guion): morfología, no lema"),
        ("61", "die", "oikti (died)", "segmento opcional entre paréntesis"),
        ("80", "cloud", "SPANISH", "préstamo o marca de Oliver, no forma nativa"),
        ("85", "path", "wobu(h)", "segmento opcional entre paréntesis"),
        ("88", "green", "SPANISH", "préstamo o marca de Oliver, no forma nativa"),
        ("89", "yellow", "SPANISH", "préstamo o marca de Oliver, no forma nativa"),
        ("90", "white", "SPANISH", "préstamo o marca de Oliver, no forma nativa"),
        ("91", "black", "SPANISH", "préstamo o marca de Oliver, no forma nativa"),
        ("97", "good", "kama-chichiri", "forma ligada (guion): morfología, no lema"),
    ],
    "lokono": [
        ("1", "I", "*day", "reconstrucción/atestación vieja de Oliver (*)"),
        ("4", "this", "tho(h)o", "segmento opcional entre paréntesis"),
        ("4", "this", "li(h)i", "segmento opcional entre paréntesis"),
        ("5", "that", "thora(h)a", "segmento opcional entre paréntesis"),
        ("5", "that", "lira(h)a", "segmento opcional entre paréntesis"),
        ("8", "not", "kho(ro)", "segmento opcional entre paréntesis"),
        ("9", "all", "*tumakua", "reconstrucción/atestación vieja de Oliver (*)"),
        ("9", "all", "hara-", "forma ligada (guion): morfología, no lema"),
        ("10", "many", "io(h)o", "segmento opcional entre paréntesis"),
        ("11", "one", "aba-", "forma ligada (guion): morfología, no lema"),
        ("13", "big", "(i)firo", "segmento opcional entre paréntesis"),
        ("13", "big", "(i)fili-", "forma ligada (guion): morfología, no lema"),
        ("14", "long", "oadi-", "forma ligada (guion): morfología, no lema"),
        ("15", "small", "ibi-", "forma ligada (guion): morfología, no lema"),
        ("15", "small", "sioko-", "forma ligada (guion): morfología, no lema"),
        ("21", "dog", "SPANISH", "préstamo o marca de Oliver, no forma nativa"),
        ("22", "louse", "-ie", "forma ligada (guion): morfología, no lema"),
        ("24", "seed", "-si", "forma ligada (guion): morfología, no lema"),
        ("25", "leaf", "-bana", "forma ligada (guion): morfología, no lema"),
        ("26", "root", "-ikira", "forma ligada (guion): morfología, no lema"),
        ("27", "bark", "-da", "forma ligada (guion): morfología, no lema"),
        ("28", "skin", "-da", "forma ligada (guion): morfología, no lema"),
        ("29", "flesh", "-siroko", "forma ligada (guion): morfología, no lema"),
        ("30", "blood", "ithihi/-china (?)", "transcripción dudosa «(?)» — verificar contra la imagen"),
        ("31", "bone", "-bona", "forma ligada (guion): morfología, no lema"),
        ("32", "fat", "iki(h)i", "segmento opcional entre paréntesis"),
        ("33", "egg", "-sa", "forma ligada (guion): morfología, no lema"),
        ("34", "horn", "*tukua", "reconstrucción/atestación vieja de Oliver (*)"),
        ("34", "horn", "-(o)koa", "forma ligada (guion): morfología, no lema"),
        ("35", "tail", "i(h)itoko", "segmento opcional entre paréntesis"),
        ("35", "tail", "-i(h)i", "forma ligada (guion): morfología, no lema"),
        ("36", "feather", "(o)bara/-hara (?)", "transcripción dudosa «(?)» — verificar contra la imagen"),
        ("37", "hair", "(o)bara", "segmento opcional entre paréntesis"),
        ("37", "hair", "-bara", "forma ligada (guion): morfología, no lema"),
        ("38", "head", "*dasi", "reconstrucción/atestación vieja de Oliver (*)"),
        ("38", "head", "-si", "forma ligada (guion): morfología, no lema"),
        ("39", "ear", "*dike", "reconstrucción/atestación vieja de Oliver (*)"),
        ("39", "ear", "-dike", "forma ligada (guion): morfología, no lema"),
        ("39", "ear", "-koioko", "forma ligada (guion): morfología, no lema"),
        ("40", "eye", "*dacusi", "reconstrucción/atestación vieja de Oliver (*)"),
        ("40", "eye", "-kosi", "forma ligada (guion): morfología, no lema"),
        ("42", "mouth", "-reroko", "forma ligada (guion): morfología, no lema"),
        ("43", "tooth", "-ari", "forma ligada (guion): morfología, no lema"),
        ("44", "tongue", "*daiya", "reconstrucción/atestación vieja de Oliver (*)"),
        ("44", "tongue", "-iee", "forma ligada (guion): morfología, no lema"),
        ("45", "claw", "-bada", "forma ligada (guion): morfología, no lema"),
        ("46", "foot", "*dacuti", "reconstrucción/atestación vieja de Oliver (*)"),
        ("46", "foot", "-koti", "forma ligada (guion): morfología, no lema"),
        ("47", "knee", "*dacuruji", "reconstrucción/atestación vieja de Oliver (*)"),
        ("47", "knee", "-koro", "forma ligada (guion): morfología, no lema"),
        ("47", "knee", "*-culu-siba", "reconstrucción/atestación vieja de Oliver (*)"),
        ("48", "hand", "*dacabu", "reconstrucción/atestación vieja de Oliver (*)"),
        ("48", "hand", "-khabo", "forma ligada (guion): morfología, no lema"),
        ("49", "belly", "*dibeyu-", "reconstrucción/atestación vieja de Oliver (*)"),
        ("49", "belly", "-dibeio", "forma ligada (guion): morfología, no lema"),
        ("50", "neck", "-noro", "forma ligada (guion): morfología, no lema"),
        ("51", "breast", "-dio", "forma ligada (guion): morfología, no lema"),
        ("52", "heart", "-oasina", "forma ligada (guion): morfología, no lema"),
        ("53", "liver", "-bana", "forma ligada (guion): morfología, no lema"),
        ("54", "drink", "(a)-thin", "forma ligada (guion): morfología, no lema"),
        ("54", "drink", "(a)-than", "forma ligada (guion): morfología, no lema"),
        ("55", "eat", "(e)kin", "segmento opcional entre paréntesis"),
        ("57", "see", "*adikin", "reconstrucción/atestación vieja de Oliver (*)"),
        ("58", "hear", "*kanabun", "reconstrucción/atestación vieja de Oliver (*)"),
        ("60", "sleep", "*adumka", "reconstrucción/atestación vieja de Oliver (*)"),
        ("61", "die", "(h)odon", "segmento opcional entre paréntesis"),
        ("61", "die", "*ahudun", "reconstrucción/atestación vieja de Oliver (*)"),
        ("62", "kill", "*ap(h)aru-", "reconstrucción/atestación vieja de Oliver (*)"),
        ("63", "swim", "*at(h)imun", "reconstrucción/atestación vieja de Oliver (*)"),
        ("65", "walk", "*-kunna-", "reconstrucción/atestación vieja de Oliver (*)"),
        ("65", "walk", "*iyahadun", "reconstrucción/atestación vieja de Oliver (*)"),
        ("66", "come", "*andin (arrive)", "reconstrucción/atestación vieja de Oliver (*)"),
        ("75", "water", "-nia", "forma ligada (guion): morfología, no lema"),
        ("77", "stone", "-siban", "forma ligada (guion): morfología, no lema"),
        ("79", "earth", "-orora", "forma ligada (guion): morfología, no lema"),
        ("80b", "sky", "*kasaku", "reconstrucción/atestación vieja de Oliver (*)"),
        ("81", "smoke", "*kuleheli", "reconstrucción/atestación vieja de Oliver (*)"),
        ("82", "fire", "jiki(h)i", "segmento opcional entre paréntesis"),
        ("82", "fire", "-ihime", "forma ligada (guion): morfología, no lema"),
        ("84", "burn", "*tibittua", "reconstrucción/atestación vieja de Oliver (*)"),
        ("86", "mountain", "hororo sin", "forma compuesta/multi-palabra"),
        ("87", "red", "kore(e)-", "forma ligada (guion): morfología, no lema"),
        ("88", "green", "(imoro-)", "forma ligada (guion): morfología, no lema"),
        ("89", "yellow", "(hehe-)", "forma ligada (guion): morfología, no lema"),
        ("90", "white", "harira-", "forma ligada (guion): morfología, no lema"),
        ("91", "black", "khareme-", "forma ligada (guion): morfología, no lema"),
        ("91", "black", "*keremero", "reconstrucción/atestación vieja de Oliver (*)"),
        ("93", "hot", "there-", "forma ligada (guion): morfología, no lema"),
        ("94", "cold", "mimili-", "forma ligada (guion): morfología, no lema"),
        ("95", "full", "(h)ebe-", "forma ligada (guion): morfología, no lema"),
        ("95", "full", "*-ibe-", "reconstrucción/atestación vieja de Oliver (*)"),
        ("95", "full", "*-ebe-", "reconstrucción/atestación vieja de Oliver (*)"),
        ("96", "new", "(h)emelea-", "forma ligada (guion): morfología, no lema"),
        ("96", "new", "-emelia-", "forma ligada (guion): morfología, no lema"),
        ("97", "good", "sa-", "forma ligada (guion): morfología, no lema"),
        ("97", "good", "*u-sa-", "reconstrucción/atestación vieja de Oliver (*)"),
        ("99", "dry", "oaa-", "forma ligada (guion): morfología, no lema"),
        ("99", "dry", "sare-", "forma ligada (guion): morfología, no lema"),
        ("99", "dry", "*wahado", "reconstrucción/atestación vieja de Oliver (*)"),
        ("100", "name", "-iri", "forma ligada (guion): morfología, no lema"),
    ],
}


# Formas de la A-2 que YA son clave del lexicón: no se pisan, y la
# coincidencia es dato areal (el paraujano compartiendo forma con el
# núcleo es exactamente la señal que el hallazgo 1 de la transcripción
# describe para el guajiro).
COLISIONES_A2: list[tuple] = [
    ("paraujano", "2", "thou", "pia"),
    ("paraujano", "4", "this", "chi"),
    ("lokono", "7", "what", "hamaha"),
    ("lokono", "12", "two", "biama"),
    ("lokono", "16", "woman", "hiaro"),
    ("lokono", "18", "person", "loko"),
    ("lokono", "20", "bird", "kodibio"),
    ("lokono", "63", "swim", "thimin"),
    ("lokono", "70", "give", "sikin"),
    ("lokono", "75", "water", "oniabo"),
    ("lokono", "76", "rain", "oni"),
    ("lokono", "77", "stone", "siba"),
]

TOTALES_A2 = {
    "paraujano": 46,
    "lokono": 48,
    "referencia": 125,
    "colisiones": 12,
}
